<?php
/**
 * Copyright 2018 Klarna AB
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$sLangName = "Italiano";
// -------------------------------
// RESOURCE IDENTITFIER = STRING
// -------------------------------
$aLang = array(
    'charset'                                           => 'UTF-8',

    'TCKLARNA_KLARNAMAINMENU'                           => 'Klarna',
    'TCKLARNA_START'                                    => 'Inizio',
    'TCKLARNA_GENERAL_SETTINGS'                         => 'In generale',
    'TCKLARNA_CONFIGURATION'                            => 'Configurazione',
    'TCKLARNA_CONFIGURATION_KCO'                        => 'Configurazione per Klarna Checkout',
    'TCKLARNA_CONFIGURATION_KP'                         => 'Configurazione per i pagamenti Klarna',
    'TCKLARNA_KLARNADESIGN'                             => 'Impostazioni di design',
    'TCKLARNA_EXTERNAL_PAYMENTS'                        => 'Metodi di pagamento esterni',
    'TCKLARNA_EXTRA_MERCHANT_DATA'                      => 'Ulteriori informazioni sul rivenditore',
    'TCKLARNA_BASIC_SETTINGS'                           => 'Impostazioni di base',
    'TCKLARNA_DISCOUNT_TITLE'                           => 'Sconto',

    'tcklarna_tbclklarna_orders'                        => 'Klarna',
    'TCKLARNA_NO_OPTIONS_MODE'                          => 'In questa modalità non sono disponibili impostazioni.',
    'TCKLARNA_CHANGES_SAVED'                            => 'Tutte le impostazioni sono state salvate.',
    'TCKLARNA_EMPTY_FIELDS_WARRNING'                    => 'Se i campi URL vengono lasciati vuoti, ciò potrebbe causare malfunzionamenti del modulo.',

    'TCKLARNA_EASY'                                     => 'Attivare Klarna è semplicissimo',
    'TCKLARNA_PHONE'                                    => 'Telefono',
    'TCKLARNA_EMAIL'                                    => 'E-mail',
    'TCKLARNA_BUSINESS_HOURS'                           => 'Orari di apertura',
    'TCKLARNA_MONDAY'                                   => 'Lunedì',
    'TCKLARNA_TUESDAY'                                  => 'martedì',
    'TCKLARNA_WEDNESDAY'                                => 'mercoledì',
    'TCKLARNA_THURSDAY'                                 => 'Giovedì',
    'TCKLARNA_FRIDAY'                                   => 'Venerdì',
    'TCKLARNA_SATURDAY'                                 => 'Sabato',
    'TCKLARNA_SUNDAY'                                   => 'Domenica',
    'TCKLARNA_YOUR_COUNTRY_SPECIFIC_CREDS'              => 'Le vostre credenziali di accesso specifiche per paese',
    'TCKLARNA_ADD_COUNTRY_SPECIFIC_CREDS'               => 'Aggiungere le credenziali di accesso specifiche per paese',
    'TCKLARNA_COUNTRY'                                  => 'Paese',
    'TCKLARNA_MERCHANT_ID'                              => 'Nome utente API',
    'TCKLARNA_PASSWORD'                                 => 'Password API',
    'TCKLARNA_PORTAL_MERCHANT_ID'                       => 'ID commerciante',
    'TCKLARNA_DEFAULT_SHOP_COUNTRY'                     => 'Paese predefinito del negozio',
    'TCKLARNA_ENABLE_LOGGING'                           => 'Registrazione attiva',
    'TCKLARNA_SEND_ADDITIONAL_PRODUCT_DATA'             => 'Inviare dati aggiuntivi sul prodotto a Klarna?',
    'TCKLARNA_PRODUCT_URLS'                             => 'URL dei prodotti',
    'TCKLARNA_IMAGE_URLS'                               => 'URL delle immagini',
    'TCKLARNA_ENABLE_ANONYMIZATION'                     => 'Rendere anonimo',
    'TCKLARNA_ADD'                                      => 'Aggiungi',


    'TCKLARNA_CHECKOUT_NAME'                            => 'Klarna Checkout',
    'TCKLARNA_PAYMENTS_NAME'                            => 'Pagamenti Klarna',
    'TCKLARNA_CHOOSE_KLARNA_MODULE_MODE'                => 'Selezionare la modalità del modulo Klarna',

    'TCKLARNA_CHECKOUT_DESC'                            => 'La soluzione completa include tutti i principali metodi di pagamento (fattura, acquisto rateale, bonifico immediato, addebito diretto, Mastercard e VISA) ed è ospitata da Klarna. Al momento del pagamento, i vostri clienti devono semplicemente inserire l’indirizzo e-mail e il codice postale e possono scegliere il metodo di pagamento che preferiscono. Il tutto con una sola integrazione.',
    'TCKLARNA_PAYMENTS_DESC'                            => 'Con Klarna i clienti finali possono pagare in tre modi: bonifico immediato, in un secondo momento o a rate. Ciò consente ai clienti finali di provare prima la merce e pagare solo ciò che desiderano tenere, di finanziare i prodotti nel negozio o di pagare immediatamente. Fattura, acquisto rateale, bonifico immediato o addebito diretto possono essere attivati tramite un’integrazione e, grazie alla soluzione iFrame di Klarna, sono sempre aggiornati dal punto di vista legale e dei contenuti.',
    'TCKLARNA_EASY_AND_SECURE_SHOPPING'                 => 'I metodi di pagamento più diffusi. Sicuri e facili da integrare.',
    'TCKLARNA_WELCOME_TO_CONFIGURATION'                 => 'Benvenuti nelle impostazioni di configurazione di Klarna Checkout e Klarna Payments. Qui troverete tutto il necessario per l\'attivazione. Selezionate le voci del sottomenu Klarna nella barra a sinistra per completare la configurazione del modulo.',

    'TCKLARNA_CREATE_USER_ACCOUNT'                      => 'Creare un account cliente nell\'OXID eShop',
    'TCKLARNA_SUBSCRIBE_TO_NEWSLETTER'                  => 'Iscrizione alla newsletter',
    'TCKLARNA_CREATE_USER_ACCOUNT_AND_SUBSCRIBE'        => 'Crea un account cliente E iscriviti alla newsletter',
    'TCKLARNA_NO_CHECKBOX'                              => 'Non visualizzare la casella di selezione',


    /* design */
    'TCKLARNA_DISPLAY_ON_HOME'                          => 'Mostrare nella pagina iniziale dello shop?',
    'TCKLARNA_BANNER_SRC'                               => 'Fonte del banner Klarna',
    'TCKLARNA_FOOTER'                                   => 'Piè di pagina',
    'TCKLARNA_DISPLAY_IN_FOOTER'                        => 'Cosa deve essere visualizzato nel piè di pagina?',
    'TCKLARNA_FOOTER_PAYMENT_METHODS'                   => 'Visualizzazione dei metodi di pagamento',
    'TCKLARNA_FOOTER_KLARNA_LOGO'                       => 'Logo Klarna',
    'TCKLARNA_DESIGN'                                   => 'Design',
    'TCKLARNA_LONG_VERSION'                             => 'Versione lunga:',
    'TCKLARNA_SHORT_VERSION'                            => 'Versione breve:',
    'TCKLARNA_WHITE'                                    => 'Bianco:',
    'TCKLARNA_BLACK'                                    => 'Nero:',
    'TCKLARNA_DETAILS_AND_BASKET'                       => 'Pagina dei dettagli dell\'articolo e carrello',
    'TCKLARNA_DISPLAY_PAYMENT_WIDGET'                   => 'Visualizzare il widget del metodo di pagamento Klarna?',
    'TCKLARNA_ON_PROD_PAGE'                             => 'Nella pagina dei dettagli dell\'articolo',
    'TCKLARNA_KEB_CLID'                                 => 'Klarna Express Checkout - Identificativo cliente',
    'TCKLARNA_KEB_SHIPPINGMETHOD'                       => 'Spedizione con Klarna Express Checkout',
    'TCKLARNA_KEB_THEME'                                => 'Tema del pulsante "Klarna Express Checkout"',
    'TCKLARNA_KEB_THEME_default'                        => 'Standard (scuro)',
    'TCKLARNA_KEB_THEME_light'                          => 'Sfortuna',
    'TCKLARNA_KEB_THEME_outlined'                       => 'In sintesi',
    'TCKLARNA_KEB_SHAPE'                                => 'Modulo del pulsante "Klarna Express Checkout"',
    'TCKLARNA_KEB_SHAPE_default'                        => 'Standard',
    'TCKLARNA_KEB_SHAPE_rect'                           => 'Rettangolare',
    'TCKLARNA_KEB_SHAPE_pill'                           => 'Pillola',
    'TCKLARNA_ON_BASKET_PAGE'                           => 'Nella pagina del carrello',
    'TCKLARNA_DISPLAY_EXPRESS_BUTTON'                   => 'Visualizzare il pulsante "Klarna Express Checkout"?',
    'TCKLARNA_PAYMENT_DESIGN'                           => 'Opzioni di design per i pagamenti Klarna',
    'TCKLARNA_CHECKOUT_DESIGN'                          => 'Opzioni di design di Klarna Checkout',
    'TCKLARNA_COLOR_SETTINGS'                           => 'Impostazioni colore:',
    'TCKLARNA_BORDER'                                   => 'Confine:',
    'TCKLARNA_BORDER_SELECTED'                          => 'Confine selezionato:',
    'TCKLARNA_BUTTON'                                   => 'Pulsante:',
    'TCKLARNA_BUTTON_TEXT'                              => 'Testo del pulsante:',
    'TCKLARNA_CHECKBOX'                                 => 'Casella di selezione:',
    'TCKLARNA_CHECKBOX_CHECKMARK'                       => 'Casella di selezione spuntata:',
    'TCKLARNA_DETAILS'                                  => 'Dettagli:',
    'TCKLARNA_HEADER'                                   => 'Intestazione:',
    'TCKLARNA_LINK'                                     => 'Link:',
    'TCKLARNA_TEXT'                                     => 'Testo:',
    'TCKLARNA_SECONDARY_TEXT'                           => 'Testo aggiuntivo:',
    'TCKLARNA_RADIUS_SETTINGS'                          => 'Regolazione del raggio:',
    'TCKLARNA_BORDER_RADIUS'                            => 'Raggio del bordo:',


    'TCKLARNA_ALLOW_SEPARATE_SHIPPING_ADDRESS'          => 'L\'indirizzo di consegna può essere diverso dall\'indirizzo di fatturazione',
    'TCKLARNA_PHONE_NUMBER_MANDATORY'                   => 'Il numero di telefono è un campo obbligatorio',
    'TCKLARNA_DATE_OF_BIRTH_MANDATORY'                  => 'La data di nascita è un campo obbligatorio',
    'TCKLARNA_ENABLE_AUTOFOCUS'                         => 'Attivare l\'autofocus per l\'iframe di Klarna Checkout ',
    'TCKLARNA_ADD_A_CUSTOM_CHECKBOX'                    => 'Aggiungere una casella di selezione personalizzata nell\'iframe di Klarna Checkout',
    'TCKLARNA_ENABLE_DHL_PACKSTATION'                   => 'Attivare la consegna presso un punto di ritiro DHL',
    'TCKLARNA_ENABLE_PRE_FILLING'                       => 'Attiva il pre-riempimento',
    'TCKLARNA_ENABLE_PREFILL_NOTIFICATION'              => 'Attiva l\'avviso di precompilazione',
    'TCKLARNA_SALUTATION_MANDATORY'                     => 'Il campo "Titolo" è obbligatorio',
    'TCKLARNA_SET_TAC_URI'                              => 'URL delle vostre condizioni generali di contratto - Campo obbligatorio per KCO e Klarna Express',
    'TCKLARNA_SET_CANCEL_URI'                           => 'URL relativo al diritto di recesso - Campo obbligatorio per KCO e Klarna Express',
    'TCKLARNA_SHIPPING_DETAILS'                         => 'URL dei dettagli di spedizione - Campo obbligatorio per KCO e Klarna Express',
    'TCKLARNA_NO_VALIDATION_NEEDED'                     => 'Nessuna convalida',
    'TCKLARNA_VALIDATION_IGNORE_TIMEOUTS_NEEDED'        => 'Eseguire la convalida, ma ignorare i timeout',
    'TCKLARNA_SUCCESSFUL_VALIDATION_NEEDED'             => 'È necessaria una validazione riuscita',
    'TCKLARNA_ORDER_VALIDATION'                         => 'Conferma dell\'ordine',

    'TCKLARNA_CHOOSE_KP_OPTIONS'                        => 'Selezionate le opzioni di pagamento Klarna che desiderate offrire ai vostri clienti:',
    'TCKLARNA_PAY_LATER'                                => 'Fattura',
    'TCKLARNA_PAY_LATER.'                               => 'Fattura.',
    'TCKLARNA_PAY_LATER_START'                          => 'Per i clienti che desiderano acquistare ora e pagare in un secondo momento. In tutta comodità entro 30 giorni, a seconda del mercato.',
    'TCKLARNA_PAY_LATER_TEXT'                           => 'L\'opzione “Fattura” rende la procedura di pagamento semplice e veloce per i clienti, senza che questi debbano inserire dati personali o codici complicati. Il cliente può scegliere tra la fattura e il pagamento nel mese X.',
    'TCKLARNA_SLICE_IT'                                 => 'Acquisto a rate.',
    'TCKLARNA_SLICE_IT.'                                => 'Pagare a rate.',
    'TCKLARNA_SLICE_IT_START'                           => 'Aumentate il potere d\'acquisto dei vostri clienti grazie al pagamento a rate. I clienti possono saldare i propri acquisti con rate mensili fisse in un periodo compreso tra 6 e 36 mesi.',
    'TCKLARNA_SLICE_IT_TEXT'                            => 'Grazie all’“acquisto rateale”, i clienti possono suddividere l’importo dell’acquisto in rate a tassi di interesse contenuti. Ciò aumenta il margine di investimento e il potere d’acquisto. L’esclusiva procedura di concessione del credito di Klarna richiede solo pochi istanti e l’inserimento di un numero minimo di dati.',
    'TCKLARNA_PAY_NOW'                                  => 'Paga subito',
    'TCKLARNA_PAY_NOW.'                                 => 'Paga subito.',
    'TCKLARNA_PAY_NOW_START'                            => 'Pagamenti diretti semplici e veloci con la funzione “Paga subito” di Klarna. In Germania, il portafoglio di opzioni di pagamento non dovrebbe tralasciare il bonifico immediato, la carta di credito e l’addebito diretto.',
    'TCKLARNA_PAY_NOW_TEXT'                             => 'I clienti che desiderano pagare l\'intero importo immediatamente al momento del completamento dell\'ordine possono utilizzare l\'opzione "Paga subito". È possibile scegliere tra carta di credito, addebito diretto e bonifico immediato.',
    'TCKLARNA_CHECKOUT'                                 => 'Il Klarna Checkout.',
    'TCKLARNA_CHECKOUT_START'                           => 'La migliore esperienza di checkout per i tuoi clienti. Identificazione affidabile dei clienti e scelta delle opzioni di spedizione. Tutti i pagamenti inclusi. Disponibilità a livello mondiale, ottimizzata a livello locale. Ci assumiamo noi tutto il rischio e tu ricevi sempre il tuo denaro.',

    'TCKLARNA_RB_HOW_TO_ACTIVATE'                       => 'How-to-activate<br>Klarna guide.',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_ONE'              => 'Nel backend di OXID, clicchi sulla nuova voce di menu "Klarna", poi sulla sottocategoria "Generale" e infine selezioni il prodotto Klarna desiderato. Può scegliere tra "Klarna Payments" e "Klarna Checkout".',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_TWO'              => 'Inserisci le tue credenziali di accesso (nome utente e password) e, nella sezione Impostazioni negozio &gt; Metodi di pagamento e &gt; Metodi di spedizione, configura le associazioni tipiche di OXID per i metodi di pagamento.',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_THREE'            => 'Salvare le modifiche.',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_FOUR'             => 'Ora sei online e puoi iniziare a vendere con Klarna.',
    'TCKLARNA_RB_MERCHANT_SUPPORT'                      => 'Assistenza ai commercianti',
    'TCKLARNA_DEVICE_IMG'                               => 'device.png',


    'TCKLARNA_EXTERNAL_PAYMENTS_ADMIN_DESC'             => 'Qui è possibile configurare metodi di pagamento esterni e procedure di checkout esterne da integrare all\'interno dell\'iframe di Klarna Checkout. ',
    'TP11'                                              => 'Per una descrizione dettagliata delle diverse impostazioni, si prega di consultare i suggerimenti al passaggio del mouse ',
    'TP12'                                              => '<i class="fa fa-question-circle-o" aria-hidden="true"></i>, legga il <a class="cl-pink" href="https://wiki.fatchip.de/public/faqklarna" target="_blank">manuale</a> ',
    'TP13'                                              => 'oppure contatta l\'assistenza per l\'integrazione di Klarna.',
    'TCKLARNA_EXTRA_MERCHANT_DATA_ADMIN_DESC'           => 'Qui è possibile configurare se, se del caso, i dati aggiuntivi del commerciante debbano essere trasmessi a Klarna. ',
    'TP21'                                              => 'Per una descrizione dettagliata delle diverse impostazioni, si prega di consultare i suggerimenti al passaggio del mouse ',
    'TP22'                                              => '<i class="fa fa-question-circle-o" aria-hidden="true"></i>, legga il <a class="cl-pink" href="https://wiki.fatchip.de/public/faqklarna" target="_blank">manuale</a> ',
    'TP23'                                              => 'oppure contatta l\'assistenza per l\'integrazione di Klarna.',
    'TCKLARNA_DESIGN_SETTINGS_ADMIN_DESC'               => 'Qui è possibile configurare le impostazioni di design da utilizzare con il modulo Klarna per l\'eShop OXID. ',
    'TP31'                                              => 'Per una descrizione dettagliata delle diverse impostazioni, si prega di consultare i suggerimenti ',
    'TP32'                                              => '<i class="fa fa-question-circle-o" aria-hidden="true"></i>, legga il <a class="cl-pink" href="https://wiki.fatchip.de/public/faqklarna" target="_blank">manuale</a> ',
    'TP33'                                              => 'oppure contatta l\'assistenza per l\'integrazione di Klarna.',
    'TCKLARNA_GENERAL_SETTINGS_ADMIN_DESC'              => 'Qui è possibile scegliere tra Klarna Checkout e Klarna Payments e configurare le impostazioni generali. ',
    'TP41'                                              => 'Per una descrizione dettagliata delle diverse impostazioni, si prega di consultare i suggerimenti ',
    'TP42'                                              => '<i class="fa fa-question-circle-o" aria-hidden="true"></i>, legga il <a class="cl-pink" href="https://wiki.fatchip.de/public/faqklarna" target="_blank">manuale</a> ',
    'TP43'                                              => 'oppure contatta l\'assistenza per l\'integrazione di Klarna.',
    'TCKLARNA_CONFIGURATION_KCO_ADMIN_DESC'             => 'In questa pagina è possibile configurare le impostazioni specifiche di Klarna Checkout. ',
    'TP51'                                              => 'Per una descrizione dettagliata delle diverse impostazioni, si prega di consultare i suggerimenti al passaggio del mouse ',
    'TP52'                                              => '<i class="fa fa-question-circle-o" aria-hidden="true"></i>, legga il <a class="cl-pink" href="https://wiki.fatchip.de/public/faqklarna" target="_blank">manuale</a> ',
    'TP53'                                              => 'oppure contatta l\'assistenza per l\'integrazione di Klarna.',
    'TCKLARNA_CONFIGURATION_KP_ADMIN_DESC'              => 'In questa pagina puoi scegliere quali metodi di pagamento Klarna desideri offrire. ',
    'TP61'                                              => 'Per una descrizione dettagliata delle diverse impostazioni, si prega di consultare i suggerimenti al passaggio del mouse ',
    'TP62'                                              => '<i class="fa fa-question-circle-o" aria-hidden="true"></i>, legga il <a class="cl-pink" href="https://wiki.fatchip.de/public/faqklarna" target="_blank">manuale</a> ',
    'TP63'                                              => 'oppure contatta l\'assistenza per l\'integrazione di Klarna.',

    'TCKLARNA_PAYMENT_METHOD'                           => 'Modalità di pagamento',
    'TCKLARNA_EXTERNAL_PAYMENT_METHOD'                  => 'Metodo di pagamento esterno',
    'TCKLARNA_EXTERNAL_CHECKOUT'                        => 'Checkout esterno',
    'TCKLARNA_IMAGE_URI_EXT_PAYMENT'                    => 'URI dell\'immagine per il metodo di pagamento esterno',
    'TCKLARNA_IMAGE_URI_EXT_CHECKOUT'                   => 'URI dell\'immagine per il checkout esterno',
    'TCKLARNA_IMAGE_TIP_69x24'                          => 'Dimensioni dell\'immagine: 69x24 pixel',
    'TCKLARNA_IMAGE_TIP_276x48'                         => 'Dimensioni dell\'immagine: 276x48 pixel',
    'TCKLARNA_USER_GUIDE_DESCRIPTION'                   => 'È possibile consultare qui il manuale d\'uso del modulo Klarna per OXID eShop.',
    'TCKLARNA_USER_GUIDE_LINK'                          => 'https://wiki.fatchip.de/public/faqklarna',
    'TCKLARNA_USER_GUIDE_BUTTON'                        => 'Manuale d\'uso',

    'TCKLARNA_CHOOSE'                                   => 'Selezionare',

    'TCKLARNA_CUSTOMER_ACCOUNT_INFO'                    => 'Informazioni sull\'account cliente',
    'TCKLARNA_PAYMENT_HISTORY_FULL'                     => 'Cronologia completa dei pagamenti',
    'TCKLARNA_PASSTHROUGH_FIELD'                        => 'Campo di passaggio',

    'TCKLARNA_ASSIGN_PAYMENT_METHOD_TYPE'               => 'Assegnare il tipo di pagamento:',
    'TCKLARNA_WHICH_ORDERS_IN_FULL_PAYMENT_HISTORY'     => 'Quali ordini devono essere inclusi nella cronologia dei pagamenti completa?',
    'TCKLARNA_EMD_ORDER_HISTORY_ALL'                    => 'Considerare tutti gli ordini come pagati, indipendentemente dalla data di oxpaid',
    'TCKLARNA_EMD_ORDER_HISTORY_PAID'                   => 'Inviare solo gli ordini con data oxpaid impostata; ignorare gli ordini non pagati',
    'TCKLARNA_EMD_ORDER_HISTORY_NONE'                   => 'Ignora tutti gli ordini effettuati con questa modalità di pagamento',
    'TCKLARNA_OTHER_PAYMENT'                            => 'Altra opzione di pagamento',
    'TCKLARNA_DIRECT_BANKING'                           => 'Bonifico immediato',
    'TCKLARNA_CARD'                                     => 'Mappa',

    'TCKLARNA_TEST_MODE_TOOLTIP'                        => 'Scegliere tra Playground (ambiente di test) e Live (ambiente di produzione). Attivare l\'ambiente di produzione solo dopo aver eseguito con successo i test di integrazione e previa consultazione con il proprio Klarna Integration Manager.',
    'TCKLARNA_GLOBAL_MERCHANT_ID_TOOLTIP'               => 'Inserisci qui le tue credenziali di accesso all\'API di Klarna. Le hai ricevute nell\'e-mail di benvenuto inviata da Klarna. Questo nome utente e questa password sono validi a livello globale per tutti i paesi. Solo nel caso in cui tu abbia ricevuto credenziali di accesso diverse per paesi diversi, puoi aggiungerle più in basso.',
    'TCKLARNA_GLOBAL_PASSWORD_TOOLTIP'                  => 'Inserisci qui la password corrispondente al nome utente API che stai utilizzando. Hai ricevuto questa password nell\'e-mail di benvenuto inviata da Klarna.',
    'TCKLARNA_GLOBAL_PORTAL_MERCHANT_ID_TOOLTIP'        => 'Inserisci qui il tuo ID commerciante Klarna. Lo hai ricevuto nell\'e-mail di benvenuto inviata da Klarna.',
    'TCKLARNA_CREDENTIALS_COUNTRY_SELECTOR_TOOLTIP'     => 'Selezionare dalla lista a sinistra il Paese per il quale ha ricevuto le credenziali di accesso specifiche di Klarna.',
    'TCKLARNA_CREDENTIALS_COUNTRY_MERCHANT_ID_TOOLTIP'  => 'Si prega di inserire qui il nome utente corrispondente a questo Paese.',
    'TCKLARNA_CREDENTIALS_COUNTRY_PASSWORD_TOOLTIP'     => 'Inserisca qui la password corrispondente a questo Paese.',
    'TCKLARNA_CREDENTIALS_COUNTRY_PORTAL_MERCHANT_ID_TOOLTIP'=> 'Si prega di inserire qui l\'ID commerciante corrispondente a questo Paese.',
    'TCKLARNA_DEFAULT_COUNTRY_TOOLTIP'                  => 'Selezionare dall\'elenco il Paese per il quale si desidera che Klarna Checkout venga caricato per impostazione predefinita, fintanto che il cliente non abbia ancora specificato il proprio Paese.',
    'TCKLARNA_ENABLE_LOGGING_TOOLTIP'                   => 'Attiva la funzione di log in modo che tutte le comunicazioni API con Klarna vengano registrate nella tabella MySQL tcklarna_logs. Ciò può risultare utile per l\'analisi o la ricerca degli errori. In ambiente di produzione, la funzione dovrebbe essere disattivata, poiché altrimenti potrebbero accumularsi grandi quantità di log e venire memorizzati dati sensibili.',
    'TCKLARNA_SEND_PRODUCT_URLS_TOOLTIP'                => 'Inviate a Klarna gli URL delle pagine di dettaglio dei prodotti presenti nel carrello dei vostri clienti, in modo che Klarna possa successivamente inserire i link ai vostri articoli dal portale Klarna.',
    'TCKLARNA_SEND_PRODUCT_IMAGES_TOOLTIP'              => 'Inviate a Klarna gli URL delle immagini degli articoli presenti nel carrello dei vostri clienti, in modo che Klarna possa visualizzarle sul portale Klarna.',
    'TCKLARNA_ENABLE_ANONYMIZATION_TOOLTIP'             => 'Attiva l\'anonimizzazione per nascondere a Klarna i nomi degli articoli presenti nel carrello dei tuoi clienti. Questa operazione è consigliata, ad esempio, per le farmacie online, ma dovrebbe essere effettuata solo previa consultazione con il responsabile dell\'integrazione di Klarna.',
    'TCKLARNA_ALLOW_SEPARATE_DELIVERY_ADDRESS_TOOLTIP'  => 'Se si desidera consentire la consegna a un indirizzo di consegna diverso, attivare questo pulsante.',
    'TCKLARNA_MANDATORY_PHONE_TOOLTIP'                  => 'Se desiderate rendere obbligatorio l\'inserimento di un numero di telefono, attivate questo pulsante. Normalmente, per Klarna il numero di telefono non è un campo obbligatorio.',
    'TCKLARNA_MANDATORY_BIRTH_DATE_TOOLTIP'             => 'Se desiderate rendere obbligatoria l\'indicazione della data di nascita, attivate questo pulsante. Normalmente, per Klarna la data di nascita non è un campo obbligatorio. Tuttavia, tale informazione è necessaria per consentire l\'acquisto con pagamento tramite fattura o a rate.',
    'TCKLARNA_ENABLE_AUTOFOCUS_TOOLTIP'                 => 'Utilizzando questo pulsante, è possibile impostare che, al caricamento della pagina con Klarna Checkout, l\'iframe di Klarna venga automaticamente selezionato.',
    'TCKLARNA_CHECKBOX_TOOLTIP'                         => 'È possibile attivare una casella di selezione aggiuntiva all’interno dell’iframe di Klarna Checkout per offrire al cliente la possibilità di aprire un account cliente, iscriversi alla newsletter o entrambe le cose. Se, con la casella di selezione attivata, il cliente possiede già un account cliente o è già iscritto alla newsletter, il testo della casella verrà automaticamente modificato oppure, se necessario, la casella verrà completamente nascosta.',
    'TCKLARNA_VALIDATION_TOOLTIP'                       => 'Con questa opzione è possibile attivare un controllo aggiuntivo del carrello che, al momento dell\'invio dell\'ordine tramite Klarna Checkout, verifica nuovamente la disponibilità degli articoli desiderati, al fine di evitare errori dovuti a vendite in eccesso. Si consiglia di selezionare la modalità "Convalida riuscita richiesta".',
    'TCKLARNA_SALUTATION_MANDATORY_TOOLTIP'             => 'Questa impostazione riguarda esclusivamente il modulo di checkout di Klarna per il Regno Unito: è necessario rendere obbligatorio l\'inserimento del titolo?',
    'TCKLARNA_ENABLE_DHL_PACKSTATIONS_TOOLTIP'          => 'Al momento non implementato',
    'TCKLARNA_ENABLE_PRE_FILLING_TOOLTIP'               => 'Attivare la compilazione automatica dell\'iframe di Klarna Checkout con i dati del cliente che ha effettuato l\'accesso all\'eShop OXID',
    'TCKLARNA_ENABLE_PREFILL_NOTIFICATION_TOOLTIP'      => 'Se la funzione di compilazione automatica dell\'iframe di Klarna Checkout è attiva, per alcuni paesi è necessario visualizzare un\'apposita informativa sulla privacy. Questa informativa viene attivata tramite questo pulsante.',
    'TCKLARNA_TERMS_AND_CONDITIONS_URL_TOOLTIP'         => 'Inserisci qui l\'URL delle tue Condizioni generali di contratto. Queste saranno collegate tramite link nell\'iframe di Klarna Checkout. È necessario specificare un URL valido che inizi con https://.',
    'TCKLARNA_CANCELLATION_RIGHTS_URL_TOOLTIP'          => 'Inserisci qui l\'URL della tua pagina web contenente l\'informativa sul diritto di recesso. L\'URL deve iniziare con https://.',
    'TCKLARNA_SHIPPING_DETAILS_TOOLTIP'                 => 'Queste informazioni sulla spedizione vengono mostrate al cliente nella pagina di conferma al termine dell\'ordine.',
    'TCKLARNA_EXTERNAL_PAYMENT_NAME_SELECT_TOOLTIP'     => 'Assegnare questo metodo di pagamento esterno a uno dei metodi di pagamento predefiniti',
    'TCKLARNA_ENABLE_EXTERNAL_PAYMENT_TOOLTIP'          => 'Con questo pulsante è possibile attivare questa modalità di pagamento come metodo di pagamento esterno per il Klarna Checkout. Una volta attivata, il cliente potrà selezionare questa modalità di pagamento dall\'elenco delle opzioni di pagamento nell\'iframe del Klarna Checkout.',
    'TCKLARNA_ENABLE_EXTERNAL_CHECKOUT_TOOLTIP'         => 'Con questo pulsante è possibile attivare questo metodo di pagamento come checkout esterno. Se attivato, questo metodo di pagamento verrà visualizzato nella parte inferiore dell\'iframe del checkout Klarna, prima ancora dell\'inserimento dei dati del cliente.',
    'TCKLARNA_EXTERNAL_PAYMENT_IMAGE_URL_TOOLTIP'       => 'Inserisci qui l\'URL di un\'immagine che deve essere visualizzata accanto alla modalità di pagamento nell\'iframe di Klarna Checkout. Si consiglia di utilizzare un\'immagine proveniente da un URL sicuro che inizi con https://.',
    'TCKLARNA_EXTERNAL_CHECKOUT_IMAGE_URL_TOOLTIP'      => 'Inserisci qui l\'URL di un\'immagine che dovrà essere visualizzata come pulsante per questo metodo di pagamento nell\'iframe di Klarna Checkout in basso. Si consiglia di utilizzare un\'immagine proveniente da un URL sicuro che inizi con https://.',
    'TCKLARNA_EXTERNAL_IMAGE_URL_EMPTY'                 => 'Si prega di indicare un URL per tutte le lingue',
    'TCKLARNA_EXTERNAL_IMAGE_URL_INVALID'               => 'Si prega di inserire un URL valido che inizi con https://',
    'TCKLARNA_EMD_CUSTOMER_INFO_TOOLTIP'                => 'Questo pulsante attiva la trasmissione di dati aggiuntivi a Klarna; in questo caso si tratta delle informazioni relative all\'account del cliente, che includono la data di registrazione dell\'account e quella dell\'ultima modifica.',
    'TCKLARNA_EMD_PAYMENT_HISTORY_FULL_TOOLTIP'         => 'Questo pulsante attiva l\'invio di dati aggiuntivi a Klarna, in questo caso la "Payment History Full", che contiene gli acquisti effettuati finora dal cliente.',
    'TCKLARNA_EMD_PAYMENT_TYPE_TOOLTIP'                 => 'Si prega di indicare a quale tipo di pagamento corrisponde questo metodo di pagamento.',
    'TCKLARNA_EMD_HISTORY_FULL_TOOLTIP'                 => 'Si prega di specificare qui se e, eventualmente, quali ordini effettuati con questa modalità di pagamento debbano essere inclusi nel trasferimento della cronologia degli ordini del cliente. La dipendenza del campo OXORDER.OXPAID indica se debbano essere considerati solo gli ordini pagati o tutti gli ordini.',
    'TCKLARNA_EMD_PASSTHROUGH_FIELD_TOOLTIP'            => 'È possibile trasmettere a Klarna ulteriori dati a propria scelta tramite un campo "pass-through". Per utilizzare questa funzione, è necessario installare nell\'OXID eShop un modulo apposito che inserisca i dati desiderati nel campo "pass-through". Le istruzioni relative sono disponibili nella documentazione per gli sviluppatori.',
    'TCKLARNA_DISPLAY_ON_HOME_TOOLTIP'                  => 'Con questo pulsante è possibile attivare un banner Klarna sulla pagina iniziale del proprio negozio nei temi predefiniti Flow e Wave.',
    'TCKLARNA_BANNER_SRC_TOOLTIP'                       => 'Qui è possibile inserire il tag script per l\'integrazione del banner. Nel portale dei banner di Klarna potrete trovare, se necessario, altri banner tra cui scegliere.',
    'TCKLARNA_FOOTER_PAYMENT_METHODS_TOOLTIP'           => 'Con questo pulsante è possibile attivare la visualizzazione del metodo di pagamento Klarna nel piè di pagina del proprio negozio nei temi predefiniti Flow e Wave.',
    'TCKLARNA_FOOTER_KLARNA_LOGO_TOOLTIP'               => 'Con questo pulsante è possibile inserire il logo Klarna nel piè di pagina del proprio negozio nei temi predefiniti Flow e Wave.',
    'TCKLARNA_BUY_NOW_ON_BASKET_TOOLTIP'                => 'Questo plugin inserisce un pulsante "Klarna Express Checkout" nella pagina del carrello del tuo negozio, nei temi predefiniti.',
    'TCKLARNA_BUY_NOW_ON_PROD_PAGE_TOOLTIP'             => 'Questo pulsante aggiunge un pulsante "Klarna Express Checkout" alle pagine di dettaglio degli articoli del tuo negozio nei temi predefiniti.',
    'TCKLARNA_KEB_CLID_TOOLTIP'                         => 'Per poter utilizzare Klarna Express Checkout, è necessario attivarlo nel portale Klarna, nella scheda "Conversion boosters". Una volta completata la configurazione, è possibile copiare l\'identificativo cliente in questo campo.',
    'TCKLARNA_BORDER_TOOLTIP'                           => 'Colore della cornice che appare nel frontend del negozio dopo aver selezionato il metodo di pagamento Klarna, nel caso in cui siano disponibili diverse sotto-opzioni.',
    'TCKLARNA_BORDER_SELECTED_TOOLTIP'                  => 'Colore della cornice che appare nel frontend del negozio dopo aver selezionato il metodo di pagamento Klarna, nel caso in cui siano disponibili diverse sotto-opzioni. Questo valore di colore viene utilizzato per evidenziare la sotto-opzione attualmente selezionata.',
    'TCKLARNA_BUTTON_TOOLTIP'                           => 'Al momento della pubblicazione di questo modulo, questa impostazione non ha ancora alcun effetto.',
    'TCKLARNA_BUTTON_TEXT_TOOLTIP'                      => 'Al momento della pubblicazione di questo modulo, questa impostazione non ha ancora alcun effetto.',
    'TCKLARNA_DESIGN_CHECKBOX_TOOLTIP'                  => 'Colore di sfondo dei pulsanti di opzione che compaiono nel frontend del negozio dopo aver selezionato il metodo di pagamento Klarna, nel caso in cui siano disponibili diverse opzioni secondarie',
    'TCKLARNA_DESIGN_CHECKBOX_CHECKMARK_TOOLTIP'        => 'Al momento della pubblicazione di questo modulo, questa impostazione non ha ancora alcun effetto.',
    'TCKLARNA_DETAILS_TOOLTIP'                          => 'Colore dei simboli di elenco nella visualizzazione dei dettagli di pagamento nella pagina di selezione dei metodi di pagamento.',
    'TCKLARNA_HEADER_TOOLTIP'                           => 'Al momento della pubblicazione di questo modulo, questa impostazione non ha ancora alcun effetto.',
    'TCKLARNA_LINK_TOOLTIP'                             => 'Colore dei link nella descrizione dettagliata delle modalità di pagamento nella pagina di selezione delle modalità di pagamento.',
    'TCKLARNA_TEXT_TOOLTIP'                             => 'Colore del testo della descrizione dettagliata delle modalità di pagamento nella pagina di selezione delle modalità di pagamento.',
    'TCKLARNA_SECONDARY_TEXT_TOOLTIP'                   => 'Colore alternativo del testo della descrizione dettagliata delle modalità di pagamento nella pagina di selezione delle modalità di pagamento.',
    'TCKLARNA_BORDER_RADIUS_TOOLTIP'                    => 'Con questa impostazione è possibile definire il grado di arrotondamento della cornice che appare nel frontend del negozio dopo aver selezionato il metodo di pagamento Klarna, a seconda delle diverse sotto-opzioni disponibili.',

    'KLARNA_ONLY_FOR_KLARNA_PAYMENT'                    => 'Questa scheda riguarda solo gli ordini effettuati tramite Klarna',
    'KLARNA_CAPTURE_FULL_ORDER'                         => 'Acquisizione dell\'ordine completo',
    'KLARNA_CAPTURE_ID'                                 => 'ID addebito',
    'KLARNA_CAPTURE_REFERENCE'                          => 'Riferimento Klarna',
    'KLARNA_CAPTURE_AMOUNT'                             => 'Importo dell\'addebito',
    'KLARNA_CAPTURE_DATE'                               => 'Addebitato il',
    'KLARNA_REFUND_AMOUNT'                              => 'Importo del rimborso',
    'KLARNA_REFUND_DESCRIPTION'                         => 'Rimborso - Spiegazione',
    'KLARNA_REFUND_DATE'                                => 'Sostituito da',
    'KLARNA_CAPTURES'                                   => 'Addebiti',
    'KLARNA_REFUNDS'                                    => 'Rimborsi',
    'KLARNA_CANCEL_ORDER'                               => 'Annulla l\'ordine',
    'KLARNA_ORDER_IS_CANCELLED'                         => 'L\'ordine è stato annullato. ',
    'KLARNA_SEE_ORDER_IN_PORTAL'                        => '<a href="%s" target="_blank" class="alert-link">Diese Bestellung im Klarna Portal aufrufen</a>',
    'KLARNA_ORDER_NOT_IN_SYNC'                          => '<strong>Attenzione!</strong> I dati di questo ordine non corrispondono a quelli registrati presso Klarna. ',
    'TCKLARNA_ORDER_UPDATE_CANT_BE_SENT_TO_KLARNA'      => 'Attenzione! A causa dello stato attuale dell\'ordine, questa modifica non può essere trasmessa a Klarna. Se necessario, effettua manualmente la modifica corrispondente direttamente nel Klarna Merchant Portal.',
    'TCKLARNA_ORDER_UPDATE_REJECTED_BY_KLARNA'          => 'Attenzione! Klarna non è riuscita a elaborare le ultime modifiche apportate a questo ordine (motivo: %s). Si prega di annullare le modifiche recenti nell\'eShop OXID oppure, se necessario, di apportare manualmente le modifiche del caso nel Klarna Merchant Portal.',
    'KLARNA_UNAUTHORIZED_REQUEST'                       => 'Richiesta non autorizzata. Verificare le impostazioni del modulo Klarna, l\'ID commerciante e la relativa password',
    'KLARNA_ORDER_NOT_FOUND'                            => 'Questo ordine non è stato trovato nel sistema di Klarna. Pertanto, le modifiche apportate ai dati dell\'ordine non verranno trasmesse a Klarna.',
    'KLARNA_MID_CHANGED_FOR_COUNTRY'                    => '<strong>Dati di accesso errati!</strong> Questo ordine è stato effettuato utilizzando l\'ID rivenditore <strong>%s</strong>. L\'ID rivenditore attualmente configurato per <strong>%s</strong> è <strong>%s</strong>.',
    'TCKLARNA_PRODUCT_NAME'                             => 'Nome del prodotto',
    'TCKLARNA_ANONYMIZED_PRODUCT'                       => 'Titolo del prodotto in forma anonima:',
    'TCKLARNA_KCO_INVOICE_MSG'                          => 'Il pagamento viene gestito dal nostro partner Klarna. Se non avete ancora pagato l\'acquisto, vi preghiamo di fare riferimento alle informazioni di pagamento inviate da Klarna. Potete gestire tutti i vostri acquisti su Klarna.com o tramite l\'app Klarna e persino effettuare il pagamento con un solo clic.',
    'TCKLARNA_KP_INVOICE_MSG'                           => 'Il pagamento viene gestito dal nostro partner Klarna. Si prega di prendere visione delle informazioni di pagamento inviate da Klarna. È possibile gestire tutti i propri acquisti su Klarna.com o tramite l\'app Klarna e persino effettuare il pagamento con un solo clic.',
    'TCKLARNA_VOUCHER_DISCOUNT'                         => 'Buono sconto',

    'TCKLARNA_KCO_BUTTON_TOOLTIP'                       => 'Colore di sfondo del pulsante di pagamento all\'interno dell\'iframe di Klarna Checkout.',
    'TCKLARNA_KCO_BUTTON_TEXT_TOOLTIP'                  => 'Colore del testo del pulsante di pagamento nell\'iframe di Klarna Checkout.',
    'TCKLARNA_KCO_DESIGN_CHECKBOX_TOOLTIP'              => 'Colore di sfondo delle caselle di selezione all\'interno dell\'iframe di Klarna Checkout.',
    'TCKLARNA_KCO_DESIGN_CHECKBOX_CHECKMARK_TOOLTIP'    => 'Colore del segno di spunta all\'interno delle caselle di selezione nell\'iframe di Klarna Checkout.',
    'TCKLARNA_KCO_HEADER_TOOLTIP'                       => 'Colore dei titoli all’interno dell’iframe di Klarna Checkout.',
    'TCKLARNA_KCO_LINK_TOOLTIP'                         => 'Colore dei link all\'interno dell\'iframe di Klarna Checkout.',
    'TCKLARNA_KCO_BORDER_RADIUS_TOOLTIP'                => 'Con questa impostazione è possibile definire il grado di arrotondamento del bordo dell\'iframe di Klarna Checkout.',

    'TCKLARNA_GIFT_WRAPPING_TITLE'                      => 'Confezione regalo',
    'TCKLARNA_GIFT_CARD_TITLE'                          => 'Biglietto di auguri',

    'TCKLARNA_ERROR_SHOP_SSL_NOT_CONFIGURED'            => 'Errore fatale: è obbligatorio specificare un URL $this->sSSLShopURL valido e protetto da SSL (https) nel file config.inc.php del vostro negozio online se desiderate attivare l\'%s!',
    'TCKLARNA_ERROR_WRONG_CREDS'                        => '<strong>Dati di accesso errati!</strong>',
    'TCKLARNA_ERROR_KCO_INACTIVE'                       => 'Errore di configurazione: Klarna Checkout non è attivo nel negozio',

    'KLARNA_CAPTURE_SUCCESSFULL'                        => 'L\'importo è stato addebitato con successo.',
    'TCKLARNA_CAPUTRE_FAIL_ORDER_CANCELLED'             => ' Non è stato possibile addebitare l\'ordine, poiché era già stato annullato.',
    'TCKLARNA_ANONYMIZED_PRODUCT_TOOLTIP'               => 'Inserisci qui la stringa di testo che deve essere inviata a Klarna al posto del titolo effettivo del prodotto.',
    'TCKLARNA_NO_REQUESTS_WILL_BE_SENT'                 => 'Le modifiche apportate a questo ordine non verranno trasmesse a Klarna.',
    'TCKLARNA_USER_GUIDE'                               => 'Manuale d\'uso',
    'TCKLARNA_REGISTER_NOW_BUTTON'                      => 'Registrati',
    'TCKLARNA_LEARN_MORE_BUTTON'                        => 'Per saperne di più',

    'TCKLARNA_CUSTOMER_TYPE'                            => 'Tipi di clienti supportati',
    'TCKLARNA_CUSTOMER_TYPE_TOOLTIP'                    => 'Hier können Sie einstellen, ob der Shop ausschließlich B2C Transaktionen (Standard-Einstellung). nur B2B Transaktionen oder sowohl B2C als auch B2B Transaktionen akzeptieren soll. <br> Hinweis: Nach dem Umstellen der Kundenarten muss der Session cache des Browsers gelöscht werden, damit die Bezahlung getestet werden kann.',
    'TCKLARNA_B2C'                                      => 'Solo clienti B2C',
    'TCKLARNA_B2B'                                      => 'Solo clienti B2B',
    'TCKLARNA_B2B_B2C'                                  => 'Principalmente clienti B2B, ma anche clienti B2C',
    'TCKLARNA_B2C_B2B'                                  => 'Principalmente clienti B2C, ma anche clienti B2B',
    'TCKLARNA_NEED_SUPPORT'                             => 'Avete bisogno di aiuto per l\'integrazione?',
    'TCKLARNA_REACH_SUPPORT'                            => 'Contatta l\'assistenza commercianti di Klarna',

    'TCKLARNA_EU_WARNING'                               => '<p>Per conformarsi al regolamento UE sul geoblocking, si raccomanda vivamente di attivare tutti i paesi europei e di associarli al metodo di pagamento Klarna Checkout.</p><p>Mancano i seguenti paesi: %s</p>',

    'TCKLARNA_ON_SITE_MESSAGING'                        => 'Messaggistica in loco',
    'TCKLARNA_ON_SITE_MESSAGING_ADMIN_DESC'             => 'Qui è possibile configurare la messaggistica on-site da utilizzare con il modulo Klarna per l\'OXID eShop.',
    'TCKLARNA_ON_SITE_MESSAGING_SCRIPT'                 => 'Copione',
    'TCKLARNA_CREDIT_PROMOTION_PRODUCT'                 => 'Pagina dei dettagli del prodotto "Credit Promotion"',
    'TCKLARNA_CREDIT_PROMOTION_BASKET'                  => 'Promozione crediti Carrello',
    'TCKLARNA_TOP_STRIP_PROMOTION'                      => 'Promozione "Top-strip"',
    'TCKLARNA_FOOTER_PROMOTION'                         => 'Promozione a piè di pagina',
    'TCKLARNA_BANNER_PROMOTION'                         => 'Promozione con banner',
    'TCKLARNA_ON_SITE_MESSAGING_SCRIPT_TOOLTIP'         => 'Si prega di inserire qui il frammento di codice della libreria JavaScript necessario per la funzione di messaggistica sul sito, che è possibile ottenere dal Portale commercianti di Klarna.',
    'TCKLARNA_CREDIT_PROMOTION_PRODUCT_TOOLTIP'         => 'Si prega di inserire qui il tag di posizionamento per promuovere il finanziamento e l\'acquisto rateale tramite Credit Promotions nella pagina dei dettagli del prodotto',
    'TCKLARNA_CREDIT_PROMOTION_BASKET_TOOLTIP'          => 'Si prega di inserire qui il tag di posizionamento per promuovere il finanziamento e l\'acquisto rateale tramite Credit Promotions nella pagina di riepilogo del carrello',
    'TCKLARNA_TOP_STRIP_PROMOTION_TOOLTIP'              => 'Si prega di inserire qui il tag di posizionamento per promuovere informazioni generiche e specifiche relative ai metodi di pagamento sulla pagina iniziale del negozio',
    'TCKLARNA_FOOTER_PROMOTION_TOOLTIP'                 => 'Inserisci qui il tag di posizionamento per visualizzare i metodi di pagamento Klarna disponibili nel piè di pagina del negozio',
    'TCKLARNA_BANNER_PROMOTION_TOOLTIP'                 => 'Inserisci qui il tag di posizionamento per inserire un banner sulla pagina iniziale del tuo negozio',
    'TCKLARNA_ON_SITE_MESSAGING_HEADER_TITLE'           => 'Che cos\'è l\'On-Site Messaging?',
    'TCKLARNA_ON_SITE_MESSAGING_HEADER_DESC'            => 'I clienti non sono sempre consapevoli delle diverse opzioni di credito e finanziamento a loro disposizione prima di arrivare alla cassa. Le opzioni di finanziamento disponibili in anticipo influenzano la decisione di acquisto.',

    'TCKLARNA_ON_SITE_MESSAGING_HEADER_DESC_TPK0'       => 'On-Site Messaging è semplice e facile da integrare e offre informazioni su misura, che spaziano dai banner generici alla promozione della tua partnership con Klarna e alla disponibilità del pagamento rateale, fino alle promozioni personalizzate sul credito nelle pagine dei prodotti o del carrello.',
    'TCKLARNA_ON_SITE_MESSAGING_HEADER_DESC_2'          => 'Weitere Informationen zu den ersten Schritten <a class="cl-pink" href="https://docs.klarna.com/conversion-boosters/on-site-messaging/before-you-start/" target="_blank" rel=”noopener”>finden Sie hier</a><br><br>',
    'TCKLARNA_ON_SITE_MESSAGING_HEADER_DESC_2_TPK1'     => 'Melden Sie sich im <a class="cl-pink" href="https://merchants.klarna.com/" target="_blank">Händlerportal</a> an, um Ihren persönlichen JavaScript- und Placement-Code zu generieren. On-Site-Messaging wird in Ihrem Shop aktiviert, sobald der JavaScript-Code gespeichert und mindestens ein Placement-Code eingegeben wurde.<br>',
    'TCKLARNA_ON_SITE_MESSAGING_HEADER_DESC_2_TPK2'     => 'È possibile disattivarlo in qualsiasi momento rimuovendo nuovamente i codici.',
    'TCKLARNA_ON_SITE_MESSAGING_MERCHANT_BUTTON'        => 'Portale per i rivenditori',

    'TCKLARNA_IS_ENABLED_HEADLINE'                      => 'Attiva Klarna Instant Shopping',
    'TCKLARNA_IS_ENABLED'                               => 'Attivo',
    'TCKLARNA_IS_BUTTON_REPLACE'                        => 'Sostituire il tasto',
    'TCKLARNA_IS_REPLACE'                               => 'Creare un nuovo pulsante "Key"',
    'TCKLARNA_IS_BUTTON_REPLACE_TOOLTIP'                => 'È possibile aggiornare il Button Key qualora i dati di configurazione o di identificazione da parte di Klarna richiedano una modifica. Di norma, una volta generato, il Button Key può essere utilizzato per tutto il tempo che si desidera.',
    'TCKLARNA_IS_ENABLED_TOOLTIP'                       => 'Attiva qui Klarna Instant Shopping. In questo modo verrà generato automaticamente un pulsante da utilizzare nel frontend del negozio.',
    'TCKLARNA_IS_BUTTON_APEARANCE_HEADLINE'             => 'Impostazioni di stile dei pulsanti',
    'TCKLARNA_IS_VARIATION_TOOLTIP'                     => 'Si prega di scegliere tra un pulsante con il marchio Klarna in versione completa e una variante "Light" più neutra.',
    'TCKLARNA_IS_TAGLINE_TOOLTIP'                       => 'Selezionare se il colore del testo dello slogan sotto il pulsante deve essere chiaro o scuro.',
    'TCKLARNA_IS_TYPE_TOOLTIP'                          => 'Selezionare la dicitura desiderata per il pulsante.',
    'TCKLARNA_IS_BUTTON_PREVIEW'                        => 'Anteprima del pulsante',
    'TCKLARNA_IS_BUTTON_PLACEMENT_DETAILS'              => 'Visualizza nella pagina dei dettagli dell\'articolo',
    'TCKLARNA_IS_BUTTON_PLACEMENT_DETAILS_TOOLTIP'      => 'Attiva questa funzione affinché il pulsante Klarna Instant Shopping venga visualizzato su tutte le pagine di dettaglio degli articoli del tuo negozio.',
    'TCKLARNA_IS_BUTTON_PLACEMENT_BASKET'               => 'Visualizza nella panoramica del carrello',
    'TCKLARNA_IS_BUTTON_PLACEMENT_BASKET_TOOLTIP'       => 'Attiva questa funzione affinché il pulsante Klarna Instant Shopping venga visualizzato nella pagina di riepilogo del carrello del tuo negozio.',
    'TCKLARNA_IS_BUTTON_SETTINGS_HEADLINE'              => 'Altre impostazioni di Instant Shopping',
    'TCKLARNA_IS_SETTING_ALLOW_SEPARATE_SHIPPING_ADDRESS'=> 'L\'indirizzo di consegna può essere diverso dall\'indirizzo di fatturazione',
    'TCKLARNA_IS_SETTING_ALLOW_SEPARATE_SHIPPING_ADDRESS_TOOLTIP'=> 'Se si desidera consentire la consegna a un indirizzo di consegna diverso, attivare questo pulsante.',
    'TCKLARNA_IS_SETTING_DATE_OF_BIRTH_MANDATORY'       => 'Data di nascita come campo obbligatorio',
    'TCKLARNA_IS_SETTING_DATE_OF_BIRTH_MANDATORY_TOOLTIP'=> 'Se desiderate rendere obbligatoria l\'indicazione della data di nascita, attivate questo pulsante. Normalmente, per Klarna la data di nascita non è un campo obbligatorio. Tuttavia, tale informazione è necessaria per consentire l\'acquisto con pagamento tramite fattura o a rate.',
    'TCKLARNA_IS_SETTING_NATIONAL_IDENTIFICATION_NUMBER_MANDATORY'=> 'Il numero di identificazione nazionale è un campo obbligatorio',
    'TCKLARNA_IS_SETTING_NATIONAL_IDENTIFICATION_NUMBER_MANDATORY_TOOLTIP'=> 'Si prega di specificare se il numero di identificazione nazionale deve essere un campo obbligatorio.',
    'TCKLARNA_IS_BUTTON_SETTINGS_VARIATION'             => 'Variazione',
    'TCKLARNA_IS_BUTTON_SETTINGS_TAGLINE'               => 'Slogan',
    'TCKLARNA_IS_BUTTON_SETTINGS_TYPE'                  => 'Tipo',
    'TCKLARNA_IS_SETTING_PHONE_MANDATORY'               => 'Il numero di telefono è un campo obbligatorio',
    'TCKLARNA_IS_SETTING_PHONE_MANDATORY_TOOLTIP'       => 'Selezionare se il numero di telefono deve essere un campo obbligatorio.',
    'TCKLARNA_IS_DEFAULT_COUNTRY_TIP'                   => 'Selezionare dall\'elenco il Paese che deve essere impostato come predefinito all\'apertura di Klarna Instant Shopping, fintanto che il cliente non abbia ancora specificato il proprio Paese.',
    'TCKLARNA_IS_TERMS_URI_TIP'                         => 'Inserisci qui l\'URL delle tue Condizioni generali di contratto. Queste saranno collegate tramite link nel pop-up di Klarna Instant Shopping. È necessario inserire un URL valido che inizi con https://.',

    'TCKLARNA_SHIPPING_KCO'                             => 'Assegnazione delle modalità di spedizione per Klarna Checkout e Klarna Express',
    'TCKLARNA_SHIPPING_KCO_DESC'                        => 'Si prega di associare alle modalità di spedizione definite le corrispondenti denominazioni Klarna. Tramite questa associazione è possibile, tra l’altro, configurare la consegna ai punti di ritiro.',
    'TCKLARNA_SHIPPING_SETTINGS'                        => 'Modalità di spedizione',
    'TCKLARNA_COMPLETE_REFUND'                          => 'Accreditare l\'intero importo dell\'ordine',
    'TCKLARNA_PACKSTATION_NO_SHIPPING_SET'              => 'Non sono state trovate modalità di spedizione attive',

    'TCKLARNA_AUTHPAYMENTMETHOD'                        => 'Metodo di pagamento utilizzato: ',
    'TCKLARNA_AUTHPAYMENTMETHOD_unknown'                => 'Klarna',
    'TCKLARNA_AUTHPAYMENTMETHOD_direct_debit'           => 'Addebito diretto',
    'TCKLARNA_AUTHPAYMENTMETHOD_direct_bank_transfer'   => 'Bonifico immediato',
    'TCKLARNA_AUTHPAYMENTMETHOD_slice_it_by_card'       => '3 rate senza interessi',
    'TCKLARNA_AUTHPAYMENTMETHOD_fixed_sum_credit'       => 'Finanziamento',
    'TCKLARNA_AUTHPAYMENTMETHOD_b2b_invoice'            => 'Fattura B2B (Billie)',
    'TCKLARNA_AUTHPAYMENTMETHOD_pay_later_by_card'      => 'Pagamento con carta entro 30 giorni',
    'TCKLARNA_AUTHPAYMENTMETHOD_invoice'                => 'Fattura',
    'TCKLARNA_AUTHPAYMENTMETHOD_pay_by_card'            => 'Carta di credito',
    'TCKLARNA_AUTHPAYMENTMETHOD_bank_transfer'          => 'Bonifico bancario',
    'TCKLARNA_AUTHPAYMENTMETHOD_card'                   => 'Carta di credito',
    'TCKLARNA_AUTHPAYMENTMETHOD_fixed_amount'           => 'Finanziamento',
    'TCKLARNA_AUTHPAYMENTMETHOD_invoice_business'       => 'Fattura B2B (Billie)',
    'TCKLARNA_AUTHPAYMENTMETHOD_mobilepay'              => 'MobilePay',
    'TCKLARNA_AUTHPAYMENTMETHOD_pay_later_in_parts'     => 'Klarna: paga in seguito a rate',
    'TCKLARNA_AUTHPAYMENTMETHOD_swish'                  => 'Swish',
    'TCKLARNA_AUTHPAYMENTMETHOD_apple_pay_card'         => 'Apple Pay',
    'TCKLARNA_AUTHPAYMENTMETHOD_google_pay_card'        => 'Google Pay',
    'TCKLARNA_AUTHPAYMENTMETHOD_cartes_bancaires'       => 'Carte di credito',
    'TCKLARNA_AUTHPAYMENTMETHOD_blik'                   => 'BLIK',
    'TCKLARNA_AUTHPAYMENTMETHOD_twint'                  => 'TWINT',
    'TCKLARNA_AUTHPAYMENTMETHOD_bancontact'             => 'Bancontact',
    'TCKLARNA_AUTHPAYMENTMETHOD_diners'                 => 'Carta di credito',
    'TCKLARNA_AUTHPAYMENTMETHOD_discover'               => 'Carta di credito',
    'TCKLARNA_AUTHPAYMENTMETHOD_elo'                    => 'Carta di credito',
    'TCKLARNA_AUTHPAYMENTMETHOD_jcb'                    => 'Carta di credito',
    'TCKLARNA_AUTHPAYMENTMETHOD_union_pay'              => 'Carta di credito',
    'TCKLARNA_AUTHPAYMENTMETHOD_pay_by_bank'            => 'Pagamento tramite bonifico bancario',
    'TCKLARNA_AUTHPAYMENTMETHOD_other'                  => 'Checkout personalizzato',
);
