<?php
/**
 * Copyright 2018 Klarna AB
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$sLangName = "Română";
// -------------------------------
// RESOURCE IDENTITFIER = STRING
// -------------------------------
$aLang = array(
    'charset'                                           => 'UTF-8',

    'TCKLARNA_KLARNAMAINMENU'                           => 'Klarna',
    'TCKLARNA_START'                                    => 'Început',
    'TCKLARNA_GENERAL_SETTINGS'                         => 'În general',
    'TCKLARNA_CONFIGURATION'                            => 'Configurare',
    'TCKLARNA_CONFIGURATION_KCO'                        => 'Configurare pentru Klarna Checkout',
    'TCKLARNA_CONFIGURATION_KP'                         => 'Configurare pentru plățile Klarna',
    'TCKLARNA_KLARNADESIGN'                             => 'Setări de design',
    'TCKLARNA_EXTERNAL_PAYMENTS'                        => 'Modalități de plată externe',
    'TCKLARNA_EXTRA_MERCHANT_DATA'                      => 'Date suplimentare despre comerciant',
    'TCKLARNA_BASIC_SETTINGS'                           => 'Setări de bază',
    'TCKLARNA_DISCOUNT_TITLE'                           => 'Reducere',

    'tcklarna_tbclklarna_orders'                        => 'Klarna',
    'TCKLARNA_NO_OPTIONS_MODE'                          => 'În acest mod nu există setări.',
    'TCKLARNA_CHANGES_SAVED'                            => 'Toate setările au fost salvate.',
    'TCKLARNA_EMPTY_FIELDS_WARRNING'                    => 'Dacă câmpurile URL sunt lăsate goale, acest lucru poate duce la funcționarea defectuoasă a modulului.',

    'TCKLARNA_EASY'                                     => 'Atât de simplu este să activezi Klarna',
    'TCKLARNA_PHONE'                                    => 'Telefon',
    'TCKLARNA_EMAIL'                                    => 'E-mail',
    'TCKLARNA_BUSINESS_HOURS'                           => 'Programul de lucru',
    'TCKLARNA_MONDAY'                                   => 'Luni',
    'TCKLARNA_TUESDAY'                                  => 'Marți',
    'TCKLARNA_WEDNESDAY'                                => 'Miercuri',
    'TCKLARNA_THURSDAY'                                 => 'Joi',
    'TCKLARNA_FRIDAY'                                   => 'Vineri',
    'TCKLARNA_SATURDAY'                                 => 'Sâmbătă',
    'TCKLARNA_SUNDAY'                                   => 'Duminică',
    'TCKLARNA_YOUR_COUNTRY_SPECIFIC_CREDS'              => 'Datele dvs. de acces specifice fiecărei țări',
    'TCKLARNA_ADD_COUNTRY_SPECIFIC_CREDS'               => 'Adăugarea datelor de acces specifice fiecărei țări',
    'TCKLARNA_COUNTRY'                                  => 'Țară',
    'TCKLARNA_MERCHANT_ID'                              => 'Numele de utilizator API',
    'TCKLARNA_PASSWORD'                                 => 'Parola API',
    'TCKLARNA_PORTAL_MERCHANT_ID'                       => 'ID comerciant',
    'TCKLARNA_DEFAULT_SHOP_COUNTRY'                     => 'Țara implicită a magazinului',
    'TCKLARNA_ENABLE_LOGGING'                           => 'Înregistrare activă',
    'TCKLARNA_SEND_ADDITIONAL_PRODUCT_DATA'             => 'Să trimitem date suplimentare despre produs către Klarna?',
    'TCKLARNA_PRODUCT_URLS'                             => 'URL-uri ale produselor',
    'TCKLARNA_IMAGE_URLS'                               => 'URL-uri ale imaginilor',
    'TCKLARNA_ENABLE_ANONYMIZATION'                     => 'Anonimizare',
    'TCKLARNA_ADD'                                      => 'Adăugare',


    'TCKLARNA_CHECKOUT_NAME'                            => 'Klarna Checkout',
    'TCKLARNA_PAYMENTS_NAME'                            => 'Plăți Klarna',
    'TCKLARNA_CHOOSE_KLARNA_MODULE_MODE'                => 'Alege modul Klarna',

    'TCKLARNA_CHECKOUT_DESC'                            => 'Soluția completă include toate metodele de plată importante (factură, cumpărare în rate, transfer bancar instant, debit direct, Mastercard și VISA) și este găzduită de Klarna. La efectuarea plății, clienții dumneavoastră trebuie doar să introducă adresa de e-mail și codul poștal și pot alege metoda de plată preferată. Totul cu o singură integrare.',
    'TCKLARNA_PAYMENTS_DESC'                            => 'Cu Klarna, clienții finali pot plăti în trei moduri: transfer bancar instant, mai târziu sau în rate. Acest lucru le permite clienților finali să testeze mai întâi produsele și să plătească doar ceea ce doresc să păstreze, să finanțeze produsele din magazin sau să plătească imediat. Factura, cumpărarea în rate, transferul bancar instant sau debitul direct pot fi activate printr-o integrare și, datorită soluției iFrame de la Klarna, sunt întotdeauna la zi din punct de vedere juridic și al conținutului.',
    'TCKLARNA_EASY_AND_SECURE_SHOPPING'                 => 'Cele mai populare metode de plată. Sigure și ușor de integrat.',
    'TCKLARNA_WELCOME_TO_CONFIGURATION'                 => 'Bine ați venit în setările de configurare ale Klarna Checkout și Klarna Payments. Aici veți găsi tot ce este necesar pentru activare. Selectați submeniurile Klarna din bara din stânga pentru a finaliza configurarea modulului.',

    'TCKLARNA_CREATE_USER_ACCOUNT'                      => 'Crearea unui cont de client în OXID eShop',
    'TCKLARNA_SUBSCRIBE_TO_NEWSLETTER'                  => 'Înscriere la newsletter',
    'TCKLARNA_CREATE_USER_ACCOUNT_AND_SUBSCRIBE'        => 'Crearea unui cont de client ȘI abonarea la newsletter',
    'TCKLARNA_NO_CHECKBOX'                              => 'Nu afișa caseta de selectare',


    /* design */
    'TCKLARNA_DISPLAY_ON_HOME'                          => 'Să se afișeze pe pagina principală a magazinului?',
    'TCKLARNA_BANNER_SRC'                               => 'Sursa bannerului Klarna',
    'TCKLARNA_FOOTER'                                   => 'Subsol',
    'TCKLARNA_DISPLAY_IN_FOOTER'                        => 'Ce trebuie afișat în subsol?',
    'TCKLARNA_FOOTER_PAYMENT_METHODS'                   => 'Afișarea modalităților de plată',
    'TCKLARNA_FOOTER_KLARNA_LOGO'                       => 'Logo-ul Klarna',
    'TCKLARNA_DESIGN'                                   => 'Proiectare',
    'TCKLARNA_LONG_VERSION'                             => 'Versiunea lungă:',
    'TCKLARNA_SHORT_VERSION'                            => 'Versiunea scurtă:',
    'TCKLARNA_WHITE'                                    => 'Alb:',
    'TCKLARNA_BLACK'                                    => 'Negru:',
    'TCKLARNA_DETAILS_AND_BASKET'                       => 'Pagina cu detalii despre produs și coșul de cumpărături',
    'TCKLARNA_DISPLAY_PAYMENT_WIDGET'                   => 'Să afișezi widgetul pentru metoda de plată Klarna?',
    'TCKLARNA_ON_PROD_PAGE'                             => 'Pe pagina cu detalii despre produs',
    'TCKLARNA_KEB_CLID'                                 => 'Klarna Express Checkout – Identificator client',
    'TCKLARNA_KEB_SHIPPINGMETHOD'                       => 'Livrare prin Klarna Express Checkout',
    'TCKLARNA_KEB_THEME'                                => 'Tema butonului „Klarna Express Checkout”',
    'TCKLARNA_KEB_THEME_default'                        => 'Standard (închis)',
    'TCKLARNA_KEB_THEME_light'                          => 'Norvegiană',
    'TCKLARNA_KEB_THEME_outlined'                       => 'Prezentat pe scurt',
    'TCKLARNA_KEB_SHAPE'                                => 'Formularul butonului „Klarna Express Checkout”',
    'TCKLARNA_KEB_SHAPE_default'                        => 'Standard',
    'TCKLARNA_KEB_SHAPE_rect'                           => 'Dreptunghiular',
    'TCKLARNA_KEB_SHAPE_pill'                           => 'Pastilă',
    'TCKLARNA_ON_BASKET_PAGE'                           => 'Pe pagina coșului de cumpărături',
    'TCKLARNA_DISPLAY_EXPRESS_BUTTON'                   => 'Să se afișeze butonul „Klarna Express Checkout”?',
    'TCKLARNA_PAYMENT_DESIGN'                           => 'Opțiuni de design pentru plățile Klarna',
    'TCKLARNA_CHECKOUT_DESIGN'                          => 'Opțiuni de design pentru Klarna Checkout',
    'TCKLARNA_COLOR_SETTINGS'                           => 'Setări de culoare:',
    'TCKLARNA_BORDER'                                   => 'Graniță:',
    'TCKLARNA_BORDER_SELECTED'                          => 'Graniță selectată:',
    'TCKLARNA_BUTTON'                                   => 'Buton:',
    'TCKLARNA_BUTTON_TEXT'                              => 'Textul butonului:',
    'TCKLARNA_CHECKBOX'                                 => 'Casetă de selectare:',
    'TCKLARNA_CHECKBOX_CHECKMARK'                       => 'Bifați caseta de selectare:',
    'TCKLARNA_DETAILS'                                  => 'Detalii:',
    'TCKLARNA_HEADER'                                   => 'Antet:',
    'TCKLARNA_LINK'                                     => 'Link:',
    'TCKLARNA_TEXT'                                     => 'Text:',
    'TCKLARNA_SECONDARY_TEXT'                           => 'Text suplimentar:',
    'TCKLARNA_RADIUS_SETTINGS'                          => 'Reglarea razei:',
    'TCKLARNA_BORDER_RADIUS'                            => 'Raza de rotunjire a marginilor:',


    'TCKLARNA_ALLOW_SEPARATE_SHIPPING_ADDRESS'          => 'Adresa de livrare poate fi diferită de adresa de facturare',
    'TCKLARNA_PHONE_NUMBER_MANDATORY'                   => 'Numărul de telefon este un câmp obligatoriu',
    'TCKLARNA_DATE_OF_BIRTH_MANDATORY'                  => 'Data nașterii este un câmp obligatoriu',
    'TCKLARNA_ENABLE_AUTOFOCUS'                         => 'Activarea focalizării automate pentru iframe-ul Klarna Checkout ',
    'TCKLARNA_ADD_A_CUSTOM_CHECKBOX'                    => 'Adăugarea unei casete de selectare individuale în iframe-ul Klarna Checkout',
    'TCKLARNA_ENABLE_DHL_PACKSTATION'                   => 'Activarea livrării la un punct de ridicare DHL',
    'TCKLARNA_ENABLE_PRE_FILLING'                       => 'Activare preumplere',
    'TCKLARNA_ENABLE_PREFILL_NOTIFICATION'              => 'Activare notificare de preumplere',
    'TCKLARNA_SALUTATION_MANDATORY'                     => 'Câmpul „Formula de adresare” este obligatoriu',
    'TCKLARNA_SET_TAC_URI'                              => 'URL-ul către Termenii și condițiile dvs. – câmp obligatoriu pentru KCO și Klarna Express',
    'TCKLARNA_SET_CANCEL_URI'                           => 'URL privind dreptul de retragere – câmp obligatoriu pentru KCO și Klarna Express',
    'TCKLARNA_SHIPPING_DETAILS'                         => 'URL către detaliile de livrare – câmp obligatoriu pentru KCO și Klarna Express',
    'TCKLARNA_NO_VALIDATION_NEEDED'                     => 'Fără validare',
    'TCKLARNA_VALIDATION_IGNORE_TIMEOUTS_NEEDED'        => 'Efectuați validarea, dar ignorați depășirile de timp',
    'TCKLARNA_SUCCESSFUL_VALIDATION_NEEDED'             => 'Este necesară o validare reușită',
    'TCKLARNA_ORDER_VALIDATION'                         => 'Validarea comenzii',

    'TCKLARNA_CHOOSE_KP_OPTIONS'                        => 'Vă rugăm să selectați opțiunile de plată Klarna pe care doriți să le oferiți clienților dumneavoastră:',
    'TCKLARNA_PAY_LATER'                                => 'Factură',
    'TCKLARNA_PAY_LATER.'                               => 'Factură.',
    'TCKLARNA_PAY_LATER_START'                          => 'Pentru clienții care doresc să cumpere acum și să plătească mai târziu. Foarte comod, în 30 de zile, în funcție de piață.',
    'TCKLARNA_PAY_LATER_TEXT'                           => 'Opțiunea „Factură” le permite clienților să efectueze plata simplu și rapid, fără a fi nevoiți să introducă date personale sau numere complicate. Clientul poate alege între opțiunea „Factură” și „Plată în luna X”.',
    'TCKLARNA_SLICE_IT'                                 => 'Cumpărare în rate.',
    'TCKLARNA_SLICE_IT.'                                => 'Plata în rate.',
    'TCKLARNA_SLICE_IT_START'                           => 'Creșteți puterea de cumpărare a clienților dvs. prin plata în rate. Clienții își pot achita cumpărăturile în rate lunare fixe, pe o perioadă de 6 până la 36 de luni.',
    'TCKLARNA_SLICE_IT_TEXT'                            => 'Prin intermediul „cumpărării în rate”, clienții pot împărți suma de cumpărare în tranșe, la dobânzi reduse. Acest lucru sporește bugetul de investiții și puterea de cumpărare. Procesul unic de aprobare a creditului oferit de Klarna durează doar câteva momente și necesită introducerea unui număr minim de date.',
    'TCKLARNA_PAY_NOW'                                  => 'Plătește acum',
    'TCKLARNA_PAY_NOW.'                                 => 'Plătește imediat.',
    'TCKLARNA_PAY_NOW_START'                            => 'Plată directă simplă și rapidă cu opțiunea „Plată imediată” de la Klarna. În Germania, portofoliul ar trebui să includă neapărat transferul bancar instant, cardul de credit și debitul direct.',
    'TCKLARNA_PAY_NOW_TEXT'                             => 'Clienții care doresc să achite integral suma imediat la finalizarea comenzii pot utiliza opțiunea „Plată imediată”. Opțiunile disponibile sunt: cardul de credit, debitul direct și transferul bancar instant.',
    'TCKLARNA_CHECKOUT'                                 => 'Klarna Checkout.',
    'TCKLARNA_CHECKOUT_START'                           => 'Cea mai bună experiență de finalizare a comenzii pentru clienții dumneavoastră. Identificare fiabilă a clienților și opțiuni de livrare. Toate plățile incluse. Disponibilitate la nivel mondial, optimizată la nivel local. Ne asumăm întregul risc, iar dumneavoastră vă primiți întotdeauna banii.',

    'TCKLARNA_RB_HOW_TO_ACTIVATE'                       => 'How-to-activate<br>Klarna guide.',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_ONE'              => 'În panoul de administrare OXID, faceți clic pe noua opțiune de meniu „Klarna”, apoi pe subcategoria „General” și selectați produsul Klarna dorit. Puteți alege între „Klarna Payments” și „Klarna Checkout”.',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_TWO'              => 'Introduceți datele de acces (numele de utilizator și parola) și configurați setările specifice OXID pentru metodele de plată în secțiunile Setări magazin &gt; Metode de plată și &gt; Metode de livrare.',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_THREE'            => 'Salvați modificările.',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_FOUR'             => 'Acum sunteți online și puteți începe să vindeți prin Klarna.',
    'TCKLARNA_RB_MERCHANT_SUPPORT'                      => 'Asistență pentru comercianți',
    'TCKLARNA_DEVICE_IMG'                               => 'device.png',


    'TCKLARNA_EXTERNAL_PAYMENTS_ADMIN_DESC'             => 'Aici puteți configura metodele de plată externe și procesele de plată externe pentru a le integra în cadrul iframe-ului Klarna Checkout. 
Pentru o descriere detaliată a diferitelor setări, vă rugăm să consultați informațiile afișate la trecerea cursorului peste elemente 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, citiți manualul 
sau contactați serviciul de asistență pentru integrarea Klarna.',
    'TCKLARNA_EXTRA_MERCHANT_DATA_ADMIN_DESC'           => 'Aici puteți configura dacă, eventual, datele suplimentare ale comerciantului trebuie transmise către Klarna. 
Pentru o descriere detaliată a diferitelor setări, vă rugăm să consultați informațiile afișate la trecerea cursorului peste elemente 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, citiți manualul 
sau contactați serviciul de asistență pentru integrarea Klarna.',
    'TCKLARNA_DESIGN_SETTINGS_ADMIN_DESC'               => 'Aici puteți configura setările de design pentru utilizarea modulului Klarna în magazinul online OXID. 
Pentru o descriere detaliată a diferitelor setări, vă rugăm să consultați informațiile afișate la trecerea cursorului peste elemente 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, citiți manualul 
sau contactați serviciul de asistență pentru integrarea Klarna.',
    'TCKLARNA_GENERAL_SETTINGS_ADMIN_DESC'              => 'Alegeți aici între Klarna Checkout și Klarna Payments și configurați setările generale. 
Pentru o descriere detaliată a diferitelor setări, vă rugăm să consultați informațiile afișate la trecerea cursorului peste elemente 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, citiți manualul 
sau contactați serviciul de asistență pentru integrarea Klarna.',
    'TCKLARNA_CONFIGURATION_KCO_ADMIN_DESC'             => 'Pe această pagină puteți configura setările specifice pentru Klarna Checkout. 
Pentru o descriere detaliată a diferitelor setări, vă rugăm să consultați informațiile afișate la trecerea cursorului peste elemente 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, citiți manualul 
sau contactați serviciul de asistență pentru integrarea Klarna.',
    'TCKLARNA_CONFIGURATION_KP_ADMIN_DESC'              => 'Pe această pagină puteți alege ce metode de plată Klarna doriți să oferiți. 
Pentru o descriere detaliată a diferitelor setări, vă rugăm să consultați informațiile afișate la trecerea cursorului peste elemente 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, citiți manualul 
sau contactați serviciul de asistență pentru integrarea Klarna.',

    'TCKLARNA_PAYMENT_METHOD'                           => 'Modalitatea de plată',
    'TCKLARNA_EXTERNAL_PAYMENT_METHOD'                  => 'Modalitate de plată externă',
    'TCKLARNA_EXTERNAL_CHECKOUT'                        => 'Finalizare comandă externă',
    'TCKLARNA_IMAGE_URI_EXT_PAYMENT'                    => 'URI imagine pentru metoda de plată externă',
    'TCKLARNA_IMAGE_URI_EXT_CHECKOUT'                   => 'URI-ul imaginii pentru procesul de plată externă',
    'TCKLARNA_IMAGE_TIP_69x24'                          => 'Dimensiunea imaginii: 69x24 pixeli',
    'TCKLARNA_IMAGE_TIP_276x48'                         => 'Dimensiunea imaginii: 276x48 pixeli',
    'TCKLARNA_USER_GUIDE_DESCRIPTION'                   => 'Puteți consulta aici manualul de utilizare al modulului Klarna pentru OXID eShop.',
    'TCKLARNA_USER_GUIDE_LINK'                          => 'https://wiki.fatchip.de/public/faqklarna',
    'TCKLARNA_USER_GUIDE_BUTTON'                        => 'Manual de utilizare',

    'TCKLARNA_CHOOSE'                                   => 'Alegeți',

    'TCKLARNA_CUSTOMER_ACCOUNT_INFO'                    => 'Informații despre contul clientului',
    'TCKLARNA_PAYMENT_HISTORY_FULL'                     => 'Istoric complet al plăților',
    'TCKLARNA_PASSTHROUGH_FIELD'                        => 'Câmp de transfer',

    'TCKLARNA_ASSIGN_PAYMENT_METHOD_TYPE'               => 'Atribuirea tipului de metodă de plată:',
    'TCKLARNA_WHICH_ORDERS_IN_FULL_PAYMENT_HISTORY'     => 'Ce comenzi trebuie incluse în istoricul complet al plăților?',
    'TCKLARNA_EMD_ORDER_HISTORY_ALL'                    => 'Toate comenzile sunt considerate plătite, indiferent de data înregistrării în sistemul Oxpaid',
    'TCKLARNA_EMD_ORDER_HISTORY_PAID'                   => 'Trimite numai comenzile pentru care a fost setată o dată de plată; ignoră comenzile neplătite',
    'TCKLARNA_EMD_ORDER_HISTORY_NONE'                   => 'Ignoră toate comenzile efectuate cu această metodă de plată',
    'TCKLARNA_OTHER_PAYMENT'                            => 'Alte opțiuni de plată',
    'TCKLARNA_DIRECT_BANKING'                           => 'Transfer bancar instantaneu',
    'TCKLARNA_CARD'                                     => 'Harta',

    'TCKLARNA_TEST_MODE_TOOLTIP'                        => 'Alegeți între „Playground” (modul de testare) și „Live” (modul de producție). Activați modul de producție numai după efectuarea cu succes a testelor de integrare și după consultarea cu managerul dvs. de integrare Klarna.',
    'TCKLARNA_GLOBAL_MERCHANT_ID_TOOLTIP'               => 'Vă rugăm să introduceți aici datele de acces la API-ul Klarna. Le-ați primit în e-mailul de bun venit de la Klarna. Acest nume de utilizator și această parolă sunt valabile la nivel global pentru toate țările. Doar în cazul în care ați primit date de acces diferite pentru țări diferite, le puteți adăuga mai jos.',
    'TCKLARNA_GLOBAL_PASSWORD_TOOLTIP'                  => 'Introduceți aici parola corespunzătoare numelui de utilizator API folosit. Ați primit această parolă în e-mailul de bun venit de la Klarna.',
    'TCKLARNA_GLOBAL_PORTAL_MERCHANT_ID_TOOLTIP'        => 'Vă rugăm să introduceți aici ID-ul dvs. de comerciant Klarna. L-ați primit în e-mailul de bun venit de la Klarna.',
    'TCKLARNA_CREDENTIALS_COUNTRY_SELECTOR_TOOLTIP'             => 'Selectați din lista din stânga țara pentru care ați primit datele de acces specifice de la Klarna.',
    'TCKLARNA_CREDENTIALS_COUNTRY_MERCHANT_ID_TOOLTIP'          => 'Vă rugăm să introduceți aici numele de utilizator corespunzător pentru această țară.',
    'TCKLARNA_CREDENTIALS_COUNTRY_PASSWORD_TOOLTIP'             => 'Vă rugăm să introduceți aici parola corespunzătoare pentru această țară.',
    'TCKLARNA_CREDENTIALS_COUNTRY_PORTAL_MERCHANT_ID_TOOLTIP'   => 'Vă rugăm să introduceți aici ID-ul comerciantului corespunzător pentru această țară.',
    'TCKLARNA_DEFAULT_COUNTRY_TOOLTIP'                  => 'Vă rugăm să selectați din listă țara pentru care să se încarce în mod implicit Klarna Checkout, atât timp cât clientul nu și-a specificat încă țara.',
    'TCKLARNA_ENABLE_LOGGING_TOOLTIP'                   => 'Activează funcția de jurnalizare, astfel încât toată comunicarea prin API cu Klarna să fie înregistrată în tabelul MySQL tcklarna_logs. Acest lucru poate fi util în cazul analizării sau depanării. În mediul de producție, funcția ar trebui să fie dezactivată, deoarece, în caz contrar, s-ar putea acumula volume mari de jurnale și s-ar stoca date sensibile.',
    'TCKLARNA_SEND_PRODUCT_URLS_TOOLTIP'                => 'Trimiteți către Klarna adresele URL ale paginilor cu detalii despre produsele aflate în coșul de cumpărături al clienților dumneavoastră, astfel încât Klarna să poată crea ulterior linkuri către produsele dumneavoastră din portalul Klarna.',
    'TCKLARNA_SEND_PRODUCT_IMAGES_TOOLTIP'              => 'Trimiteți către Klarna adresele URL ale imaginilor articolelor din coșul de cumpărături al clienților dumneavoastră, pentru ca Klarna să le poată afișa pe portalul Klarna.',
    'TCKLARNA_ENABLE_ANONYMIZATION_TOOLTIP'             => 'Activați funcția de anonimizare pentru a ascunde denumirile articolelor din coșul de cumpărături al clienților dvs. față de Klarna. Această măsură este recomandată, de exemplu, pentru farmaciile online, dar trebuie aplicată numai după consultarea cu managerul de integrare Klarna.',
    'TCKLARNA_ALLOW_SEPARATE_DELIVERY_ADDRESS_TOOLTIP'  => 'Dacă doriți să permiteți livrarea la o altă adresă de livrare, bifați această casetă.',
    'TCKLARNA_MANDATORY_PHONE_TOOLTIP'                  => 'Dacă doriți să faceți obligatorie introducerea unui număr de telefon, bifați această casetă. În mod normal, pentru Klarna, numărul de telefon nu este un câmp obligatoriu.',
    'TCKLARNA_MANDATORY_BIRTH_DATE_TOOLTIP'             => 'Dacă doriți să faceți obligatorie introducerea datei de naștere, bifați această casetă. În mod normal, pentru Klarna, data de naștere nu este un câmp obligatoriu. Cu toate acestea, această informație este necesară pentru a permite achiziția pe factură sau plata în rate.',
    'TCKLARNA_ENABLE_AUTOFOCUS_TOOLTIP'                 => 'Cu ajutorul acestui buton, puteți activa opțiunea prin care, la încărcarea paginii cu Klarna Checkout, cadrul Iframe Klarna va fi selectat automat.',
    'TCKLARNA_CHECKBOX_TOOLTIP'                         => 'Există posibilitatea ca, în cadrul iframe-ului Klarna Checkout, să bifați o casetă de selectare suplimentară pentru a oferi clientului posibilitatea de a-și crea un cont de client sau de a se abona la newsletter-ul dvs., sau ambele. În cazul în care caseta de selectare este activată, iar clientul are deja un cont de client sau este deja abonat la newsletter, textul casetei de selectare va fi adaptat automat sau, dacă este cazul, caseta de selectare va fi ascunsă complet.',
    'TCKLARNA_VALIDATION_TOOLTIP'                       => 'Prin această opțiune puteți activa o verificare suplimentară a coșului de cumpărături, care verifică încă o dată disponibilitatea articolelor dorite la trimiterea comenzii prin Klarna Checkout, pentru a evita erorile cauzate de vânzările în exces. Se recomandă modul „Este necesară validarea cu succes”.',
    'TCKLARNA_SALUTATION_MANDATORY_TOOLTIP'             => 'Această setare se referă exclusiv la formularul Klarna Checkout pentru Marea Britanie: trebuie să fie obligatorie completarea titlului?',
    'TCKLARNA_ENABLE_DHL_PACKSTATIONS_TOOLTIP'          => 'Momentan nu este implementat',
    'TCKLARNA_ENABLE_PRE_FILLING_TOOLTIP'               => 'Activați completarea automată a iframe-ului Klarna Checkout cu datele clientului conectat la magazinul online OXID',
    'TCKLARNA_ENABLE_PREFILL_NOTIFICATION_TOOLTIP'      => 'Dacă funcția de completare automată a iframe-ului Klarna Checkout este activată, pentru anumite țări trebuie afișată o notă de confidențialitate corespunzătoare. Această notă se activează prin intermediul acestui buton.',
    'TCKLARNA_TERMS_AND_CONDITIONS_URL_TOOLTIP'         => 'Introduceți aici adresa URL către Termenii și condițiile dvs. generale. Aceștia vor fi afișați sub formă de link în iframe-ul Klarna Checkout. Trebuie să introduceți o adresă URL validă, care să înceapă cu https://.',
    'TCKLARNA_CANCELLATION_RIGHTS_URL_TOOLTIP'          => 'Introduceți aici adresa URL a paginii dvs. web care conține explicațiile privind dreptul de retragere. Adresa URL trebuie să înceapă cu https://.',
    'TCKLARNA_SHIPPING_DETAILS_TOOLTIP'                 => 'Aceste informații privind livrarea sunt afișate clientului pe pagina de confirmare, după finalizarea comenzii.',
    'TCKLARNA_EXTERNAL_PAYMENT_NAME_SELECT_TOOLTIP'     => 'Asociați această metodă de plată externă uneia dintre metodele de plată predefinite',
    'TCKLARNA_ENABLE_EXTERNAL_PAYMENT_TOOLTIP'          => 'Cu ajutorul acestui buton, puteți activa această metodă de plată ca metodă de plată externă pentru Klarna Checkout. Când este activată, clientul poate selecta această metodă de plată din lista de metode de plată din iframe-ul Klarna Checkout.',
    'TCKLARNA_ENABLE_EXTERNAL_CHECKOUT_TOOLTIP'         => 'Cu ajutorul acestui buton puteți activa această metodă de plată ca proces de plată extern. Când este activată, această metodă de plată va fi afișată în partea de jos a iframe-ului Klarna Checkout, înainte chiar de introducerea datelor clientului.',
    'TCKLARNA_EXTERNAL_PAYMENT_IMAGE_URL_TOOLTIP'       => 'Introduceți aici adresa URL a unei imagini care urmează să fie afișată lângă metoda de plată în iframe-ul Klarna Checkout. Se recomandă să utilizați o imagine de la o adresă URL sigură, care începe cu https://.',
    'TCKLARNA_EXTERNAL_CHECKOUT_IMAGE_URL_TOOLTIP'      => 'Introduceți aici adresa URL a unei imagini care urmează să fie afișată ca buton pentru această metodă de plată în iframe-ul Klarna Checkout de mai jos. Se recomandă utilizarea unei imagini de la o adresă URL sigură, care începe cu https://.',
    'TCKLARNA_EXTERNAL_IMAGE_URL_EMPTY'                 => 'Vă rugăm să indicați o adresă URL pentru toate limbile',
    'TCKLARNA_EXTERNAL_IMAGE_URL_INVALID'               => 'Vă rugăm să introduceți o adresă URL validă, care să înceapă cu https://',
    'TCKLARNA_EMD_CUSTOMER_INFO_TOOLTIP'                => 'Acest buton activează transmiterea de date suplimentare către Klarna; în acest caz, este vorba despre informațiile privind contul clientului, care includ data înregistrării contului clientului și data ultimei modificări a acestuia.',
    'TCKLARNA_EMD_PAYMENT_HISTORY_FULL_TOOLTIP'         => 'Acest buton activează transmiterea de date suplimentare către Klarna, în acest caz „Payment History Full”, care conține istoricul achizițiilor efectuate până în prezent de client.',
    'TCKLARNA_EMD_PAYMENT_TYPE_TOOLTIP'                 => 'Vă rugăm să indicați despre ce tip de plată este vorba în cazul acestei metode de plată.',
    'TCKLARNA_EMD_HISTORY_FULL_TOOLTIP'                 => 'Vă rugăm să specificați aici dacă și, eventual, care dintre comenzi, efectuate cu această metodă de plată, trebuie incluse în istoricul comenzilor clientului. Dependența câmpului OXORDER.OXPAID indică dacă trebuie luate în considerare doar comenzile plătite sau toate comenzile.',
    'TCKLARNA_EMD_PASSTHROUGH_FIELD_TOOLTIP'            => 'Există posibilitatea de a transmite către Klarna orice alte date dorite, cu ajutorul unui câmp „pass-through”. Pentru a utiliza această funcție, trebuie să instalați un modul corespunzător în OXID eShop, care să introducă datele dorite în câmpul „pass-through”. Găsiți instrucțiuni în acest sens în documentația pentru dezvoltatori.',
    'TCKLARNA_DISPLAY_ON_HOME_TOOLTIP'                  => 'Cu ajutorul acestui buton, puteți activa un banner Klarna pe pagina principală a magazinului dvs. în temele standard Flow sau Wave.',
    'TCKLARNA_BANNER_SRC_TOOLTIP'                       => 'Aici puteți introduce eticheta script pentru integrarea bannerului. În portalul de bannere al Klarna veți găsi, dacă este cazul, și alte bannere din care puteți alege.',
    'TCKLARNA_FOOTER_PAYMENT_METHODS_TOOLTIP'           => 'Cu ajutorul acestui buton, puteți activa afișarea metodei de plată Klarna în subsolul magazinului dvs. în temele standard Flow și, respectiv, Wave.',
    'TCKLARNA_FOOTER_KLARNA_LOGO_TOOLTIP'               => 'Cu ajutorul acestui buton, puteți insera logo-ul Klarna în subsolul magazinului dvs. în temele standard Flow sau Wave.',
    'TCKLARNA_BUY_NOW_ON_BASKET_TOOLTIP'                => 'Acest comutator adaugă un buton „Klarna Express Checkout” pe pagina coșului de cumpărături al magazinului dvs. în temele standard.',
    'TCKLARNA_BUY_NOW_ON_PROD_PAGE_TOOLTIP'             => 'Acest comutator adaugă un buton „Klarna Express Checkout” pe paginile cu detalii despre produse ale magazinului dvs. în temele standard.',
    'TCKLARNA_KEB_CLID_TOOLTIP'                         => 'Pentru a putea utiliza Klarna Express Checkout, trebuie să activați această opțiune în portalul Klarna, în fila „Conversion boosters”. După configurarea cu succes, identificatorul clientului poate fi copiat în acest câmp.',
    'TCKLARNA_BORDER_TOOLTIP'                           => 'Culoarea cadrului care apare în interfața magazinului online după selectarea metodei de plată Klarna, în cazul în care sunt disponibile diverse subopțiuni.',
    'TCKLARNA_BORDER_SELECTED_TOOLTIP'                  => 'Culoarea cadrului care apare în interfața magazinului online după selectarea metodei de plată Klarna, în cazul în care sunt disponibile mai multe subopțiuni. Această culoare este utilizată pentru a evidenția subopțiunea selectată în acel moment.',
    'TCKLARNA_BUTTON_TOOLTIP'                           => 'La momentul publicării acestui modul, această setare nu are încă niciun efect.',
    'TCKLARNA_BUTTON_TEXT_TOOLTIP'                      => 'La momentul publicării acestui modul, această setare nu are încă niciun efect.',
    'TCKLARNA_DESIGN_CHECKBOX_TOOLTIP'                  => 'Culoarea de fundal a butoanelor radio care apar în interfața magazinului online după selectarea metodei de plată Klarna, în cazul în care sunt disponibile mai multe subopțiuni',
    'TCKLARNA_DESIGN_CHECKBOX_CHECKMARK_TOOLTIP'        => 'La momentul publicării acestui modul, această setare nu are încă niciun efect.',
    'TCKLARNA_DETAILS_TOOLTIP'                          => 'Culoarea marcajelor de enumerare în afișarea detaliilor de plată pe pagina de selectare a modalităților de plată.',
    'TCKLARNA_HEADER_TOOLTIP'                           => 'La momentul publicării acestui modul, această setare nu are încă niciun efect.',
    'TCKLARNA_LINK_TOOLTIP'                             => 'Culoarea linkurilor din descrierea detaliată a metodelor de plată de pe pagina de selectare a metodelor de plată.',
    'TCKLARNA_TEXT_TOOLTIP'                             => 'Culoarea textului din descrierea detaliată a metodelor de plată de pe pagina de selectare a metodelor de plată.',
    'TCKLARNA_SECONDARY_TEXT_TOOLTIP'                   => 'Culoarea alternativă a textului din descrierea detaliată a metodelor de plată de pe pagina de selectare a metodelor de plată.',
    'TCKLARNA_BORDER_RADIUS_TOOLTIP'                    => 'Cu această setare puteți stabili gradul de rotunjire al cadrului care apare în interfața magazinului online, în funcție de diferitele subopțiuni disponibile, după selectarea metodei de plată Klarna.',

    'KLARNA_ONLY_FOR_KLARNA_PAYMENT'                    => 'Această filă se referă numai la comenzile efectuate prin Klarna',
    'KLARNA_CAPTURE_FULL_ORDER'                         => 'Înregistrarea comenzii complete',
    'KLARNA_CAPTURE_ID'                                 => 'ID-ul tranzacției',
    'KLARNA_CAPTURE_REFERENCE'                          => 'Referință Klarna',
    'KLARNA_CAPTURE_AMOUNT'                             => 'Suma debitată',
    'KLARNA_CAPTURE_DATE'                               => 'Debitat la data de',
    'KLARNA_REFUND_AMOUNT'                              => 'Suma rambursabilă',
    'KLARNA_REFUND_DESCRIPTION'                         => 'Rambursare – Explicație',
    'KLARNA_REFUND_DATE'                                => 'Înlocuit la',
    'KLARNA_CAPTURES'                                   => 'Debitări',
    'KLARNA_REFUNDS'                                    => 'Rambursări',
    'KLARNA_CANCEL_ORDER'                               => 'Anularea comenzii',
    'KLARNA_ORDER_IS_CANCELLED'                         => 'Comanda a fost anulată. ',
    'KLARNA_SEE_ORDER_IN_PORTAL'                        => '<a href="%s" target="_blank" class="alert-link">Vizualizați această comandă în portalul Klarna</a>',
    'KLARNA_ORDER_NOT_IN_SYNC'                          => '<strong>Atenție!</strong> Datele acestei comenzi diferă de cele înregistrate la Klarna. ',
    'TCKLARNA_ORDER_UPDATE_CANT_BE_SENT_TO_KLARNA'      => 'Atenție! Având în vedere starea actuală a comenzii, această modificare nu poate fi transmisă către Klarna. Dacă este necesar, efectuați manual modificarea corespunzătoare direct în portalul Klarna Merchant.',
    'TCKLARNA_ORDER_UPDATE_REJECTED_BY_KLARNA'          => 'Atenție! Ultimele modificări aduse acestei comenzi nu au putut fi procesate de Klarna (motiv: %s). Vă rugăm să anulați modificările recente efectuate în OXID eShop sau, dacă este necesar, să efectuați manual modificările corespunzătoare în Portalul comercianților Klarna.',
    'KLARNA_UNAUTHORIZED_REQUEST'                       => 'Solicitare neautorizată. Verificați setările modulului Klarna, ID-ul comerciantului și parola corespunzătoare.',
    'KLARNA_ORDER_NOT_FOUND'                            => 'Această comandă nu a putut fi găsită în sistemul Klarna. Prin urmare, modificările aduse datelor comenzii nu vor fi transmise către Klarna.',
    'KLARNA_MID_CHANGED_FOR_COUNTRY'                    => '<strong>Date de acces incorecte!</strong> Această comandă a fost plasată utilizând ID-ul comerciantului <strong>%s</strong>. ID-ul comerciantului configurat în prezent pentru <strong>%s</strong> este <strong>%s</strong>.',
    'TCKLARNA_PRODUCT_NAME'                             => 'Denumirea produsului',
    'TCKLARNA_ANONYMIZED_PRODUCT'                       => 'Titlul produsului anonimizat:',
    'TCKLARNA_KCO_INVOICE_MSG'                          => 'Plata este procesată de partenerul nostru, Klarna. Vă rugăm să consultați informațiile de plată trimise de Klarna, în cazul în care nu ați achitat încă comanda. Puteți gestiona toate cumpărăturile dvs. prin intermediul site-ului Klarna.com sau al aplicației Klarna și puteți chiar efectua plata cu un singur clic.',
    'TCKLARNA_KP_INVOICE_MSG'                           => 'Plata este procesată de partenerul nostru, Klarna. Vă rugăm să luați la cunoștință informațiile de plată trimise de Klarna. Puteți gestiona toate achizițiile dvs. prin intermediul site-ului Klarna.com sau al aplicației Klarna și puteți chiar efectua plata cu un singur clic.',
    'TCKLARNA_VOUCHER_DISCOUNT'                         => 'Cupon de reducere',

    'TCKLARNA_KCO_BUTTON_TOOLTIP'                       => 'Culoarea de fundal a butonului de plată din cadrul iframe-ului Klarna Checkout.',
    'TCKLARNA_KCO_BUTTON_TEXT_TOOLTIP'                  => 'Culoarea textului butonului de plată din iframe-ul Klarna Checkout.',
    'TCKLARNA_KCO_DESIGN_CHECKBOX_TOOLTIP'              => 'Culoarea de fundal a casetelor de selectare din cadrul iframe-ului Klarna Checkout.',
    'TCKLARNA_KCO_DESIGN_CHECKBOX_CHECKMARK_TOOLTIP'    => 'Culoarea bifei din casetele de selectare din cadrul iframe-ului Klarna Checkout.',
    'TCKLARNA_KCO_HEADER_TOOLTIP'                       => 'Culoarea titlurilor din cadrul iframe-ului Klarna Checkout.',
    'TCKLARNA_KCO_LINK_TOOLTIP'                         => 'Culoarea linkurilor din cadrul iframe-ului Klarna Checkout.',
    'TCKLARNA_KCO_BORDER_RADIUS_TOOLTIP'                => 'Cu această setare puteți stabili gradul de rotunjire al cadrului iframe-ului Klarna Checkout.',

    'TCKLARNA_GIFT_WRAPPING_TITLE'                      => 'Ambalaj cadou',
    'TCKLARNA_GIFT_CARD_TITLE'                          => 'Felicitare',

    'TCKLARNA_ERROR_SHOP_SSL_NOT_CONFIGURED'            => 'Eroare gravă: Este obligatoriu să specificați o adresă validă, protejată prin SSL (https), pentru $this->sSSLShopURL în fișierul config.inc.php al magazinului dvs. dacă doriți să activați funcția „%s”!',
    'TCKLARNA_ERROR_WRONG_CREDS'                        => '<strong>Date de acces incorecte!</strong>',
    'TCKLARNA_ERROR_KCO_INACTIVE'                       => 'Eroare de configurare: Klarna Checkout nu este activat în magazin',

    'KLARNA_CAPTURE_SUCCESSFULL'                        => 'Suma a fost debitată cu succes.',
    'TCKLARNA_CAPUTRE_FAIL_ORDER_CANCELLED'             => ' Comanda nu a putut fi debitată, deoarece a fost deja anulată.',
    'TCKLARNA_ANONYMIZED_PRODUCT_TOOLTIP'               => 'Introduceți aici șirul de caractere care trebuie trimis către Klarna în locul titlului real al produsului.',
    'TCKLARNA_NO_REQUESTS_WILL_BE_SENT'                 => 'Modificările pe care le faceți la această comandă nu vor fi transmise către Klarna.',
    'TCKLARNA_USER_GUIDE'                               => 'Manual de utilizare',
    'TCKLARNA_REGISTER_NOW_BUTTON'                      => 'Înregistrare',
    'TCKLARNA_LEARN_MORE_BUTTON'                        => 'Află mai multe',

    'TCKLARNA_CUSTOMER_TYPE'                            => 'Tipuri de clienți acceptați',
    'TCKLARNA_CUSTOMER_TYPE_TOOLTIP'                    => 'Aici puteți configura dacă magazinul să accepte doar tranzacții B2C (setare implicită), doar tranzacții B2B sau atât tranzacții B2C, cât și B2B. <br> Notă: După schimbarea tipului de client, memoria cache a sesiunii browserului trebuie ștearsă înainte de a putea testa plata.',
    'TCKLARNA_B2C'                                      => 'Numai clienți B2C',
    'TCKLARNA_B2B'                                      => 'Numai clienți B2B',
    'TCKLARNA_B2B_B2C'                                  => 'În principal clienți B2B, dar și clienți B2C',
    'TCKLARNA_B2C_B2B'                                  => 'În principal clienți B2C, dar și clienți B2B',
    'TCKLARNA_NEED_SUPPORT'                             => 'Aveți nevoie de ajutor cu integrarea?',
    'TCKLARNA_REACH_SUPPORT'                            => 'Contactați serviciul de asistență pentru comercianți al Klarna',

    'TCKLARNA_EU_WARNING'                               => '<p>Pentru a respecta Regulamentul UE privind geoblocarea, se recomandă insistent activarea tuturor țărilor europene și atribuirea acestora metodei de plată Klarna Checkout.</p><p>Lipsesc următoarele țări: %s</p>',

    'TCKLARNA_ON_SITE_MESSAGING'                        => 'Mesagerie în cadrul site-ului',
    'TCKLARNA_ON_SITE_MESSAGING_ADMIN_DESC'             => 'Aici puteți configura funcția de mesagerie pe site pentru a o utiliza împreună cu modulul Klarna pentru OXID eShop.',
    'TCKLARNA_ON_SITE_MESSAGING_SCRIPT'                 => 'Scenariu',
    'TCKLARNA_CREDIT_PROMOTION_PRODUCT'                 => 'Pagina cu detalii despre produsul „Credit Promotion”',
    'TCKLARNA_CREDIT_PROMOTION_BASKET'                  => 'Promovare credite Coș de cumpărături',
    'TCKLARNA_TOP_STRIP_PROMOTION'                      => 'Promoție „Top-strip”',
    'TCKLARNA_FOOTER_PROMOTION'                         => 'Promoție în subsol',
    'TCKLARNA_BANNER_PROMOTION'                         => 'Promoție cu banner',
    'TCKLARNA_ON_SITE_MESSAGING_SCRIPT_TOOLTIP'         => 'Vă rugăm să inserați aici fragmentul de cod al bibliotecii JavaScript necesar pentru funcția de mesagerie pe site, pe care îl puteți obține din Portalul comercianților Klarna.',
    'TCKLARNA_CREDIT_PROMOTION_PRODUCT_TOOLTIP'         => 'Vă rugăm să inserați aici eticheta de plasare pentru a promova finanțarea și achiziția în rate prin Credit Promotions pe pagina cu detalii despre produs',
    'TCKLARNA_CREDIT_PROMOTION_BASKET_TOOLTIP'          => 'Vă rugăm să inserați aici eticheta de plasare pentru a promova finanțarea și achiziția în rate prin Credit Promotions în pagina de prezentare a coșului de cumpărături',
    'TCKLARNA_TOP_STRIP_PROMOTION_TOOLTIP'              => 'Vă rugăm să inserați aici eticheta de plasare pentru a promova informații generice și specifice metodelor de plată pe pagina principală a magazinului',
    'TCKLARNA_FOOTER_PROMOTION_TOOLTIP'                 => 'Vă rugăm să inserați aici eticheta de plasare pentru a afișa metodele de plată Klarna disponibile în subsolul magazinului',
    'TCKLARNA_BANNER_PROMOTION_TOOLTIP'                 => 'Vă rugăm să inserați aici eticheta de plasare pentru a adăuga un banner pe pagina principală a magazinului dumneavoastră',
    'TCKLARNA_ON_SITE_MESSAGING_HEADER_TITLE'           => 'Ce este mesageria on-site?',
    'TCKLARNA_ON_SITE_MESSAGING_HEADER_DESC'            => 'Clienții nu sunt întotdeauna conștienți de diversele opțiuni de creditare și finanțare care le stau la dispoziție înainte de a ajunge la casă. Opțiunile de finanțare disponibile din timp influențează decizia de cumpărare.

Funcția „On-Site Messaging” se integrează ușor și fără probleme și oferă informații personalizate, de la bannere generale care promovează parteneriatul dvs. cu Klarna și disponibilitatea plății în rate, până la oferte de credit personalizate pe paginile de produse sau din coșul de cumpărături.',
    'TCKLARNA_ON_SITE_MESSAGING_HEADER_DESC_2'          => 'Informații suplimentare despre primii pași pot fi găsite aici: <a class="cl-pink" href="https://docs.klarna.com/conversion-boosters/on-site-messaging/before-you-start/" target="_blank" rel=”noopener”></a><br><br> 
Conectați-vă la <a class="cl-pink" href="https://merchants.klarna.com/" target="_blank">Portalul Comercianților</a> pentru a genera codul JavaScript personal și codul de plasare. Mesageria pe site va fi activată în magazinul dvs. după ce codul JavaScript a fost salvat și cel puțin un cod de plasare a fost introdus.<br> 
Îl puteți dezactiva oricând, eliminând din nou codurile.',
    'TCKLARNA_ON_SITE_MESSAGING_MERCHANT_BUTTON'        => 'Portalul comercianților',

    'TCKLARNA_IS_ENABLED_HEADLINE'                      => 'Activarea funcției Klarna Instant Shopping',
    'TCKLARNA_IS_ENABLED'                               => 'Activ',
    'TCKLARNA_IS_BUTTON_REPLACE'                        => 'Înlocuirea butonului Key',
    'TCKLARNA_IS_REPLACE'                               => 'Crearea unui nou buton „Key”',
    'TCKLARNA_IS_BUTTON_REPLACE_TOOLTIP'                => 'Puteți actualiza „Button Key” dacă datele de configurare sau de identificare necesită o modificare din partea Klarna. În mod normal, puteți utiliza un „Button Key” generat o singură dată atât timp cât doriți.',
    'TCKLARNA_IS_ENABLED_TOOLTIP'                       => 'Activați aici funcția Klarna Instant Shopping. Astfel, se va genera automat un buton pe care îl puteți utiliza în interfața magazinului.',
    'TCKLARNA_IS_BUTTON_APEARANCE_HEADLINE'             => 'Setări de stil pentru butoane',
    'TCKLARNA_IS_VARIATION_TOOLTIP'                     => 'Vă rugăm să alegeți între un buton cu designul complet al mărcii Klarna și o variantă mai neutră, de tip „Light”.',
    'TCKLARNA_IS_TAGLINE_TOOLTIP'                       => 'Vă rugăm să alegeți dacă culoarea textului sloganului de sub buton să fie deschisă sau închisă.',
    'TCKLARNA_IS_TYPE_TOOLTIP'                          => 'Vă rugăm să selectați textul dorit pentru buton.',
    'TCKLARNA_IS_BUTTON_PREVIEW'                        => 'Previzualizare buton',
    'TCKLARNA_IS_BUTTON_PLACEMENT_DETAILS'              => 'Afișare pe pagina cu detalii despre produs',
    'TCKLARNA_IS_BUTTON_PLACEMENT_DETAILS_TOOLTIP'      => 'Activați această funcție pentru ca butonul Klarna Instant Shopping să apară pe toate paginile cu detalii despre produse din magazinul dvs.',
    'TCKLARNA_IS_BUTTON_PLACEMENT_BASKET'               => 'Afișare în pagina de prezentare a coșului de cumpărături',
    'TCKLARNA_IS_BUTTON_PLACEMENT_BASKET_TOOLTIP'       => 'Activați această funcție pentru ca butonul Klarna Instant Shopping să apară în pagina de prezentare a coșului de cumpărături din magazinul dvs.',
    'TCKLARNA_IS_BUTTON_SETTINGS_HEADLINE'              => 'Alte setări pentru Instant Shopping',
    'TCKLARNA_IS_SETTING_ALLOW_SEPARATE_SHIPPING_ADDRESS'                   => 'Adresa de livrare poate fi diferită de adresa de facturare',
    'TCKLARNA_IS_SETTING_ALLOW_SEPARATE_SHIPPING_ADDRESS_TOOLTIP'           => 'Dacă doriți să permiteți livrarea la o altă adresă de livrare, bifați această casetă.',
    'TCKLARNA_IS_SETTING_DATE_OF_BIRTH_MANDATORY'                           => 'Data nașterii este un câmp obligatoriu',
    'TCKLARNA_IS_SETTING_DATE_OF_BIRTH_MANDATORY_TOOLTIP'                   => 'Dacă doriți să faceți obligatorie introducerea datei de naștere, bifați această casetă. În mod normal, pentru Klarna, data de naștere nu este un câmp obligatoriu. Cu toate acestea, introducerea acesteia este necesară pentru a permite achiziția pe factură sau plata în rate.',
    'TCKLARNA_IS_SETTING_NATIONAL_IDENTIFICATION_NUMBER_MANDATORY'          => 'Numărul de identificare național este un câmp obligatoriu',
    'TCKLARNA_IS_SETTING_NATIONAL_IDENTIFICATION_NUMBER_MANDATORY_TOOLTIP'  => 'Vă rugăm să selectați dacă numărul național de identificare trebuie să fie un câmp obligatoriu.',
    'TCKLARNA_IS_BUTTON_SETTINGS_VARIATION'             => 'Variație',
    'TCKLARNA_IS_BUTTON_SETTINGS_TAGLINE'               => 'Slogan',
    'TCKLARNA_IS_BUTTON_SETTINGS_TYPE'                  => 'Tip',
    'TCKLARNA_IS_SETTING_PHONE_MANDATORY'               => 'Numărul de telefon este un câmp obligatoriu',
    'TCKLARNA_IS_SETTING_PHONE_MANDATORY_TOOLTIP'       => 'Vă rugăm să alegeți dacă numărul de telefon trebuie să fie un câmp obligatoriu.',
    'TCKLARNA_IS_DEFAULT_COUNTRY_TIP'                   => 'Vă rugăm să selectați din listă țara care să fie setată implicit la accesarea Klarna Instant Shopping, atât timp cât clientul nu și-a specificat încă țara.',
    'TCKLARNA_IS_TERMS_URI_TIP'                         => 'Introduceți aici adresa URL către Termenii și condițiile dvs. generale. Aceștia vor fi afișați sub formă de link în fereastra pop-up Klarna Instant Shopping. Trebuie să introduceți o adresă URL validă, care să înceapă cu https://.',

    'TCKLARNA_SHIPPING_KCO'                             => 'Atribuirea metodelor de livrare pentru Klarna Checkout și Klarna Express',
    'TCKLARNA_SHIPPING_KCO_DESC'                        => 'Vă rugăm să asociați denumirile corespunzătoare din Klarna cu modalitățile de livrare pe care le-ați definit. Prin această asociere configurați, printre altele, livrarea către punctele de ridicare.',
    'TCKLARNA_SHIPPING_SETTINGS'                        => 'Modalități de livrare',
    'TCKLARNA_COMPLETE_REFUND'                          => 'Să se crediteze întreaga comandă',
    'TCKLARNA_PACKSTATION_NO_SHIPPING_SET'              => 'Nu s-au găsit metode de livrare active',

    'TCKLARNA_AUTHPAYMENTMETHOD'                        => 'Metoda de plată utilizată: ',
    'TCKLARNA_AUTHPAYMENTMETHOD_unknown'                => 'Klarna',
    'TCKLARNA_AUTHPAYMENTMETHOD_direct_debit'           => 'Debit direct',
    'TCKLARNA_AUTHPAYMENTMETHOD_direct_bank_transfer'   => 'Transfer bancar instantaneu',
    'TCKLARNA_AUTHPAYMENTMETHOD_slice_it_by_card'       => '3 rate fără dobândă',
    'TCKLARNA_AUTHPAYMENTMETHOD_fixed_sum_credit'       => 'Finanțare',
    'TCKLARNA_AUTHPAYMENTMETHOD_b2b_invoice'            => 'Factură B2B (Billie)',
    'TCKLARNA_AUTHPAYMENTMETHOD_pay_later_by_card'      => 'Plată cu cardul în 30 de zile',
    'TCKLARNA_AUTHPAYMENTMETHOD_invoice'                => 'Factură',
    'TCKLARNA_AUTHPAYMENTMETHOD_pay_by_card'            => 'Card de credit',
    'TCKLARNA_AUTHPAYMENTMETHOD_bank_transfer'          => 'Transfer bancar',
    'TCKLARNA_AUTHPAYMENTMETHOD_card'                   => 'Card de credit',
    'TCKLARNA_AUTHPAYMENTMETHOD_fixed_amount'           => 'Finanțare',
    'TCKLARNA_AUTHPAYMENTMETHOD_invoice_business'       => 'Factură B2B (Billie)',
    'TCKLARNA_AUTHPAYMENTMETHOD_mobilepay'              => 'MobilePay',
    'TCKLARNA_AUTHPAYMENTMETHOD_pay_later_in_parts'     => 'Klarna – Plătește mai târziu, în rate',
    'TCKLARNA_AUTHPAYMENTMETHOD_swish'                  => 'Swish',
    'TCKLARNA_AUTHPAYMENTMETHOD_apple_pay_card'         => 'Apple Pay',
    'TCKLARNA_AUTHPAYMENTMETHOD_google_pay_card'        => 'Google Pay',
    'TCKLARNA_AUTHPAYMENTMETHOD_cartes_bancaires'       => 'Carduri bancare',
    'TCKLARNA_AUTHPAYMENTMETHOD_blik'                   => 'BLIK',
    'TCKLARNA_AUTHPAYMENTMETHOD_twint'                  => 'TWINT',
    'TCKLARNA_AUTHPAYMENTMETHOD_bancontact'             => 'Bancontact',
    'TCKLARNA_AUTHPAYMENTMETHOD_diners'                 => 'Card de credit',
    'TCKLARNA_AUTHPAYMENTMETHOD_discover'               => 'Card de credit',
    'TCKLARNA_AUTHPAYMENTMETHOD_elo'                    => 'Card de credit',
    'TCKLARNA_AUTHPAYMENTMETHOD_jcb'                    => 'Card de credit',
    'TCKLARNA_AUTHPAYMENTMETHOD_union_pay'              => 'Card de credit',
    'TCKLARNA_AUTHPAYMENTMETHOD_pay_by_bank'            => 'Plată prin transfer bancar',
    'TCKLARNA_AUTHPAYMENTMETHOD_other'                  => 'Proces de finalizare a comenzii personalizat',
);
