<?php
/**
 * Copyright 2018 Klarna AB
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$sLangName = "Norsk";
// -------------------------------
// RESOURCE IDENTITFIER = STRING
// -------------------------------
$aLang = array(
    'charset'                                           => 'UTF-8',

    'TCKLARNA_KLARNAMAINMENU'                           => 'Klarna',
    'TCKLARNA_START'                                    => 'Start',
    'TCKLARNA_GENERAL_SETTINGS'                         => 'Generelt',
    'TCKLARNA_CONFIGURATION'                            => 'Konfigurasjon',
    'TCKLARNA_CONFIGURATION_KCO'                        => 'Konfigurasjon for Klarna Checkout',
    'TCKLARNA_CONFIGURATION_KP'                         => 'Konfigurasjon for Klarna Payments',
    'TCKLARNA_KLARNADESIGN'                             => 'Designinnstillinger',
    'TCKLARNA_EXTERNAL_PAYMENTS'                        => 'Eksterne betalingsmåter',
    'TCKLARNA_EXTRA_MERCHANT_DATA'                      => 'Ytterligere forhandleropplysninger',
    'TCKLARNA_BASIC_SETTINGS'                           => 'Grunninnstillinger',
    'TCKLARNA_DISCOUNT_TITLE'                           => 'Rabatt',

    'tcklarna_tbclklarna_orders'                        => 'Klarna',
    'TCKLARNA_NO_OPTIONS_MODE'                          => 'I denne modusen finnes det ingen innstillinger.',
    'TCKLARNA_CHANGES_SAVED'                            => 'Alle innstillinger er lagret.',
    'TCKLARNA_EMPTY_FIELDS_WARRNING'                    => 'Hvis URL-feltene ikke fylles ut, kan dette føre til at modulen ikke fungerer som den skal.',

    'TCKLARNA_EASY'                                     => 'Det er så enkelt å aktivere Klarna',
    'TCKLARNA_PHONE'                                    => 'Telefon',
    'TCKLARNA_EMAIL'                                    => 'E-post',
    'TCKLARNA_BUSINESS_HOURS'                           => 'Åpningstider',
    'TCKLARNA_MONDAY'                                   => 'mandag',
    'TCKLARNA_TUESDAY'                                  => 'Tirsdag',
    'TCKLARNA_WEDNESDAY'                                => 'onsdag',
    'TCKLARNA_THURSDAY'                                 => 'Torsdag',
    'TCKLARNA_FRIDAY'                                   => 'fredag',
    'TCKLARNA_SATURDAY'                                 => 'Lørdag',
    'TCKLARNA_SUNDAY'                                   => 'Søndag',
    'TCKLARNA_YOUR_COUNTRY_SPECIFIC_CREDS'              => 'Dine landsspesifikke påloggingsopplysninger',
    'TCKLARNA_ADD_COUNTRY_SPECIFIC_CREDS'               => 'Legg til landsspesifikke påloggingsopplysninger',
    'TCKLARNA_COUNTRY'                                  => 'Land',
    'TCKLARNA_MERCHANT_ID'                              => 'API-brukernavn',
    'TCKLARNA_PASSWORD'                                 => 'API-passord',
    'TCKLARNA_PORTAL_MERCHANT_ID'                       => 'Forhandler-ID',
    'TCKLARNA_DEFAULT_SHOP_COUNTRY'                     => 'Standardland for nettbutikken',
    'TCKLARNA_ENABLE_LOGGING'                           => 'Logging aktiv',
    'TCKLARNA_SEND_ADDITIONAL_PRODUCT_DATA'             => 'Sende utvidede produktdata til Klarna?',
    'TCKLARNA_PRODUCT_URLS'                             => 'Produkt-URL-er',
    'TCKLARNA_IMAGE_URLS'                               => 'Bilde-URL-er',
    'TCKLARNA_ENABLE_ANONYMIZATION'                     => 'Anonymisere',
    'TCKLARNA_ADD'                                      => 'Legg til',


    'TCKLARNA_CHECKOUT_NAME'                            => 'Klarna Checkout',
    'TCKLARNA_PAYMENTS_NAME'                            => 'Klarna-betalinger',
    'TCKLARNA_CHOOSE_KLARNA_MODULE_MODE'                => 'Velg Klarna-modul og modus',

    'TCKLARNA_CHECKOUT_DESC'                            => 'Den komplette løsningen omfatter alle viktige betalingsmåter (faktura, avbetalingskjøp, Sofortüberweisung, direkte belastning, Mastercard og VISA-kort) og driftes av Klarna. Kundene dine trenger bare å oppgi e-postadresse og postnummer ved betaling, og kan velge sin foretrukne betalingsmåte. Alt med bare én integrasjon.',
    'TCKLARNA_PAYMENTS_DESC'                            => 'Med Klarna kan sluttkunder betale på tre måter: Sofortüberweisung, senere eller i avdrag. Dette gjør det mulig for sluttkunder å prøve varene først og bare betale for det de ønsker å beholde, finansiere produkter i nettbutikken eller betale umiddelbart. Faktura, avbetalingskjøp, umiddelbar bankoverføring eller direkte belastning kan du aktivere med en integrasjon, og takket være Klarnas iFrame-løsning er disse alternativene alltid oppdatert både juridisk og innholdsmessig.',
    'TCKLARNA_EASY_AND_SECURE_SHOPPING'                 => 'De mest populære betalingsmåtene. Sikre og enkle å integrere.',
    'TCKLARNA_WELCOME_TO_CONFIGURATION'                 => 'Hjertelig velkommen til konfigurasjonsinnstillingene for Klarna Checkout og Klarna Payments. Her finner du alt du trenger for å aktivere tjenestene. Velg undermenyene for Klarna i menyen til venstre for å fullføre moduloppsettet.',

    'TCKLARNA_CREATE_USER_ACCOUNT'                      => 'Opprette en kundekonto i OXID eShop',
    'TCKLARNA_SUBSCRIBE_TO_NEWSLETTER'                  => 'Påmelding til nyhetsbrev',
    'TCKLARNA_CREATE_USER_ACCOUNT_AND_SUBSCRIBE'        => 'Opprett kundekonto OG meld deg på nyhetsbrevet',
    'TCKLARNA_NO_CHECKBOX'                              => 'Ikke vis avkrysningsrute',


    /* design */
    'TCKLARNA_DISPLAY_ON_HOME'                          => 'Vise på butikkens startside?',
    'TCKLARNA_BANNER_SRC'                               => 'Kilde til Klarna-banner',
    'TCKLARNA_FOOTER'                                   => 'Bunntekst',
    'TCKLARNA_DISPLAY_IN_FOOTER'                        => 'Hva skal vises i bunnteksten?',
    'TCKLARNA_FOOTER_PAYMENT_METHODS'                   => 'Visning av betalingsmåter',
    'TCKLARNA_FOOTER_KLARNA_LOGO'                       => 'Klarna-logoen',
    'TCKLARNA_DESIGN'                                   => 'Design',
    'TCKLARNA_LONG_VERSION'                             => 'Lang versjon:',
    'TCKLARNA_SHORT_VERSION'                            => 'Kortversjon:',
    'TCKLARNA_WHITE'                                    => 'Hvitt:',
    'TCKLARNA_BLACK'                                    => 'Svart:',
    'TCKLARNA_DETAILS_AND_BASKET'                       => 'Artikkeloversikt og handlekurv',
    'TCKLARNA_DISPLAY_PAYMENT_WIDGET'                   => 'Vise Klarna-betalingsmetode-widgeten?',
    'TCKLARNA_ON_PROD_PAGE'                             => 'På artikkelens detaljsiden',
    'TCKLARNA_KEB_CLID'                                 => 'Klarna Express Checkout – Kundekode',
    'TCKLARNA_KEB_SHIPPINGMETHOD'                       => 'Klarna Express Checkout – frakt',
    'TCKLARNA_KEB_THEME'                                => 'Tema for Klarna Express-betalingsknapp',
    'TCKLARNA_KEB_THEME_default'                        => 'Standard (mørk)',
    'TCKLARNA_KEB_THEME_light'                          => 'Hell',
    'TCKLARNA_KEB_THEME_outlined'                       => 'Skissert',
    'TCKLARNA_KEB_SHAPE'                                => 'Skjema for Klarna Express-betalingsknapp',
    'TCKLARNA_KEB_SHAPE_default'                        => 'Standard',
    'TCKLARNA_KEB_SHAPE_rect'                           => 'Rektangulær',
    'TCKLARNA_KEB_SHAPE_pill'                           => 'Pille',
    'TCKLARNA_ON_BASKET_PAGE'                           => 'På handlekurv-siden',
    'TCKLARNA_DISPLAY_EXPRESS_BUTTON'                   => 'Vise Klarna Express Checkout-knappen?',
    'TCKLARNA_PAYMENT_DESIGN'                           => 'Klarna-betalingsdesignalternativer',
    'TCKLARNA_CHECKOUT_DESIGN'                          => 'Designalternativer for Klarna Checkout',
    'TCKLARNA_COLOR_SETTINGS'                           => 'Fargeinnstillinger:',
    'TCKLARNA_BORDER'                                   => 'Grense:',
    'TCKLARNA_BORDER_SELECTED'                          => 'Valgt grense:',
    'TCKLARNA_BUTTON'                                   => 'Knapp:',
    'TCKLARNA_BUTTON_TEXT'                              => 'Tekst på knappen:',
    'TCKLARNA_CHECKBOX'                                 => 'Avkryssingsrute:',
    'TCKLARNA_CHECKBOX_CHECKMARK'                       => 'Avkryssingsrute:',
    'TCKLARNA_DETAILS'                                  => 'Detaljer:',
    'TCKLARNA_HEADER'                                   => 'Overskrift:',
    'TCKLARNA_LINK'                                     => 'Lenke:',
    'TCKLARNA_TEXT'                                     => 'Tekst:',
    'TCKLARNA_SECONDARY_TEXT'                           => 'Ytterligere tekst:',
    'TCKLARNA_RADIUS_SETTINGS'                          => 'Innstilling av radius:',
    'TCKLARNA_BORDER_RADIUS'                            => 'Kantradius:',


    'TCKLARNA_ALLOW_SEPARATE_SHIPPING_ADDRESS'          => 'Leveringsadressen kan avvike fra fakturaadressen',
    'TCKLARNA_PHONE_NUMBER_MANDATORY'                   => 'Telefonnummer er et obligatorisk felt',
    'TCKLARNA_DATE_OF_BIRTH_MANDATORY'                  => 'Fødselsdato er et obligatorisk felt',
    'TCKLARNA_ENABLE_AUTOFOCUS'                         => 'Aktiver autofokus for Klarna Checkout-iframe ',
    'TCKLARNA_ADD_A_CUSTOM_CHECKBOX'                    => 'Legg til en individuell avkryssingsrute i Klarna Checkout-iframe',
    'TCKLARNA_ENABLE_DHL_PACKSTATION'                   => 'Aktiver levering til DHL Packstation',
    'TCKLARNA_ENABLE_PRE_FILLING'                       => 'Aktiver forhåndsfylling',
    'TCKLARNA_ENABLE_PREFILL_NOTIFICATION'              => 'Aktiver varsel om forhåndsfylling',
    'TCKLARNA_SALUTATION_MANDATORY'                     => 'Tittel er et obligatorisk felt',
    'TCKLARNA_SET_TAC_URI'                              => 'URL til dine vilkår og betingelser – obligatorisk felt for KCO og Klarna Express',
    'TCKLARNA_SET_CANCEL_URI'                           => 'URL om angrerett – obligatorisk felt for KCO og Klarna Express',
    'TCKLARNA_SHIPPING_DETAILS'                         => 'URL til leveringsdetaljer – obligatorisk felt for KCO og Klarna Express',
    'TCKLARNA_NO_VALIDATION_NEEDED'                     => 'Ingen validering',
    'TCKLARNA_VALIDATION_IGNORE_TIMEOUTS_NEEDED'        => 'Gjennomfør validering, men ignorér tidsavbrudd',
    'TCKLARNA_SUCCESSFUL_VALIDATION_NEEDED'             => 'Vellykket validering er nødvendig',
    'TCKLARNA_ORDER_VALIDATION'                         => 'Bekreftelse av bestilling',

    'TCKLARNA_CHOOSE_KP_OPTIONS'                        => 'Vennligst velg de Klarna-betalingsalternativene du ønsker å tilby kundene dine:',
    'TCKLARNA_PAY_LATER'                                => 'Faktura',
    'TCKLARNA_PAY_LATER.'                               => 'Faktura.',
    'TCKLARNA_PAY_LATER_START'                          => 'For kunder som ønsker å kjøpe nå og betale senere. Helt enkelt innen 30 dager, avhengig av marked.',
    'TCKLARNA_PAY_LATER_TEXT'                           => 'Alternativet «Faktura» gjør betalingsprosessen enkel og rask for kundene, uten at de trenger å oppgi personopplysninger eller kompliserte numre. Kunden kan velge mellom faktura og betaling i måned X.',
    'TCKLARNA_SLICE_IT'                                 => 'Avbetalingskjøp.',
    'TCKLARNA_SLICE_IT.'                                => 'Betale i avdrag.',
    'TCKLARNA_SLICE_IT_START'                           => 'Øk kundenes kjøpekraft ved å tilby avbetaling. Kundene kan betale for kjøpene sine i faste månedlige avdrag over en periode på 6 til 36 måneder.',
    'TCKLARNA_SLICE_IT_TEXT'                            => 'Gjennom «avbetalingskjøp» kan kundene dele opp kjøpesummen i mindre delbetalinger til lav rente. Dette øker investeringsrammen og kjøpekraften. Klarnas unike kredittbehandling tar bare noen få øyeblikk og krever minimalt med datainnlegging.',
    'TCKLARNA_PAY_NOW'                                  => 'Betal nå',
    'TCKLARNA_PAY_NOW.'                                 => 'Betal med en gang.',
    'TCKLARNA_PAY_NOW_START'                            => 'Enkel og rask direktebetaling med Klarnas «Sofort bezahlen». I Tyskland bør Sofortüberweisung, kredittkort og direktebelastning være en del av tilbudet.',
    'TCKLARNA_PAY_NOW_TEXT'                             => 'Kunder som ønsker å betale hele beløpet umiddelbart ved bestillingsavslutningen, kan benytte seg av alternativet «Betal umiddelbart». Her kan man velge mellom kredittkort, direkte belastning og Sofortüberweisung.',
    'TCKLARNA_CHECKOUT'                                 => 'Klarna Checkout.',
    'TCKLARNA_CHECKOUT_START'                           => 'Den beste betalingsopplevelsen for kundene dine. Pålitelig kundeidentifisering og valg av fraktmåte. Alle betalinger inkludert. Tilgjengelig over hele verden, lokalt optimalisert. Vi påtar oss hele risikoen, og du får alltid pengene dine.',

    'TCKLARNA_RB_HOW_TO_ACTIVATE'                       => 'How-to-activate<br>Klarna guide.',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_ONE'              => 'Klikk på det nye menypunktet «Klarna» i OXID-backend, deretter på underkategorien «Generelt», og velg deretter det ønskede Klarna-produktet. Du kan velge mellom «Klarna Payments» og «Klarna Checkout».',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_TWO'              => 'Skriv inn påloggingsopplysningene dine (brukernavn og passord), og foreta de vanlige OXID-tilordningene for betalingsmåter under «Butikkinnstillinger» &gt; «Betalingsmåter» samt «Fraktmåter».',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_THREE'            => 'Lagre endringene.',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_FOUR'             => 'Du er nå online og kan begynne å selge med Klarna.',
    'TCKLARNA_RB_MERCHANT_SUPPORT'                      => 'Støtte for forhandlere',
    'TCKLARNA_DEVICE_IMG'                               => 'enhet.png',


    'TCKLARNA_EXTERNAL_PAYMENTS_ADMIN_DESC'             => 'Her kan du konfigurere eksterne betalingsmåter og eksterne kasseprosesser for integrering i Klarna Checkout-iframen. ',
    'TP11'                                              => 'For en detaljert beskrivelse av de ulike innstillingene, se verktøytipsene ',
    'TP12'                                              => '<i class="fa fa-question-circle-o" aria-hidden="true"></i>, les bruksanvisningen ',
    'TP13'                                              => 'eller ta kontakt med Klarnas integrasjonssupport.',
    'TCKLARNA_EXTRA_MERCHANT_DATA_ADMIN_DESC'           => 'Her kan du angi om eventuelle tilleggsopplysninger om forhandleren skal overføres til Klarna. ',
    'TP21'                                              => 'For en detaljert beskrivelse av de ulike innstillingene, se verktøytipsene ',
    'TP22'                                              => '<i class="fa fa-question-circle-o" aria-hidden="true"></i>, les bruksanvisningen ',
    'TP23'                                              => 'eller ta kontakt med Klarnas integrasjonssupport.',
    'TCKLARNA_DESIGN_SETTINGS_ADMIN_DESC'               => 'Her kan du konfigurere designinnstillingene for bruk med Klarna-modulen for OXID eShop. ',
    'TP31'                                              => 'For en detaljert beskrivelse av de ulike innstillingene, se verktøytipsene ',
    'TP32'                                              => '<i class="fa fa-question-circle-o" aria-hidden="true"></i>, les bruksanvisningen ',
    'TP33'                                              => 'eller ta kontakt med Klarnas integrasjonssupport.',
    'TCKLARNA_GENERAL_SETTINGS_ADMIN_DESC'              => 'Her kan du velge mellom Klarna Checkout og Klarna Payments og angi generelle innstillinger. ',
    'TP41'                                              => 'For en detaljert beskrivelse av de ulike innstillingene, se verktøytipsene ',
    'TP42'                                              => '<i class="fa fa-question-circle-o" aria-hidden="true"></i>, les bruksanvisningen ',
    'TP43'                                              => 'eller ta kontakt med Klarnas integrasjonssupport.',
    'TCKLARNA_CONFIGURATION_KCO_ADMIN_DESC'             => 'På denne siden kan du konfigurere de spesifikke innstillingene for Klarna Checkout. ',
    'TP51'                                              => 'For en detaljert beskrivelse av de ulike innstillingene, se verktøytipsene ',
    'TP52'                                              => '<i class="fa fa-question-circle-o" aria-hidden="true"></i>, les bruksanvisningen ',
    'TP53'                                              => 'eller ta kontakt med Klarnas integrasjonssupport.',
    'TCKLARNA_CONFIGURATION_KP_ADMIN_DESC'              => 'På denne siden velger du hvilke Klarna-betalingsmåter du ønsker å tilby. ',
    'TP61'                                              => 'For en detaljert beskrivelse av de ulike innstillingene, se verktøytipsene ',
    'TP62'                                              => '<i class="fa fa-question-circle-o" aria-hidden="true"></i>, les bruksanvisningen ',
    'TP63'                                              => 'eller ta kontakt med Klarnas integrasjonssupport.',

    'TCKLARNA_PAYMENT_METHOD'                           => 'Betalingsmåte',
    'TCKLARNA_EXTERNAL_PAYMENT_METHOD'                  => 'Ekstern betalingsmåte',
    'TCKLARNA_EXTERNAL_CHECKOUT'                        => 'Ekstern kasse',
    'TCKLARNA_IMAGE_URI_EXT_PAYMENT'                    => 'Bilde-URI for ekstern betalingsmåte',
    'TCKLARNA_IMAGE_URI_EXT_CHECKOUT'                   => 'Bilde-URI for ekstern kasse',
    'TCKLARNA_IMAGE_TIP_69x24'                          => 'Bildestørrelse: 69x24 piksler',
    'TCKLARNA_IMAGE_TIP_276x48'                         => 'Bildestørrelse: 276x48 piksler',
    'TCKLARNA_USER_GUIDE_DESCRIPTION'                   => 'Du kan lese brukerhåndboken for Klarna-modulen til OXID eShop her.',
    'TCKLARNA_USER_GUIDE_LINK'                          => 'https://wiki.fatchip.de/public/faqklarna',
    'TCKLARNA_USER_GUIDE_BUTTON'                        => 'Brukerhåndbok',

    'TCKLARNA_CHOOSE'                                   => 'Velg',

    'TCKLARNA_CUSTOMER_ACCOUNT_INFO'                    => 'Informasjon om kundekontoen',
    'TCKLARNA_PAYMENT_HISTORY_FULL'                     => 'Fullstendig betalingshistorikk',
    'TCKLARNA_PASSTHROUGH_FIELD'                        => 'Gjennomføringsfelt',

    'TCKLARNA_ASSIGN_PAYMENT_METHOD_TYPE'               => 'Tilordne betalingsmåte:',
    'TCKLARNA_WHICH_ORDERS_IN_FULL_PAYMENT_HISTORY'     => 'Hvilke bestillinger skal inkluderes i «Payment history full»?',
    'TCKLARNA_EMD_ORDER_HISTORY_ALL'                    => 'Alle bestillinger skal betraktes som betalt, uavhengig av oxpaid-datoen',
    'TCKLARNA_EMD_ORDER_HISTORY_PAID'                   => 'Send kun bestillinger med angitt oxpaid-dato; ignorér ubetalte bestillinger',
    'TCKLARNA_EMD_ORDER_HISTORY_NONE'                   => 'Ignorer alle bestillinger som er gjennomført med denne betalingsmåten',
    'TCKLARNA_OTHER_PAYMENT'                            => 'Andre betalingsalternativer',
    'TCKLARNA_DIRECT_BANKING'                           => 'Direkteoverføring',
    'TCKLARNA_CARD'                                     => 'Kart',

    'TCKLARNA_TEST_MODE_TOOLTIP'                        => 'Velg mellom «Playground» (testdrift) og «Live» (produksjonsdrift). Aktiver produksjonsdriften først etter at integrasjonstestene er gjennomført med godt resultat og etter avtale med din Klarna-integrasjonsansvarlig.',
    'TCKLARNA_GLOBAL_MERCHANT_ID_TOOLTIP'               => 'Vennligst oppgi dine Klarna API-påloggingsopplysninger her. Du har mottatt disse i velkomst-e-posten fra Klarna. Dette brukernavnet og passordet gjelder globalt for alle land. Kun dersom du har mottatt forskjellige påloggingsopplysninger for ulike land, kan du legge disse til lenger ned.',
    'TCKLARNA_GLOBAL_PASSWORD_TOOLTIP'                  => 'Skriv inn passordet ditt her, som skal stemme overens med API-brukernavnet du bruker. Du har mottatt dette passordet i velkomst-e-posten fra Klarna.',
    'TCKLARNA_GLOBAL_PORTAL_MERCHANT_ID_TOOLTIP'        => 'Vennligst oppgi din Klarna-forhandler-ID her. Du har mottatt denne i velkomst-e-posten fra Klarna.',
    'TCKLARNA_CREDENTIALS_COUNTRY_SELECTOR_TOOLTIP'     => 'Velg det landet du har mottatt landsspesifikke påloggingsopplysninger fra Klarna for, fra listen til venstre.',
    'TCKLARNA_CREDENTIALS_COUNTRY_MERCHANT_ID_TOOLTIP'  => 'Vennligst skriv inn brukernavnet for dette landet her.',
    'TCKLARNA_CREDENTIALS_COUNTRY_PASSWORD_TOOLTIP'     => 'Vennligst skriv inn passordet for dette landet her.',
    'TCKLARNA_CREDENTIALS_COUNTRY_PORTAL_MERCHANT_ID_TOOLTIP'=> 'Vennligst oppgi den tilhørende forhandler-ID-en for dette landet her.',
    'TCKLARNA_DEFAULT_COUNTRY_TOOLTIP'                  => 'Vennligst velg fra listen hvilket land Klarna Checkout skal lastes inn som standard, så lenge kunden ikke har oppgitt sitt land ennå.',
    'TCKLARNA_ENABLE_LOGGING_TOOLTIP'                   => 'Aktiverer loggfunksjonen, slik at all API-kommunikasjon med Klarna blir loggført i MySQL-tabellen tcklarna_logs. Dette kan være nyttig ved analyse eller feilsøking. I produksjonsdrift bør funksjonen være deaktivert, da det ellers kan oppstå store mengder loggdata og sensitive opplysninger kan bli lagret.',
    'TCKLARNA_SEND_PRODUCT_URLS_TOOLTIP'                => 'Send URL-adressene til produktdetaljsidene for varene som ligger i kundenes handlekurv til Klarna, slik at Klarna senere kan lenke til produktene dine fra Klarna-portalen.',
    'TCKLARNA_SEND_PRODUCT_IMAGES_TOOLTIP'              => 'Send URL-adressene til produktbildene for varene som ligger i kundenes handlekurv til Klarna, slik at Klarna kan vise dem i Klarna-portalen.',
    'TCKLARNA_ENABLE_ANONYMIZATION_TOOLTIP'             => 'Aktiver anonymiseringen for å skjule produktbetegnelsene på varene som ligger i kundenes handlekurv for Klarna. Dette anbefales for eksempel for nettapotek, men bør kun gjøres etter avtale med Klarna Integration Manager.',
    'TCKLARNA_ALLOW_SEPARATE_DELIVERY_ADDRESS_TOOLTIP'  => 'Hvis levering til en annen leveringsadresse skal være mulig, må du aktivere denne bryteren.',
    'TCKLARNA_MANDATORY_PHONE_TOOLTIP'                  => 'Hvis du ønsker å gjøre det obligatorisk å oppgi et telefonnummer, må du aktivere denne bryteren. Normalt er telefonnummeret ikke et obligatorisk felt for Klarna.',
    'TCKLARNA_MANDATORY_BIRTH_DATE_TOOLTIP'             => 'Hvis du ønsker å gjøre det obligatorisk å oppgi fødselsdato, må du aktivere denne bryteren. Normalt er fødselsdato ikke et obligatorisk felt hos Klarna. Opplysningen er imidlertid nødvendig for å kunne tilby kjøp på faktura eller avbetaling.',
    'TCKLARNA_ENABLE_AUTOFOCUS_TOOLTIP'                 => 'Ved hjelp av denne bryteren kan du aktivere at Klarna-iframe automatisk får fokus når siden med Klarna Checkout lastes inn.',
    'TCKLARNA_CHECKBOX_TOOLTIP'                         => 'Det er mulig å aktivere en ekstra avkryssingsrute innenfor Klarna Checkout-iframen for å tilby kunden å opprette en kundekonto, melde seg på nyhetsbrevet ditt, eller begge deler. Dersom kunden allerede har en kundekonto eller allerede er registrert for nyhetsbrevet når avmerkingsboksen er aktivert, vil teksten i avmerkingsboksen automatisk tilpasses, eller avmerkingsboksen vil eventuelt skjules helt.',
    'TCKLARNA_VALIDATION_TOOLTIP'                       => 'Her kan du aktivere en ekstra sjekk av handlekurven, som ved innsending av bestillingen via Klarna Checkout på nytt kontrollerer tilgjengeligheten av de ønskede varene for å unngå feil som følge av oversalg. Modusen «Krevende vellykket validering» anbefales.',
    'TCKLARNA_SALUTATION_MANDATORY_TOOLTIP'             => 'Denne innstillingen gjelder utelukkende Klarna Checkout-skjemaet for Storbritannia: Skal det være obligatorisk å oppgi tiltaleform?',
    'TCKLARNA_ENABLE_DHL_PACKSTATIONS_TOOLTIP'          => 'Foreløpig ikke implementert',
    'TCKLARNA_ENABLE_PRE_FILLING_TOOLTIP'               => 'Aktiver automatisk utfylling av Klarna Checkout-iframen med opplysningene til kunden som er logget inn i OXID eShop',
    'TCKLARNA_ENABLE_PREFILL_NOTIFICATION_TOOLTIP'      => 'Hvis den automatiske utfyllingen av Klarna Checkout-iframen er aktivert, må det for enkelte land vises en tilsvarende personvernerklæring. Denne erklæringen aktiveres ved hjelp av denne bryteren.',
    'TCKLARNA_TERMS_AND_CONDITIONS_URL_TOOLTIP'         => 'Oppgi URL-adressen til dine generelle forretningsvilkår her. Disse vil bli lenket til i Klarna Checkout-iframe. Du må oppgi en gyldig URL-adresse som begynner med https://.',
    'TCKLARNA_CANCELLATION_RIGHTS_URL_TOOLTIP'          => 'Oppgi her nettadressen til nettsiden din med informasjon om angreretten. Nettadressen må begynne med https://.',
    'TCKLARNA_SHIPPING_DETAILS_TOOLTIP'                 => 'Disse leveringsopplysningene vises for kunden på takkesiden etter at bestillingen er fullført.',
    'TCKLARNA_EXTERNAL_PAYMENT_NAME_SELECT_TOOLTIP'     => 'Tilordne denne eksterne betalingsmåten til en av de forhåndsdefinerte betalingsmåtene',
    'TCKLARNA_ENABLE_EXTERNAL_PAYMENT_TOOLTIP'          => 'Med denne bryteren aktiverer du denne betalingsmåten som en ekstern betalingsmåte for Klarna Checkout. Når den er aktivert, kan kunden velge denne betalingsmåten fra listen over betalingsmåter i Klarna Checkout-iframe.',
    'TCKLARNA_ENABLE_EXTERNAL_CHECKOUT_TOOLTIP'         => 'Med denne bryteren aktiverer du denne betalingsmåten som ekstern kasse. Når den er aktivert, vises denne betalingsmåten helt nederst i Klarna-kasse-iframe-vinduet, allerede før kundedataene legges inn.',
    'TCKLARNA_EXTERNAL_PAYMENT_IMAGE_URL_TOOLTIP'       => 'Angi her URL-adressen til et bilde som skal vises ved siden av betalingsmåten i Klarna Checkout-iframe. Det anbefales å bruke et bilde fra en sikker URL som begynner med https://.',
    'TCKLARNA_EXTERNAL_CHECKOUT_IMAGE_URL_TOOLTIP'      => 'Angi her URL-adressen til et bilde som skal vises som en knapp for denne betalingsmåten i Klarna Checkout-iframen nederst på siden. Det anbefales å bruke et bilde fra en sikker URL som begynner med https://.',
    'TCKLARNA_EXTERNAL_IMAGE_URL_EMPTY'                 => 'Vennligst oppgi en URL for alle språk',
    'TCKLARNA_EXTERNAL_IMAGE_URL_INVALID'               => 'Vennligst oppgi en gyldig URL som begynner med https://',
    'TCKLARNA_EMD_CUSTOMER_INFO_TOOLTIP'                => 'Denne bryteren aktiverer overføring av tilleggsdata til Klarna, i dette tilfellet kundekontoinformasjonen, som inneholder datoen for registrering av kundekontoen og datoen for den siste endringen.',
    'TCKLARNA_EMD_PAYMENT_HISTORY_FULL_TOOLTIP'         => 'Denne bryteren aktiverer overføring av tilleggsdata til Klarna, i dette tilfellet «Payment History Full», som inneholder kundens tidligere kjøp.',
    'TCKLARNA_EMD_PAYMENT_TYPE_TOOLTIP'                 => 'Vennligst velg hvilken type betalingsmåte denne betalingsmetoden tilhører.',
    'TCKLARNA_EMD_HISTORY_FULL_TOOLTIP'                 => 'Angi her om, og i så fall hvilke, bestillinger med denne betalingsmåten som skal inkluderes når kundens bestillingshistorikk overføres. Avhengigheten til feltet OXORDER.OXPAID angir om kun betalte bestillinger eller alle bestillinger skal tas med.',
    'TCKLARNA_EMD_PASSTHROUGH_FIELD_TOOLTIP'            => 'Det er mulig å overføre ytterligere data til Klarna ved hjelp av et «pass-through»-felt. For å kunne bruke denne funksjonen må du installere en passende modul i OXID eShop som skriver de ønskede dataene inn i «pass-through»-feltet. Du finner en veiledning om dette i utviklerdokumentasjonen.',
    'TCKLARNA_DISPLAY_ON_HOME_TOOLTIP'                  => 'Med denne bryteren aktiverer du et Klarna-banner på startsiden til nettbutikken din i standardtemaene Flow og Wave.',
    'TCKLARNA_BANNER_SRC_TOOLTIP'                       => 'Her kan du legge inn script-taggen for å integrere banneret. I Klarnas bannerportal finner du eventuelt flere bannere å velge mellom.',
    'TCKLARNA_FOOTER_PAYMENT_METHODS_TOOLTIP'           => 'Med denne bryteren aktiverer du Klarna-betalingsmetodevisningen i bunnteksten på nettbutikken din i standardtemaene Flow og Wave.',
    'TCKLARNA_FOOTER_KLARNA_LOGO_TOOLTIP'               => 'Med denne bryteren kan du legge inn Klarna-logoen i bunnteksten på nettbutikken din i standardtemaene Flow og Wave.',
    'TCKLARNA_BUY_NOW_ON_BASKET_TOOLTIP'                => 'Denne bryteren legger til en «Klarna Express Checkout»-knapp på handlekurvsiden i nettbutikken din i standardtemaene.',
    'TCKLARNA_BUY_NOW_ON_PROD_PAGE_TOOLTIP'             => 'Denne bryteren legger til en «Klarna Express Checkout»-knapp på varedetaljsidene i nettbutikken din i standardtemaene.',
    'TCKLARNA_KEB_CLID_TOOLTIP'                         => 'For å kunne bruke Klarna Express Checkout må Klarna Express Checkout aktiveres i Klarna-portalen under fanen «Conversion boosters». Når opplysningene er lagt inn, kan klient-ID-en kopieres inn i dette feltet.',
    'TCKLARNA_BORDER_TOOLTIP'                           => 'Fargen på rammen som vises i nettbutikkens brukergrensesnitt når man velger Klarna som betalingsmåte, avhengig av hvilke underalternativer som er tilgjengelige.',
    'TCKLARNA_BORDER_SELECTED_TOOLTIP'                  => 'Fargen på rammen som vises i nettbutikkens frontend når man velger Klarna som betalingsmåte, dersom det finnes ulike underalternativer. Denne fargen brukes til å markere det underalternativet som for øyeblikket er aktivt valgt.',
    'TCKLARNA_BUTTON_TOOLTIP'                           => 'Denne innstillingen har ingen virkning på tidspunktet for utgivelsen av dette modulen.',
    'TCKLARNA_BUTTON_TEXT_TOOLTIP'                      => 'Denne innstillingen har ingen virkning på tidspunktet for utgivelsen av dette modulen.',
    'TCKLARNA_DESIGN_CHECKBOX_TOOLTIP'                  => 'Bakgrunnsfargen på radioknappene som vises i butikkens brukergrensesnitt når man velger betalingsmåten Klarna, dersom det finnes flere underalternativer',
    'TCKLARNA_DESIGN_CHECKBOX_CHECKMARK_TOOLTIP'        => 'Denne innstillingen har ingen virkning på tidspunktet for utgivelsen av dette modulen.',
    'TCKLARNA_DETAILS_TOOLTIP'                          => 'Fargen på opptellingstegnene når betalingsdetaljene vises på siden for valg av betalingsmåte.',
    'TCKLARNA_HEADER_TOOLTIP'                           => 'Denne innstillingen har ingen virkning på tidspunktet for utgivelsen av dette modulen.',
    'TCKLARNA_LINK_TOOLTIP'                             => 'Fargen på lenkene i detaljbeskrivelsen av betalingsmåtene på siden for valg av betalingsmåte.',
    'TCKLARNA_TEXT_TOOLTIP'                             => 'Tekstfarge for detaljbeskrivelsen av betalingsmåtene på siden for valg av betalingsmåte.',
    'TCKLARNA_SECONDARY_TEXT_TOOLTIP'                   => 'Alternativ tekstfarge for detaljbeskrivelsen av betalingsmåtene på siden for valg av betalingsmåte.',
    'TCKLARNA_BORDER_RADIUS_TOOLTIP'                    => 'Med denne innstillingen kan du angi hvor avrundet rammen skal være, som vises i butikkens brukergrensesnitt når du velger betalingsmåten Klarna, avhengig av hvilke underalternativer som er tilgjengelige.',

    'KLARNA_ONLY_FOR_KLARNA_PAYMENT'                    => 'Denne fanen gjelder kun bestillinger via Klarna',
    'KLARNA_CAPTURE_FULL_ORDER'                         => 'Registrere hele bestillingen',
    'KLARNA_CAPTURE_ID'                                 => 'Trekk-ID',
    'KLARNA_CAPTURE_REFERENCE'                          => 'Klarna-referanse',
    'KLARNA_CAPTURE_AMOUNT'                             => 'Beløp som trekkes',
    'KLARNA_CAPTURE_DATE'                               => 'Belastet den',
    'KLARNA_REFUND_AMOUNT'                              => 'Refusjonsbeløp',
    'KLARNA_REFUND_DESCRIPTION'                         => 'Refusjon – Forklaring',
    'KLARNA_REFUND_DATE'                                => 'Erstattet am',
    'KLARNA_CAPTURES'                                   => 'Trekk',
    'KLARNA_REFUNDS'                                    => 'Refusjoner',
    'KLARNA_CANCEL_ORDER'                               => 'Avbestille bestillingen',
    'KLARNA_ORDER_IS_CANCELLED'                         => 'Bestillingen ble kansellert. ',
    'KLARNA_SEE_ORDER_IN_PORTAL'                        => '<a href="%s" target="_blank" class="alert-link">Diese Bestellung im Klarna Portal aufrufen</a>',
    'KLARNA_ORDER_NOT_IN_SYNC'                          => '<strong>Oppmerksomhet!</strong> Opplysningene i denne bestillingen avviker fra opplysningene som er lagret hos Klarna. ',
    'TCKLARNA_ORDER_UPDATE_CANT_BE_SENT_TO_KLARNA'      => 'Oppmerksomhet! På grunn av den nåværende ordrestatusen kan denne endringen ikke sendes til Klarna. Utfør eventuelt den aktuelle endringen manuelt direkte i Klarna Merchant Portal.',
    'TCKLARNA_ORDER_UPDATE_REJECTED_BY_KLARNA'          => 'Oppmerksomhet! Klarna har ikke kunnet behandle de siste endringene du har gjort i denne bestillingen (årsak: %s). Vennligst tilbakestill de siste endringene i OXID eShop, eller foreta den nødvendige justeringen manuelt i Klarna Merchant Portal om nødvendig.',
    'KLARNA_UNAUTHORIZED_REQUEST'                       => 'Ugyldig forespørsel. Kontroller innstillingene for Klarna-modulen, Merchant-ID-en og det tilhørende passordet',
    'KLARNA_ORDER_NOT_FOUND'                            => 'Denne bestillingen ble ikke funnet i Klarnas system. Endringer i bestillingsopplysningene vil derfor ikke bli overført til Klarna.',
    'KLARNA_MID_CHANGED_FOR_COUNTRY'                    => '<strong>Feil påloggingsopplysninger!</strong> Denne bestillingen ble lagt inn med forhandler-ID-en <strong>%s</strong>. Den forhandler-ID-en som for øyeblikket er konfigurert for <strong>%s</strong>, er <strong>%s</strong>.',
    'TCKLARNA_PRODUCT_NAME'                             => 'Produktnavn',
    'TCKLARNA_ANONYMIZED_PRODUCT'                       => 'Anonymisert produkttittel:',
    'TCKLARNA_KCO_INVOICE_MSG'                          => 'Betalingen håndteres av vår samarbeidspartner Klarna. Vennligst følg betalingsinformasjonen du har mottatt fra Klarna dersom du ennå ikke har betalt for kjøpet. Du kan administrere alle kjøpene dine via Klarna.com eller Klarna-appen, og til og med betale med bare ett klikk.',
    'TCKLARNA_KP_INVOICE_MSG'                           => 'Betalingen håndteres av vår samarbeidspartner Klarna. Vennligst følg betalingsinformasjonen du har mottatt fra Klarna. Du kan administrere alle kjøpene dine via Klarna.com eller Klarna-appen, og til og med betale med bare ett klikk.',
    'TCKLARNA_VOUCHER_DISCOUNT'                         => 'Rabattkupong',

    'TCKLARNA_KCO_BUTTON_TOOLTIP'                       => 'Bakgrunnsfargen på betalingsknappen inne i Klarna Checkout-iframen.',
    'TCKLARNA_KCO_BUTTON_TEXT_TOOLTIP'                  => 'Fargen på teksten på betalingsknappen i Klarna Checkout-iframe.',
    'TCKLARNA_KCO_DESIGN_CHECKBOX_TOOLTIP'              => 'Bakgrunnsfargen på avmerkingsboksene i Klarna Checkout-iframen.',
    'TCKLARNA_KCO_DESIGN_CHECKBOX_CHECKMARK_TOOLTIP'    => 'Fargen på avmerkingsboksen i avmerkingsboksene innenfor Klarna Checkout-iframen.',
    'TCKLARNA_KCO_HEADER_TOOLTIP'                       => 'Farge på overskrifter/titler innenfor Klarna Checkout-iframen.',
    'TCKLARNA_KCO_LINK_TOOLTIP'                         => 'Fargen på lenkene i Klarna Checkout-iframen.',
    'TCKLARNA_KCO_BORDER_RADIUS_TOOLTIP'                => 'Med denne innstillingen kan du angi hvor avrundet rammen rundt Klarna Checkout-iframen skal være.',

    'TCKLARNA_GIFT_WRAPPING_TITLE'                      => 'Gaveinnpakning',
    'TCKLARNA_GIFT_CARD_TITLE'                          => 'Gratulasjonskort',

    'TCKLARNA_ERROR_SHOP_SSL_NOT_CONFIGURED'            => 'Alvorlig feil: Det er obligatorisk å oppgi en gyldig SSL-beskyttet (https) $this->sSSLShopURL i config.inc.php-filen til nettbutikken din hvis du ønsker å aktivere %s!',
    'TCKLARNA_ERROR_WRONG_CREDS'                        => '<strong>Feil påloggingsopplysninger!</strong>',
    'TCKLARNA_ERROR_KCO_INACTIVE'                       => 'Konfigurasjonsfeil: Klarna Checkout er ikke aktivert i nettbutikken',

    'KLARNA_CAPTURE_SUCCESSFULL'                        => 'Beløpet er trukket fra kontoen.',
    'TCKLARNA_CAPUTRE_FAIL_ORDER_CANCELLED'             => ' Betalingen for bestillingen kunne ikke trekkes, siden den allerede var kansellert.',
    'TCKLARNA_ANONYMIZED_PRODUCT_TOOLTIP'               => 'Skriv inn tekststrengen her som skal sendes til Klarna i stedet for den faktiske produkttittelen.',
    'TCKLARNA_NO_REQUESTS_WILL_BE_SENT'                 => 'Endringene du gjør i denne bestillingen blir ikke overført til Klarna.',
    'TCKLARNA_USER_GUIDE'                               => 'Brukerhåndbok',
    'TCKLARNA_REGISTER_NOW_BUTTON'                      => 'Registrer deg',
    'TCKLARNA_LEARN_MORE_BUTTON'                        => 'Les mer',

    'TCKLARNA_CUSTOMER_TYPE'                            => 'Støttede kundetyper',
    'TCKLARNA_CUSTOMER_TYPE_TOOLTIP'                    => 'Hier können Sie einstellen, ob der Shop ausschließlich B2C Transaktionen (Standard-Einstellung). nur B2B Transaktionen oder sowohl B2C als auch B2B Transaktionen akzeptieren soll. <br> Hinweis: Nach dem Umstellen der Kundenarten muss der Session cache des Browsers gelöscht werden, damit die Bezahlung getestet werden kann.',
    'TCKLARNA_B2C'                                      => 'Kun B2C-kunder',
    'TCKLARNA_B2B'                                      => 'Kun B2B-kunder',
    'TCKLARNA_B2B_B2C'                                  => 'Hovedsakelig B2B-kunder, men også B2C-kunder',
    'TCKLARNA_B2C_B2B'                                  => 'Hovedsakelig B2C-kunder, men også B2B-kunder',
    'TCKLARNA_NEED_SUPPORT'                             => 'Trenger du hjelp med integrasjonen?',
    'TCKLARNA_REACH_SUPPORT'                            => 'Ta kontakt med Klarnas kundestøtte for forhandlere',

    'TCKLARNA_EU_WARNING'                               => '<p>For å være i samsvar med EUs geoblokkeringsforordning anbefales det på det sterkeste å aktivere alle europeiske land og tilordne dem betalingsmetoden Klarna Checkout.</p><p>Følgende land mangler: %s</p>',

    'TCKLARNA_ON_SITE_MESSAGING'                        => 'Meldinger på stedet',
    'TCKLARNA_ON_SITE_MESSAGING_ADMIN_DESC'             => 'Her kan du konfigurere On-Site Messaging for bruk sammen med Klarna-modulen for OXID eShop.',
    'TCKLARNA_ON_SITE_MESSAGING_SCRIPT'                 => 'Manus',
    'TCKLARNA_CREDIT_PROMOTION_PRODUCT'                 => 'Credit Promotion – Produktdetaljsiden',
    'TCKLARNA_CREDIT_PROMOTION_BASKET'                  => 'Kredittkampanje Handlekurv',
    'TCKLARNA_TOP_STRIP_PROMOTION'                      => 'Kampanje på toppstripen',
    'TCKLARNA_FOOTER_PROMOTION'                         => 'Kampanje i bunnteksten',
    'TCKLARNA_BANNER_PROMOTION'                         => 'Banner-kampanje',
    'TCKLARNA_ON_SITE_MESSAGING_SCRIPT_TOOLTIP'         => 'Vennligst sett inn JavaScript-bibliotekets kodebit her, som er nødvendig for On-Site Messaging, og som du finner i Klarna Merchant Portal.',
    'TCKLARNA_CREDIT_PROMOTION_PRODUCT_TOOLTIP'         => 'Vennligst sett inn plasseringskoden her for å markedsføre finansiering og avbetalingskjøp gjennom Credit Promotions på produktdetaljsiden',
    'TCKLARNA_CREDIT_PROMOTION_BASKET_TOOLTIP'          => 'Vennligst sett inn «Placement Tag» her for å markedsføre finansiering og avbetalingskjøp gjennom Credit Promotions på oversikten over handlekurven',
    'TCKLARNA_TOP_STRIP_PROMOTION_TOOLTIP'              => 'Vennligst sett inn plasseringskoden her for å fremheve generell informasjon og informasjon om betalingsmåter på nettbutikkens startside',
    'TCKLARNA_FOOTER_PROMOTION_TOOLTIP'                 => 'Vennligst sett inn Placement-taggen her for å vise de tilgjengelige Klarna-betalingsmåtene i bunnteksten på nettbutikken',
    'TCKLARNA_BANNER_PROMOTION_TOOLTIP'                 => 'Vennligst sett inn plasseringskoden her for å legge inn et banner på butikkens startside',
    'TCKLARNA_ON_SITE_MESSAGING_HEADER_TITLE'           => 'Hva er On-Site Messaging?',
    'TCKLARNA_ON_SITE_MESSAGING_HEADER_DESC'            => 'Kundene er ikke alltid klar over de ulike kreditt- og finansieringsmulighetene som står til deres disposisjon før de kommer til kassen. Finansieringsmuligheter som tilbys på et tidlig tidspunkt, påvirker kjøpsbeslutningen.',

    'TCKLARNA_ON_SITE_MESSAGING_HEADER_DESC_TPK0'       => 'On-Site Messaging er enkelt og problemfritt å integrere og tilbyr skreddersydd informasjon, alt fra generelle bannere som fremhever samarbeidet med Klarna og muligheten for delbetaling, til personlige kredittilbud på produkt- eller handlekurvssider.',
    'TCKLARNA_ON_SITE_MESSAGING_HEADER_DESC_2'          => 'Weitere Informationen zu den ersten Schritten <a class="cl-pink" href="https://docs.klarna.com/conversion-boosters/on-site-messaging/before-you-start/" target="_blank" rel=”noopener”>finden Sie hier</a><br><br>',
    'TCKLARNA_ON_SITE_MESSAGING_HEADER_DESC_2_TPK1'     => 'Melden Sie sich im <a class="cl-pink" href="https://merchants.klarna.com/" target="_blank">Händlerportal</a> an, um Ihren persönlichen JavaScript- und Placement-Code zu generieren. On-Site-Messaging wird in Ihrem Shop aktiviert, sobald der JavaScript-Code gespeichert und mindestens ein Placement-Code eingegeben wurde.<br>',
    'TCKLARNA_ON_SITE_MESSAGING_HEADER_DESC_2_TPK2'     => 'Du kan når som helst deaktivere den ved å fjerne kodene igjen.',
    'TCKLARNA_ON_SITE_MESSAGING_MERCHANT_BUTTON'        => 'Forhandlerportal',

    'TCKLARNA_IS_ENABLED_HEADLINE'                      => 'Aktiver Klarna Instant Shopping',
    'TCKLARNA_IS_ENABLED'                               => 'Aktiv',
    'TCKLARNA_IS_BUTTON_REPLACE'                        => 'Skifte ut knappen «Key»',
    'TCKLARNA_IS_REPLACE'                               => 'Opprett en ny knapp «Key»',
    'TCKLARNA_IS_BUTTON_REPLACE_TOOLTIP'                => 'Du kan oppdatere Button Key hvis konfigurasjons- eller identifikasjonsdataene fra Klarna krever en endring. Normalt kan du bruke en Button Key så lenge du ønsker, etter at den er opprettet.',
    'TCKLARNA_IS_ENABLED_TOOLTIP'                       => 'Aktiver Klarna Instant Shopping her. Da opprettes det automatisk en knapp som kan brukes i nettbutikkens frontend.',
    'TCKLARNA_IS_BUTTON_APEARANCE_HEADLINE'             => 'Innstillinger for utforming av knapper',
    'TCKLARNA_IS_VARIATION_TOOLTIP'                     => 'Vennligst velg mellom en knapp som er fullstendig merket med Klarna-designet og en mer nøytral «Light»-variant.',
    'TCKLARNA_IS_TAGLINE_TOOLTIP'                       => 'Vennligst velg om skriftfargen på slagordet under knappen skal være lys eller mørk.',
    'TCKLARNA_IS_TYPE_TOOLTIP'                          => 'Vennligst velg ønsket tekst på knappen.',
    'TCKLARNA_IS_BUTTON_PREVIEW'                        => 'Forhåndsvisning av knappen',
    'TCKLARNA_IS_BUTTON_PLACEMENT_DETAILS'              => 'Vis på artikkeloversikten',
    'TCKLARNA_IS_BUTTON_PLACEMENT_DETAILS_TOOLTIP'      => 'Aktiver denne funksjonen for at Klarna Instant Shopping-knappen skal vises på alle produktdetaljsidene i nettbutikken din.',
    'TCKLARNA_IS_BUTTON_PLACEMENT_BASKET'               => 'Vis i handlekurven',
    'TCKLARNA_IS_BUTTON_PLACEMENT_BASKET_TOOLTIP'       => 'Aktiver denne funksjonen for at Klarna Instant Shopping-knappen skal vises i handlekurvoversikten i nettbutikken din.',
    'TCKLARNA_IS_BUTTON_SETTINGS_HEADLINE'              => 'Flere innstillinger for Instant Shopping',
    'TCKLARNA_IS_SETTING_ALLOW_SEPARATE_SHIPPING_ADDRESS'=> 'Leveringsadressen kan avvike fra fakturaadressen',
    'TCKLARNA_IS_SETTING_ALLOW_SEPARATE_SHIPPING_ADDRESS_TOOLTIP'=> 'Hvis levering til en annen leveringsadresse skal være mulig, må du aktivere denne bryteren.',
    'TCKLARNA_IS_SETTING_DATE_OF_BIRTH_MANDATORY'       => 'Fødselsdato som obligatorisk felt',
    'TCKLARNA_IS_SETTING_DATE_OF_BIRTH_MANDATORY_TOOLTIP'=> 'Hvis du ønsker å gjøre det obligatorisk å oppgi fødselsdato, må du aktivere denne bryteren. Normalt er fødselsdato ikke et obligatorisk felt hos Klarna. Opplysningen er imidlertid nødvendig for å kunne gjennomføre kjøp på faktura eller avbetaling.',
    'TCKLARNA_IS_SETTING_NATIONAL_IDENTIFICATION_NUMBER_MANDATORY'=> 'Nasjonalt ID-nummer som obligatorisk felt',
    'TCKLARNA_IS_SETTING_NATIONAL_IDENTIFICATION_NUMBER_MANDATORY_TOOLTIP'=> 'Vennligst velg om det nasjonale identifikasjonsnummeret skal være et obligatorisk felt.',
    'TCKLARNA_IS_BUTTON_SETTINGS_VARIATION'             => 'Variasjon',
    'TCKLARNA_IS_BUTTON_SETTINGS_TAGLINE'               => 'Slagord',
    'TCKLARNA_IS_BUTTON_SETTINGS_TYPE'                  => 'Type',
    'TCKLARNA_IS_SETTING_PHONE_MANDATORY'               => 'Telefonnummer er et obligatorisk felt',
    'TCKLARNA_IS_SETTING_PHONE_MANDATORY_TOOLTIP'       => 'Vennligst velg om telefonnummeret skal være et obligatorisk felt.',
    'TCKLARNA_IS_DEFAULT_COUNTRY_TIP'                   => 'Vennligst velg fra listen hvilket land som skal være standardvalg når Klarna Instant Shopping åpnes, så lenge kunden ikke har oppgitt sitt land ennå.',
    'TCKLARNA_IS_TERMS_URI_TIP'                         => 'Oppgi URL-adressen til dine generelle vilkår her. Disse vil bli lenket til i Klarna Instant Shopping-popup-vinduet. Du må oppgi en gyldig URL-adresse som begynner med https://.',

    'TCKLARNA_SHIPPING_KCO'                             => 'Tildeling av leveringsmåter for Klarna Checkout og Klarna Express',
    'TCKLARNA_SHIPPING_KCO_DESC'                        => 'Vennligst tilordne de tilsvarende Klarna-betegnelsene til de fraktmåtene du har definert. Gjennom denne tilordningen kan du blant annet konfigurere levering til pakkestasjoner.',
    'TCKLARNA_SHIPPING_SETTINGS'                        => 'Fraktalternativer',
    'TCKLARNA_COMPLETE_REFUND'                          => 'Krediter hele bestillingen',
    'TCKLARNA_PACKSTATION_NO_SHIPPING_SET'              => 'Det ble ikke funnet noen aktive leveringsmåter',

    'TCKLARNA_AUTHPAYMENTMETHOD'                        => 'Brukt betalingsmåte: ',
    'TCKLARNA_AUTHPAYMENTMETHOD_unknown'                => 'Klarna',
    'TCKLARNA_AUTHPAYMENTMETHOD_direct_debit'           => 'Direktebelastning',
    'TCKLARNA_AUTHPAYMENTMETHOD_direct_bank_transfer'   => 'Direkteoverføring',
    'TCKLARNA_AUTHPAYMENTMETHOD_slice_it_by_card'       => '3 rentefrie avdrag',
    'TCKLARNA_AUTHPAYMENTMETHOD_fixed_sum_credit'       => 'Finansiering',
    'TCKLARNA_AUTHPAYMENTMETHOD_b2b_invoice'            => 'B2B-faktura (Billie)',
    'TCKLARNA_AUTHPAYMENTMETHOD_pay_later_by_card'      => 'Kortbetaling innen 30 dager',
    'TCKLARNA_AUTHPAYMENTMETHOD_invoice'                => 'Faktura',
    'TCKLARNA_AUTHPAYMENTMETHOD_pay_by_card'            => 'Kredittkort',
    'TCKLARNA_AUTHPAYMENTMETHOD_bank_transfer'          => 'Bankoverføring',
    'TCKLARNA_AUTHPAYMENTMETHOD_card'                   => 'Kredittkort',
    'TCKLARNA_AUTHPAYMENTMETHOD_fixed_amount'           => 'Finansiering',
    'TCKLARNA_AUTHPAYMENTMETHOD_invoice_business'       => 'B2B-faktura (Billie)',
    'TCKLARNA_AUTHPAYMENTMETHOD_mobilepay'              => 'MobilePay',
    'TCKLARNA_AUTHPAYMENTMETHOD_pay_later_in_parts'     => 'Klarna – Betal senere i delbetalinger',
    'TCKLARNA_AUTHPAYMENTMETHOD_swish'                  => 'Swish',
    'TCKLARNA_AUTHPAYMENTMETHOD_apple_pay_card'         => 'Apple Pay',
    'TCKLARNA_AUTHPAYMENTMETHOD_google_pay_card'        => 'Google Pay',
    'TCKLARNA_AUTHPAYMENTMETHOD_cartes_bancaires'       => 'Bankkort',
    'TCKLARNA_AUTHPAYMENTMETHOD_blik'                   => 'BLIK',
    'TCKLARNA_AUTHPAYMENTMETHOD_twint'                  => 'TWINT',
    'TCKLARNA_AUTHPAYMENTMETHOD_bancontact'             => 'Bancontact',
    'TCKLARNA_AUTHPAYMENTMETHOD_diners'                 => 'Kredittkort',
    'TCKLARNA_AUTHPAYMENTMETHOD_discover'               => 'Kredittkort',
    'TCKLARNA_AUTHPAYMENTMETHOD_elo'                    => 'Kredittkort',
    'TCKLARNA_AUTHPAYMENTMETHOD_jcb'                    => 'Kredittkort',
    'TCKLARNA_AUTHPAYMENTMETHOD_union_pay'              => 'Kredittkort',
    'TCKLARNA_AUTHPAYMENTMETHOD_pay_by_bank'            => 'Betal via bank',
    'TCKLARNA_AUTHPAYMENTMETHOD_other'                  => 'Brukerdefinert kasse',
);
