<?php
/**
 * Copyright 2018 Klarna AB
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$sLangName = "Polski";
// -------------------------------
// RESOURCE IDENTITFIER = STRING
// -------------------------------
$aLang = array(
    'charset'                                           => 'UTF-8',

    'TCKLARNA_KLARNAMAINMENU'                           => 'Klarna',
    'TCKLARNA_START'                                    => 'Start',
    'TCKLARNA_GENERAL_SETTINGS'                         => 'Ogólne informacje',
    'TCKLARNA_CONFIGURATION'                            => 'Konfiguracja',
    'TCKLARNA_CONFIGURATION_KCO'                        => 'Konfiguracja usługi Klarna Checkout',
    'TCKLARNA_CONFIGURATION_KP'                         => 'Konfiguracja płatności Klarna',
    'TCKLARNA_KLARNADESIGN'                             => 'Ustawienia wyglądu',
    'TCKLARNA_EXTERNAL_PAYMENTS'                        => 'Zewnętrzne metody płatności',
    'TCKLARNA_EXTRA_MERCHANT_DATA'                      => 'Dodatkowe dane dotyczące sprzedawcy',
    'TCKLARNA_BASIC_SETTINGS'                           => 'Ustawienia podstawowe',
    'TCKLARNA_DISCOUNT_TITLE'                           => 'Zniżka',

    'tcklarna_tbclklarna_orders'                        => 'Klarna',
    'TCKLARNA_NO_OPTIONS_MODE'                          => 'W tym trybie nie ma żadnych ustawień.',
    'TCKLARNA_CHANGES_SAVED'                            => 'Wszystkie ustawienia zostały zapisane.',
    'TCKLARNA_EMPTY_FIELDS_WARRNING'                    => 'Jeśli pola adresu URL pozostaną puste, może to spowodować nieprawidłowe działanie modułu.',

    'TCKLARNA_EASY'                                     => 'Aktywacja Klarna jest tak prosta',
    'TCKLARNA_PHONE'                                    => 'Telefon',
    'TCKLARNA_EMAIL'                                    => 'E-mail',
    'TCKLARNA_BUSINESS_HOURS'                           => 'Godziny otwarcia',
    'TCKLARNA_MONDAY'                                   => 'poniedziałek',
    'TCKLARNA_TUESDAY'                                  => 'wtorek',
    'TCKLARNA_WEDNESDAY'                                => 'Środa',
    'TCKLARNA_THURSDAY'                                 => 'czwartek',
    'TCKLARNA_FRIDAY'                                   => 'piątek',
    'TCKLARNA_SATURDAY'                                 => 'sobota',
    'TCKLARNA_SUNDAY'                                   => 'niedziela',
    'TCKLARNA_YOUR_COUNTRY_SPECIFIC_CREDS'              => 'Dane dostępowe dla poszczególnych krajów',
    'TCKLARNA_ADD_COUNTRY_SPECIFIC_CREDS'               => 'Dodaj dane dostępowe dla poszczególnych krajów',
    'TCKLARNA_COUNTRY'                                  => 'Kraj',
    'TCKLARNA_MERCHANT_ID'                              => 'Nazwa użytkownika API',
    'TCKLARNA_PASSWORD'                                 => 'Hasło API',
    'TCKLARNA_PORTAL_MERCHANT_ID'                       => 'Identyfikator sprzedawcy',
    'TCKLARNA_DEFAULT_SHOP_COUNTRY'                     => 'Domyślny kraj sklepu',
    'TCKLARNA_ENABLE_LOGGING'                           => 'Rejestracja aktywna',
    'TCKLARNA_SEND_ADDITIONAL_PRODUCT_DATA'             => 'Czy przesłać rozszerzone dane produktu do Klarna?',
    'TCKLARNA_PRODUCT_URLS'                             => 'Adresy URL produktów',
    'TCKLARNA_IMAGE_URLS'                               => 'Adresy URL obrazów',
    'TCKLARNA_ENABLE_ANONYMIZATION'                     => 'Anonimizacja',
    'TCKLARNA_ADD'                                      => 'Dodaj',


    'TCKLARNA_CHECKOUT_NAME'                            => 'Klarna Checkout',
    'TCKLARNA_PAYMENTS_NAME'                            => 'Płatności Klarna',
    'TCKLARNA_CHOOSE_KLARNA_MODULE_MODE'                => 'Wybierz tryb działania modułu Klarna',

    'TCKLARNA_CHECKOUT_DESC'                            => 'To kompleksowe rozwiązanie obejmuje wszystkie najważniejsze metody płatności (faktura, zakup ratalny, przelew natychmiastowy, polecenie zapłaty, karty Mastercard i VISA) i jest hostowane przez Klarna. Podczas dokonywania płatności Twoi klienci muszą jedynie podać adres e-mail i kod pocztowy, a następnie wybrać preferowaną metodę płatności. Wszystko to dzięki jednej integracji.',
    'TCKLARNA_PAYMENTS_DESC'                            => 'Dzięki Klarna klienci końcowi mogą płacić na trzy sposoby: przelewem natychmiastowym, później lub w ratach. Umożliwia to klientom końcowym najpierw wypróbowanie towaru i zapłacenie tylko za to, co chcą zatrzymać, sfinansowanie produktów w sklepie lub natychmiastową płatność. Fakturę, zakup na raty, przelew natychmiastowy lub polecenie zapłaty można aktywować za pomocą integracji, a dzięki rozwiązaniu iFrame firmy Klarna są one zawsze aktualne pod względem prawnym i merytorycznym.',
    'TCKLARNA_EASY_AND_SECURE_SHOPPING'                 => 'Najpopularniejsze metody płatności. Bezpieczne i łatwe do wdrożenia.',
    'TCKLARNA_WELCOME_TO_CONFIGURATION'                 => 'Serdecznie witamy w ustawieniach konfiguracyjnych Klarna Checkout i Klarna Payments. Znajdą Państwo tu wszystko, co jest potrzebne do aktywacji. Aby zakończyć konfigurację modułów, proszę wybrać podpunkty menu Klarna w pasku po lewej stronie.',

    'TCKLARNA_CREATE_USER_ACCOUNT'                      => 'Założenie konta klienta w sklepie internetowym OXID',
    'TCKLARNA_SUBSCRIBE_TO_NEWSLETTER'                  => 'Zapisanie się do newslettera',
    'TCKLARNA_CREATE_USER_ACCOUNT_AND_SUBSCRIBE'        => 'Załóż konto klienta ORAZ zapisz się do newslettera',
    'TCKLARNA_NO_CHECKBOX'                              => 'Nie wyświetlaj pola wyboru',


    /* design */
    'TCKLARNA_DISPLAY_ON_HOME'                          => 'Wyświetlać na stronie głównej sklepu?',
    'TCKLARNA_BANNER_SRC'                               => 'Źródło banera Klarna',
    'TCKLARNA_FOOTER'                                   => 'Stopka strony',
    'TCKLARNA_DISPLAY_IN_FOOTER'                        => 'Co ma być wyświetlane w stopce?',
    'TCKLARNA_FOOTER_PAYMENT_METHODS'                   => 'Wyświetlanie metod płatności',
    'TCKLARNA_FOOTER_KLARNA_LOGO'                       => 'Logo Klarna',
    'TCKLARNA_DESIGN'                                   => 'Projekt',
    'TCKLARNA_LONG_VERSION'                             => 'Wersja długa:',
    'TCKLARNA_SHORT_VERSION'                            => 'Wersja skrócona:',
    'TCKLARNA_WHITE'                                    => 'Biały:',
    'TCKLARNA_BLACK'                                    => 'Czarny:',
    'TCKLARNA_DETAILS_AND_BASKET'                       => 'Strona szczegółów produktu i koszyk',
    'TCKLARNA_DISPLAY_PAYMENT_WIDGET'                   => 'Wyświetlić widżet metody płatności Klarna?',
    'TCKLARNA_ON_PROD_PAGE'                             => 'Na stronie szczegółów produktu',
    'TCKLARNA_KEB_CLID'                                 => 'Klarna Express Checkout – identyfikator klienta',
    'TCKLARNA_KEB_SHIPPINGMETHOD'                       => 'Wysyłka w ramach usługi Klarna Express Checkout',
    'TCKLARNA_KEB_THEME'                                => 'Motyw przycisku „Klarna Express Checkout”',
    'TCKLARNA_KEB_THEME_default'                        => 'Standard (ciemny)',
    'TCKLARNA_KEB_THEME_light'                          => 'Pewności',
    'TCKLARNA_KEB_THEME_outlined'                       => 'Zarysowane',
    'TCKLARNA_KEB_SHAPE'                                => 'Formularz przycisku „Klarna Express Checkout”',
    'TCKLARNA_KEB_SHAPE_default'                        => 'Standard',
    'TCKLARNA_KEB_SHAPE_rect'                           => 'Prostokątny',
    'TCKLARNA_KEB_SHAPE_pill'                           => 'Pigułka',
    'TCKLARNA_ON_BASKET_PAGE'                           => 'Na stronie koszyka',
    'TCKLARNA_DISPLAY_EXPRESS_BUTTON'                   => 'Wyświetlić przycisk „Klarna Express Checkout”?',
    'TCKLARNA_PAYMENT_DESIGN'                           => 'Opcje projektowania płatności Klarna',
    'TCKLARNA_CHECKOUT_DESIGN'                          => 'Opcje projektowe Klarna Checkout',
    'TCKLARNA_COLOR_SETTINGS'                           => 'Ustawienia kolorów:',
    'TCKLARNA_BORDER'                                   => 'Granica:',
    'TCKLARNA_BORDER_SELECTED'                          => 'Wybrana granica:',
    'TCKLARNA_BUTTON'                                   => 'Przycisk:',
    'TCKLARNA_BUTTON_TEXT'                              => 'Tekst przycisku:',
    'TCKLARNA_CHECKBOX'                                 => 'Pole wyboru:',
    'TCKLARNA_CHECKBOX_CHECKMARK'                       => 'Zaznaczenie pola wyboru:',
    'TCKLARNA_DETAILS'                                  => 'Szczegóły:',
    'TCKLARNA_HEADER'                                   => 'Nagłówek:',
    'TCKLARNA_LINK'                                     => 'Link:',
    'TCKLARNA_TEXT'                                     => 'Tekst:',
    'TCKLARNA_SECONDARY_TEXT'                           => 'Dalsza treść:',
    'TCKLARNA_RADIUS_SETTINGS'                          => 'Ustawienie promienia:',
    'TCKLARNA_BORDER_RADIUS'                            => 'Promień zaokrąglenia krawędzi:',


    'TCKLARNA_ALLOW_SEPARATE_SHIPPING_ADDRESS'          => 'Adres dostawy może różnić się od adresu rozliczeniowego',
    'TCKLARNA_PHONE_NUMBER_MANDATORY'                   => 'Numer telefonu jest polem obowiązkowym',
    'TCKLARNA_DATE_OF_BIRTH_MANDATORY'                  => 'Data urodzenia jest polem obowiązkowym',
    'TCKLARNA_ENABLE_AUTOFOCUS'                         => 'Włącz autofokus dla iframe Klarna Checkout ',
    'TCKLARNA_ADD_A_CUSTOM_CHECKBOX'                    => 'Dodanie indywidualnego pola wyboru w ramce iframe w procesie płatności Klarna',
    'TCKLARNA_ENABLE_DHL_PACKSTATION'                   => 'Włącz dostawę do punktu odbioru DHL Packstation',
    'TCKLARNA_ENABLE_PRE_FILLING'                       => 'Włącz wstępne wypełnianie',
    'TCKLARNA_ENABLE_PREFILL_NOTIFICATION'              => 'Włącz powiadomienie o wstępnym napełnianiu',
    'TCKLARNA_SALUTATION_MANDATORY'                     => 'Pole „Tytuł” jest obowiązkowe',
    'TCKLARNA_SET_TAC_URI'                              => 'Adres URL do Państwa warunków handlowych – pole obowiązkowe dla KCO i Klarna Express',
    'TCKLARNA_SET_CANCEL_URI'                           => 'Adres URL dotyczący prawa do odstąpienia od umowy – pole obowiązkowe dla KCO i Klarna Express',
    'TCKLARNA_SHIPPING_DETAILS'                         => 'Adres URL ze szczegółami wysyłki – pole obowiązkowe dla KCO i Klarna Express',
    'TCKLARNA_NO_VALIDATION_NEEDED'                     => 'Brak walidacji',
    'TCKLARNA_VALIDATION_IGNORE_TIMEOUTS_NEEDED'        => 'Przeprowadź walidację, ale zignoruj przekroczenia limitu czasu',
    'TCKLARNA_SUCCESSFUL_VALIDATION_NEEDED'             => 'Konieczna jest pomyślna walidacja',
    'TCKLARNA_ORDER_VALIDATION'                         => 'Weryfikacja zamówienia',

    'TCKLARNA_CHOOSE_KP_OPTIONS'                        => 'Proszę wybrać opcje płatności Klarna, które chcą Państwo zaoferować swoim klientom:',
    'TCKLARNA_PAY_LATER'                                => 'Faktura',
    'TCKLARNA_PAY_LATER.'                               => 'Faktura.',
    'TCKLARNA_PAY_LATER_START'                          => 'Dla klientów, którzy chcą kupić teraz, a zapłacić później. Całkiem wygodnie w ciągu 30 dni, w zależności od rynku.',
    'TCKLARNA_PAY_LATER_TEXT'                           => 'Opcja „Faktura” sprawia, że proces płatności jest dla klientów prosty i szybki, bez konieczności podawania danych osobowych czy skomplikowanych numerów. Klient ma do wyboru opcję „Faktura” lub „Płatność w miesiącu X”.',
    'TCKLARNA_SLICE_IT'                                 => 'Zakup na raty.',
    'TCKLARNA_SLICE_IT.'                                => 'Płata w ratach.',
    'TCKLARNA_SLICE_IT_START'                           => 'Zwiększ siłę nabywczą swoich klientów dzięki płatnościom ratalnym. Klienci mogą regulować swoje zakupy w stałych miesięcznych ratach przez okres od 6 do 36 miesięcy.',
    'TCKLARNA_SLICE_IT_TEXT'                            => 'Dzięki opcji „zakupu ratalnego” klienci mogą rozłożyć kwotę zakupu na mniejsze raty przy niskim oprocentowaniu. Zwiększa to możliwości inwestycyjne i siłę nabywczą. Unikalny proces rozpatrywania wniosków kredytowych firmy Klarna zajmuje zaledwie kilka chwil i wymaga wprowadzenia minimalnej ilości danych.',
    'TCKLARNA_PAY_NOW'                                  => 'Zapłać od razu',
    'TCKLARNA_PAY_NOW.'                                 => 'Zapłać od razu.',
    'TCKLARNA_PAY_NOW_START'                            => 'Prosta i szybka płatność bezpośrednia dzięki usłudze „Sofort bezahlen” firmy Klarna. W Niemczech w ofercie nie powinno zabraknąć przelewu natychmiastowego, karty kredytowej i polecenia zapłaty.',
    'TCKLARNA_PAY_NOW_TEXT'                             => 'Klienci, którzy chcą zapłacić całą kwotę od razu przy finalizacji zamówienia, mogą skorzystać z opcji „Zapłać od razu”. Do wyboru są: karta kredytowa, polecenie zapłaty oraz przelew natychmiastowy.',
    'TCKLARNA_CHECKOUT'                                 => 'Klarna Checkout.',
    'TCKLARNA_CHECKOUT_START'                           => 'Najlepszy proces realizacji transakcji dla Twoich klientów. Niezawodna identyfikacja klientów i wybór opcji wysyłki. Wszystkie płatności w cenie. Dostępność na całym świecie, zoptymalizowana pod kątem lokalnych warunków. Bierzemy na siebie całe ryzyko, a Ty zawsze otrzymujesz swoje pieniądze.',

    'TCKLARNA_RB_HOW_TO_ACTIVATE'                       => 'How-to-activate<br>Klarna guide.',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_ONE'              => 'W panelu administracyjnym OXID kliknij nową pozycję menu „Klarna”, następnie podkategorię „Ogólne”, a na koniec wybierz żądany produkt Klarna. Do wyboru masz opcje „Klarna Payments” i „Klarna Checkout”.',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_TWO'              => 'Wprowadź swoje dane logowania (nazwę użytkownika i hasło), a następnie w sekcji „Ustawienia sklepu” &gt; „Metody płatności” oraz &gt; „Metody wysyłki” skonfiguruj typowe dla OXID przyporządkowania metod płatności.',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_THREE'            => 'Zapisz zmiany.',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_FOUR'             => 'Jesteś już online i możesz zacząć sprzedawać za pomocą Klarna.',
    'TCKLARNA_RB_MERCHANT_SUPPORT'                      => 'Wsparcie dla sprzedawców',
    'TCKLARNA_DEVICE_IMG'                               => 'device.png',


    'TCKLARNA_EXTERNAL_PAYMENTS_ADMIN_DESC'             => 'W tym miejscu można skonfigurować zewnętrzne metody płatności i zewnętrzne procesy realizacji transakcji w celu ich zintegrowania z ramką iframe Klarna Checkout. 
Szczegółowy opis poszczególnych ustawień można znaleźć w podpowiedziach 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, zapoznaj się z <a class="cl-pink" href="https://wiki.fatchip.de/public/faqklarna" target="_blank">instrukcją obsługi</a> 
lub skontaktuj się z działem wsparcia technicznego ds. integracji Klarna.',
    'TCKLARNA_EXTRA_MERCHANT_DATA_ADMIN_DESC'           => 'W tym miejscu można skonfigurować, czy w razie potrzeby dodatkowe dane sprzedawcy mają być przekazywane do Klarna. 
Szczegółowy opis poszczególnych ustawień można znaleźć w podpowiedziach 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, zapoznaj się z <a class="cl-pink" href="https://wiki.fatchip.de/public/faqklarna" target="_blank">instrukcją obsługi</a> 
lub skontaktuj się z działem wsparcia technicznego ds. integracji Klarna.',
    'TCKLARNA_DESIGN_SETTINGS_ADMIN_DESC'               => 'W tym miejscu można skonfigurować ustawienia wyglądu do wykorzystania z modułem Klarna dla sklepu OXID eShop. 
Szczegółowy opis poszczególnych ustawień można znaleźć w podpowiedziach 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, zapoznaj się z <a class="cl-pink" href="https://wiki.fatchip.de/public/faqklarna" target="_blank">instrukcją obsługi</a> 
lub skontaktuj się z działem wsparcia technicznego ds. integracji Klarna.',
    'TCKLARNA_GENERAL_SETTINGS_ADMIN_DESC'              => 'W tym miejscu można wybrać między Klarna Checkout a Klarna Payments oraz skonfigurować ustawienia ogólne. 
Szczegółowy opis poszczególnych ustawień można znaleźć w podpowiedziach 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, zapoznaj się z <a class="cl-pink" href="https://wiki.fatchip.de/public/faqklarna" target="_blank">instrukcją obsługi</a> 
lub skontaktuj się z działem wsparcia technicznego ds. integracji Klarna.',
    'TCKLARNA_CONFIGURATION_KCO_ADMIN_DESC'             => 'Na tej stronie można skonfigurować ustawienia specyficzne dla usługi Klarna Checkout. 
Szczegółowy opis poszczególnych ustawień można znaleźć w podpowiedziach 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, zapoznaj się z <a class="cl-pink" href="https://wiki.fatchip.de/public/faqklarna" target="_blank">instrukcją obsługi</a> 
lub skontaktuj się z działem wsparcia technicznego ds. integracji Klarna.',
    'TCKLARNA_CONFIGURATION_KP_ADMIN_DESC'              => 'Na tej stronie możesz wybrać, które usługi płatnicze Klarna chcesz oferować. 
Szczegółowy opis poszczególnych ustawień można znaleźć w podpowiedziach 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, zapoznaj się z <a class="cl-pink" href="https://wiki.fatchip.de/public/faqklarna" target="_blank">instrukcją obsługi</a> 
lub skontaktuj się z działem wsparcia technicznego ds. integracji Klarna.',

    'TCKLARNA_PAYMENT_METHOD'                           => 'Sposób płatności',
    'TCKLARNA_EXTERNAL_PAYMENT_METHOD'                  => 'Zewnętrzna metoda płatności',
    'TCKLARNA_EXTERNAL_CHECKOUT'                        => 'Zewnętrzna procedura płatności',
    'TCKLARNA_IMAGE_URI_EXT_PAYMENT'                    => 'Adres URI obrazu dla zewnętrznej metody płatności',
    'TCKLARNA_IMAGE_URI_EXT_CHECKOUT'                   => 'Adres URI obrazu dla zewnętrznej kasy',
    'TCKLARNA_IMAGE_TIP_69x24'                          => 'Rozmiar obrazu: 69x24 pikseli',
    'TCKLARNA_IMAGE_TIP_276x48'                         => 'Rozmiar obrazu: 276 x 48 pikseli',
    'TCKLARNA_USER_GUIDE_DESCRIPTION'                   => 'Podręcznik użytkownika modułu Klarna dla sklepu OXID eShop można przejrzeć tutaj.',
    'TCKLARNA_USER_GUIDE_LINK'                          => 'https://wiki.fatchip.de/public/faqklarna',
    'TCKLARNA_USER_GUIDE_BUTTON'                        => 'Instrukcja obsługi',

    'TCKLARNA_CHOOSE'                                   => 'Wybrać',

    'TCKLARNA_CUSTOMER_ACCOUNT_INFO'                    => 'Informacje o koncie klienta',
    'TCKLARNA_PAYMENT_HISTORY_FULL'                     => 'Pełna historia płatności',
    'TCKLARNA_PASSTHROUGH_FIELD'                        => 'Pole typu „pass-through”',

    'TCKLARNA_ASSIGN_PAYMENT_METHOD_TYPE'               => 'Przypisz typ metody płatności:',
    'TCKLARNA_WHICH_ORDERS_IN_FULL_PAYMENT_HISTORY'     => 'Które zamówienia powinny zostać uwzględnione w pełnej historii płatności?',
    'TCKLARNA_EMD_ORDER_HISTORY_ALL'                    => 'Wszystkie zamówienia uznaje się za opłacone, niezależnie od daty Oxpaid',
    'TCKLARNA_EMD_ORDER_HISTORY_PAID'                   => 'Przesyłać wyłącznie zamówienia z ustawioną datą oxpaid; zamówienia niezapłacone należy zignorować',
    'TCKLARNA_EMD_ORDER_HISTORY_NONE'                   => 'Zignoruj wszystkie zamówienia złożone przy użyciu tej metody płatności',
    'TCKLARNA_OTHER_PAYMENT'                            => 'Inna opcja płatności',
    'TCKLARNA_DIRECT_BANKING'                           => 'Przelew natychmiastowy',
    'TCKLARNA_CARD'                                     => 'Mapa',

    'TCKLARNA_TEST_MODE_TOOLTIP'                        => 'Wybierz opcję „Playground” (tryb testowy) lub „Live” (tryb produkcyjny). Tryb produkcyjny należy aktywować dopiero po pomyślnym przeprowadzeniu testów integracyjnych i po konsultacji z menedżerem ds. integracji Klarna.',
    'TCKLARNA_GLOBAL_MERCHANT_ID_TOOLTIP'               => 'Proszę wprowadzić tutaj dane dostępowe do API Klarna. Otrzymali Państwo je w wiadomości e-mail z powitaniem od Klarna. Ta nazwa użytkownika wraz z hasłem obowiązuje globalnie we wszystkich krajach. Tylko w przypadku, gdy otrzymali Państwo różne dane dostępowe dla poszczególnych krajów, mogą Państwo dodać je poniżej.',
    'TCKLARNA_GLOBAL_PASSWORD_TOOLTIP'                  => 'Wpisz tutaj hasło odpowiadające używanej nazwie użytkownika API. Hasło to otrzymałeś w wiadomości e-mail z powitaniem od firmy Klarna.',
    'TCKLARNA_GLOBAL_PORTAL_MERCHANT_ID_TOOLTIP'        => 'Proszę wpisać tutaj swój identyfikator sprzedawcy Klarna. Otrzymali Państwo go w wiadomości e-mail z powitaniem od firmy Klarna.',
    'TCKLARNA_CREDENTIALS_COUNTRY_SELECTOR_TOOLTIP'             => 'Z listy po lewej stronie wybierz kraj, dla którego otrzymałeś dane dostępowe do serwisu Klarna przeznaczone dla tego kraju.',
    'TCKLARNA_CREDENTIALS_COUNTRY_MERCHANT_ID_TOOLTIP'          => 'Proszę wpisać tutaj nazwę użytkownika dla tego kraju.',
    'TCKLARNA_CREDENTIALS_COUNTRY_PASSWORD_TOOLTIP'             => 'Proszę wpisać tutaj hasło dla tego kraju.',
    'TCKLARNA_CREDENTIALS_COUNTRY_PORTAL_MERCHANT_ID_TOOLTIP'   => 'Proszę wpisać tutaj identyfikator sprzedawcy (Merchant ID) dla tego kraju.',
    'TCKLARNA_DEFAULT_COUNTRY_TOOLTIP'                  => 'Proszę wybrać z listy kraj, dla którego domyślnie ma być ładowana strona Klarna Checkout, dopóki klient nie poda jeszcze swojego kraju.',
    'TCKLARNA_ENABLE_LOGGING_TOOLTIP'                   => 'Włącza funkcję logowania, dzięki czemu cała komunikacja API z Klarną jest rejestrowana w tabeli MySQL o nazwie tcklarna_logs. Może to być przydatne podczas analizy lub wyszukiwania błędów. W środowisku produkcyjnym funkcja ta powinna być wyłączona, ponieważ w przeciwnym razie mogą gromadzić się duże ilości logów i być zapisywane dane wrażliwe.',
    'TCKLARNA_SEND_PRODUCT_URLS_TOOLTIP'                => 'Prosimy o przesłanie do firmy Klarna adresów URL stron szczegółowych produktów znajdujących się w koszykach Państwa klientów, aby firma Klarna mogła później umieścić linki do tych produktów na portalu Klarna.',
    'TCKLARNA_SEND_PRODUCT_IMAGES_TOOLTIP'              => 'Prosimy o przesłanie do firmy Klarna adresów URL zdjęć produktów znajdujących się w koszykach Państwa klientów, aby firma Klarna mogła je wyświetlić w portalu Klarna.',
    'TCKLARNA_ENABLE_ANONYMIZATION_TOOLTIP'             => 'Włącz funkcję anonimizacji, aby ukryć nazwy produktów znajdujących się w koszyku Twoich klientów przed Klarną. Jest to zalecane np. w przypadku aptek internetowych, jednak należy to zrobić wyłącznie po konsultacji z menedżerem ds. integracji z Klarną.',
    'TCKLARNA_ALLOW_SEPARATE_DELIVERY_ADDRESS_TOOLTIP'  => 'Jeśli chcesz umożliwić dostawę pod inny adres, zaznacz to pole wyboru.',
    'TCKLARNA_MANDATORY_PHONE_TOOLTIP'                  => 'Jeśli chcą Państwo, aby podanie numeru telefonu było obowiązkowe, proszę włączyć ten przełącznik. Zazwyczaj w systemie Klarna numer telefonu nie jest polem obowiązkowym.',
    'TCKLARNA_MANDATORY_BIRTH_DATE_TOOLTIP'             => 'Jeśli chcą Państwo, aby podanie daty urodzenia było obowiązkowe, proszę zaznaczyć to pole wyboru. Zazwyczaj w systemie Klarna data urodzenia nie jest polem obowiązkowym. Jest ona jednak niezbędna, aby umożliwić zakup na rachunek lub płatność w ratach.',
    'TCKLARNA_ENABLE_AUTOFOCUS_TOOLTIP'                 => 'Za pomocą tego przełącznika można włączyć automatyczne przełączanie fokusu na ramkę iframe Klarna podczas ładowania strony z modułem Klarna Checkout.',
    'TCKLARNA_CHECKBOX_TOOLTIP'                         => 'Istnieje możliwość zaznaczenia dodatkowego pola wyboru w ramce iframe serwisu Klarna Checkout, aby zaproponować klientowi założenie konta klienta lub zapisanie się do newslettera, albo jedno i drugie. Jeśli po zaznaczeniu tego pola wyboru klient posiada już konto lub jest już zapisany do newslettera, tekst pola wyboru zostanie automatycznie dostosowany lub, w razie potrzeby, pole wyboru zostanie całkowicie ukryte.',
    'TCKLARNA_VALIDATION_TOOLTIP'                       => 'Za pomocą tej opcji można włączyć dodatkową weryfikację koszyka, która podczas wysyłania zamówienia przez Klarna Checkout ponownie sprawdza dostępność wybranych produktów, aby uniknąć błędów wynikających ze sprzedaży ponad stan. Zalecany jest tryb „Wymagana pomyślna weryfikacja”.',
    'TCKLARNA_SALUTATION_MANDATORY_TOOLTIP'             => 'To ustawienie dotyczy wyłącznie formularza Klarna Checkout dla Wielkiej Brytanii: czy należy wymusić podanie tytułu?',
    'TCKLARNA_ENABLE_DHL_PACKSTATIONS_TOOLTIP'          => 'Obecnie nie jest to zaimplementowane',
    'TCKLARNA_ENABLE_PRE_FILLING_TOOLTIP'               => 'Włącz automatyczne wypełnianie ramki iframe Klarna Checkout danymi klienta zalogowanego w sklepie OXID eShop',
    'TCKLARNA_ENABLE_PREFILL_NOTIFICATION_TOOLTIP'      => 'Jeśli funkcja automatycznego wypełniania ramki iframe Klarna Checkout jest włączona, w przypadku niektórych krajów należy wyświetlić odpowiednią informację o ochronie danych. Informację tę aktywuje się za pomocą tego przełącznika.',
    'TCKLARNA_TERMS_AND_CONDITIONS_URL_TOOLTIP'         => 'W tym miejscu należy podać adres URL prowadzący do ogólnych warunków handlowych. Link do nich zostanie umieszczony w ramce iframe serwisu Klarna Checkout. Należy podać prawidłowy adres URL, zaczynający się od https://.',
    'TCKLARNA_CANCELLATION_RIGHTS_URL_TOOLTIP'          => 'W tym miejscu należy podać adres URL swojej strony internetowej zawierającej informacje na temat prawa do odstąpienia od umowy. Adres URL musi zaczynać się od https://.',
    'TCKLARNA_SHIPPING_DETAILS_TOOLTIP'                 => 'Te informacje dotyczące wysyłki są wyświetlane klientowi na stronie podziękowania po złożeniu zamówienia.',
    'TCKLARNA_EXTERNAL_PAYMENT_NAME_SELECT_TOOLTIP'     => 'Przypisz tę zewnętrzną metodę płatności do jednej z predefiniowanych metod płatności',
    'TCKLARNA_ENABLE_EXTERNAL_PAYMENT_TOOLTIP'          => 'Za pomocą tego przełącznika można aktywować tę metodę płatności jako zewnętrzną opcję płatności w ramach Klarna Checkout. Gdy opcja jest aktywna, klient może wybrać tę metodę płatności z listy metod płatności wyświetlanej w ramce iframe Klarna Checkout.',
    'TCKLARNA_ENABLE_EXTERNAL_CHECKOUT_TOOLTIP'         => 'Za pomocą tego przełącznika można włączyć tę metodę płatności jako zewnętrzną procedurę płatności. Gdy opcja jest włączona, metoda ta wyświetla się na samym dole ramki iframe procedury płatności Klarna, jeszcze przed wprowadzeniem danych klienta.',
    'TCKLARNA_EXTERNAL_PAYMENT_IMAGE_URL_TOOLTIP'       => 'W tym miejscu należy podać adres URL obrazu, który ma być wyświetlany obok metody płatności w ramce iframe Klarna Checkout. Najlepiej użyć obrazu z bezpiecznego adresu URL, zaczynającego się od https://.',
    'TCKLARNA_EXTERNAL_CHECKOUT_IMAGE_URL_TOOLTIP'      => 'W tym miejscu należy podać adres URL obrazu, który ma zostać wyświetlony jako przycisk dla tej metody płatności w ramce iframe Klarna Checkout poniżej. Najlepiej użyć obrazu z bezpiecznego adresu URL, zaczynającego się od https://.',
    'TCKLARNA_EXTERNAL_IMAGE_URL_EMPTY'                 => 'Proszę podać adres URL dla wszystkich języków',
    'TCKLARNA_EXTERNAL_IMAGE_URL_INVALID'               => 'Proszę podać prawidłowy adres URL, zaczynający się od https://',
    'TCKLARNA_EMD_CUSTOMER_INFO_TOOLTIP'                => 'Ten przełącznik aktywuje przesyłanie dodatkowych danych do Klarna – w tym przypadku informacji o koncie klienta, zawierających datę rejestracji konta oraz datę ostatniej zmiany.',
    'TCKLARNA_EMD_PAYMENT_HISTORY_FULL_TOOLTIP'         => 'Ten przełącznik aktywuje przesyłanie dodatkowych danych do Klarna – w tym przypadku chodzi o „Payment History Full”, czyli pełną historię płatności, zawierającą dotychczasowe zakupy klienta.',
    'TCKLARNA_EMD_PAYMENT_TYPE_TOOLTIP'                 => 'Proszę wskazać, jakiego rodzaju jest ta metoda płatności.',
    'TCKLARNA_EMD_HISTORY_FULL_TOOLTIP'                 => 'Proszę określić tutaj, czy i ewentualnie które zamówienia opłacone tą metodą płatności mają zostać uwzględnione podczas przenoszenia historii zamówień klienta. Zależność pola OXORDER.OXPAID określa, czy mają być uwzględnione tylko opłacone zamówienia, czy wszystkie zamówienia.',
    'TCKLARNA_EMD_PASSTHROUGH_FIELD_TOOLTIP'            => 'Istnieje możliwość przekazania dowolnych dodatkowych danych do Klarna za pomocą pola „pass-through”. Aby skorzystać z tej funkcji, należy zainstalować odpowiedni moduł w sklepie OXID eShop, który zapisuje żądane dane w polu „pass-through”. Odpowiednią instrukcję można znaleźć w dokumentacji dla programistów.',
    'TCKLARNA_DISPLAY_ON_HOME_TOOLTIP'                  => 'Za pomocą tego przełącznika można wyświetlić baner Klarna na stronie głównej sklepu w standardowych motywach Flow lub Wave.',
    'TCKLARNA_BANNER_SRC_TOOLTIP'                       => 'W tym miejscu można umieścić tag skryptowy służący do osadzenia banera. W portalu banerów firmy Klarna można znaleźć dodatkowe banery do wyboru.',
    'TCKLARNA_FOOTER_PAYMENT_METHODS_TOOLTIP'           => 'Za pomocą tego przełącznika można włączyć wyświetlanie metody płatności Klarna w stopce sklepu w standardowych motywach Flow i Wave.',
    'TCKLARNA_FOOTER_KLARNA_LOGO_TOOLTIP'               => 'Za pomocą tego przełącznika można umieścić logo Klarna w stopce sklepu w standardowych motywach Flow lub Wave.',
    'TCKLARNA_BUY_NOW_ON_BASKET_TOOLTIP'                => 'Ten przełącznik dodaje przycisk „Klarna Express Checkout” na stronie koszyka w Twoim sklepie w standardowych motywach.',
    'TCKLARNA_BUY_NOW_ON_PROD_PAGE_TOOLTIP'             => 'Ten przełącznik dodaje przycisk „Klarna Express Checkout” na stronach szczegółów produktów w Twoim sklepie w standardowych motywach.',
    'TCKLARNA_KEB_CLID_TOOLTIP'                         => 'Aby móc korzystać z funkcji Klarna Express Checkout, należy ją aktywować w portalu Klarna w zakładce „Conversion boosters”. Po pomyślnym wprowadzeniu danych identyfikator klienta można skopiować do tego pola.',
    'TCKLARNA_BORDER_TOOLTIP'                           => 'Kolor ramki, która pojawia się w interfejsie sklepu po wybraniu metody płatności Klarna, w zależności od dostępnych podopcji.',
    'TCKLARNA_BORDER_SELECTED_TOOLTIP'                  => 'Kolor ramki, która pojawia się w interfejsie sklepu po wybraniu metody płatności Klarna, w przypadku gdy dostępne są różne opcje podrzędne. Ten kolor służy do wyróżnienia aktualnie wybranej opcji podrzędnej.',
    'TCKLARNA_BUTTON_TOOLTIP'                           => 'W momencie publikacji tego modułu to ustawienie nie ma jeszcze żadnego wpływu.',
    'TCKLARNA_BUTTON_TEXT_TOOLTIP'                      => 'W momencie publikacji tego modułu to ustawienie nie ma jeszcze żadnego wpływu.',
    'TCKLARNA_DESIGN_CHECKBOX_TOOLTIP'                  => 'Kolor tła przycisków opcji, które pojawiają się w interfejsie sklepu po wybraniu metody płatności Klarna, w zależności od dostępnych podopcji',
    'TCKLARNA_DESIGN_CHECKBOX_CHECKMARK_TOOLTIP'        => 'W momencie publikacji tego modułu to ustawienie nie ma jeszcze żadnego wpływu.',
    'TCKLARNA_DETAILS_TOOLTIP'                          => 'Kolor symboli wypunktowania podczas wyświetlania szczegółów płatności na stronie wyboru metod płatności.',
    'TCKLARNA_HEADER_TOOLTIP'                           => 'W momencie publikacji tego modułu to ustawienie nie ma jeszcze żadnego wpływu.',
    'TCKLARNA_LINK_TOOLTIP'                             => 'Kolor linków w szczegółowym opisie metod płatności na stronie wyboru metod płatności.',
    'TCKLARNA_TEXT_TOOLTIP'                             => 'Kolor tekstu szczegółowego opisu metod płatności na stronie wyboru metod płatności.',
    'TCKLARNA_SECONDARY_TEXT_TOOLTIP'                   => 'Alternatywny kolor tekstu opisu szczegółowego metod płatności na stronie wyboru metod płatności.',
    'TCKLARNA_BORDER_RADIUS_TOOLTIP'                    => 'Za pomocą tego ustawienia można określić stopień zaokrąglenia ramki, która pojawia się w interfejsie sklepu po wybraniu metody płatności Klarna, w zależności od dostępnych opcji podrzędnych.',

    'KLARNA_ONLY_FOR_KLARNA_PAYMENT'                    => 'Ta zakładka dotyczy wyłącznie zamówień realizowanych przez Klarna',
    'KLARNA_CAPTURE_FULL_ORDER'                         => 'Zarejestruj całe zamówienie',
    'KLARNA_CAPTURE_ID'                                 => 'Numer transakcji',
    'KLARNA_CAPTURE_REFERENCE'                          => 'Informacje o Klarna',
    'KLARNA_CAPTURE_AMOUNT'                             => 'Kwota obciążenia',
    'KLARNA_CAPTURE_DATE'                               => 'Pobrano w dniu',
    'KLARNA_REFUND_AMOUNT'                              => 'Kwota zwrotu',
    'KLARNA_REFUND_DESCRIPTION'                         => 'Zwrot kosztów – wyjaśnienie',
    'KLARNA_REFUND_DATE'                                => 'Zastąpiono am',
    'KLARNA_CAPTURES'                                   => 'Pobrania',
    'KLARNA_REFUNDS'                                    => 'Zwroty kosztów',
    'KLARNA_CANCEL_ORDER'                               => 'Anulowanie zamówienia',
    'KLARNA_ORDER_IS_CANCELLED'                         => 'Zamówienie zostało anulowane. ',
    'KLARNA_SEE_ORDER_IN_PORTAL'                        => '<a href="%s" target="_blank" class="alert-link">Zobacz to zamówienie w portalu Klarna</a>',
    'KLARNA_ORDER_NOT_IN_SYNC'                          => '<strong>Uwaga!</strong> Dane dotyczące tego zamówienia różnią się od danych zapisanych w systemie Klarna. ',
    'TCKLARNA_ORDER_UPDATE_CANT_BE_SENT_TO_KLARNA'      => 'Uwaga! Ze względu na aktualny status zamówienia nie można przesłać tej korekty do Klarna. W razie potrzeby należy wprowadzić odpowiednią korektę ręcznie bezpośrednio w portalu Klarna Merchant Portal.',
    'TCKLARNA_ORDER_UPDATE_REJECTED_BY_KLARNA'          => 'Uwaga! Firma Klarna nie mogła przetworzyć ostatnich zmian wprowadzonych w tym zamówieniu (przyczyna: %s). Prosimy o cofnięcie ostatnich zmian w sklepie OXID eShop lub, w razie potrzeby, o ręczne wprowadzenie odpowiednich poprawek w portalu Klarna Merchant Portal.',
    'KLARNA_UNAUTHORIZED_REQUEST'                       => 'Niedozwolone żądanie. Sprawdź ustawienia modułu Klarna oraz identyfikator sprzedawcy (Merchant ID) i związane z nim hasło.',
    'KLARNA_ORDER_NOT_FOUND'                            => 'Nie udało się znaleźć tego zamówienia w systemie firmy Klarna. W związku z tym zmiany w danych zamówienia nie zostaną przekazane do firmy Klarna.',
    'KLARNA_MID_CHANGED_FOR_COUNTRY'                    => '<strong>Nieprawidłowe dane logowania!</strong> To zamówienie zostało złożone przy użyciu identyfikatora sprzedawcy <strong>%s</strong>. Aktualny identyfikator sprzedawcy skonfigurowany dla strony <strong>%s</strong> to <strong>%s</strong>.',
    'TCKLARNA_PRODUCT_NAME'                             => 'Nazwa produktu',
    'TCKLARNA_ANONYMIZED_PRODUCT'                       => 'Anonimizowany tytuł produktu:',
    'TCKLARNA_KCO_INVOICE_MSG'                          => 'Płatność jest realizowana przez naszego partnera, firmę Klarna. Jeśli nie uregulowali Państwo jeszcze płatności za zakupy, prosimy o zapoznanie się z informacjami dotyczącymi płatności przesłanymi przez firmę Klarna. Wszystkie swoje zakupy mogą Państwo zarządzać za pośrednictwem strony Klarna.com lub aplikacji Klarna, a nawet dokonać płatności jednym kliknięciem.',
    'TCKLARNA_KP_INVOICE_MSG'                           => 'Płatność jest realizowana przez naszego partnera, firmę Klarna. Prosimy o zapoznanie się z informacjami dotyczącymi płatności przesłanymi przez firmę Klarna. Wszystkie swoje zakupy można zarządzać za pośrednictwem strony Klarna.com lub aplikacji Klarna, a nawet dokonać płatności jednym kliknięciem.',
    'TCKLARNA_VOUCHER_DISCOUNT'                         => 'Kupon rabatowy',

    'TCKLARNA_KCO_BUTTON_TOOLTIP'                       => 'Kolor tła przycisku płatności w ramce iframe serwisu Klarna Checkout.',
    'TCKLARNA_KCO_BUTTON_TEXT_TOOLTIP'                  => 'Kolor tekstu przycisku płatności w ramce iframe Klarna Checkout.',
    'TCKLARNA_KCO_DESIGN_CHECKBOX_TOOLTIP'              => 'Kolor tła pól wyboru w ramce iframe serwisu Klarna Checkout.',
    'TCKLARNA_KCO_DESIGN_CHECKBOX_CHECKMARK_TOOLTIP'    => 'Kolor znacznika w polach wyboru w ramce iframe serwisu Klarna Checkout.',
    'TCKLARNA_KCO_HEADER_TOOLTIP'                       => 'Kolor nagłówków / tytułów w ramce iframe serwisu Klarna Checkout.',
    'TCKLARNA_KCO_LINK_TOOLTIP'                         => 'Kolor linków w ramce iframe serwisu Klarna Checkout.',
    'TCKLARNA_KCO_BORDER_RADIUS_TOOLTIP'                => 'Za pomocą tego ustawienia można określić stopień zaokrąglenia ramki iframe Klarna Checkout.',

    'TCKLARNA_GIFT_WRAPPING_TITLE'                      => 'Opakowanie prezentowe',
    'TCKLARNA_GIFT_CARD_TITLE'                          => 'Kartka z życzeniami',

    'TCKLARNA_ERROR_SHOP_SSL_NOT_CONFIGURED'            => 'Błąd krytyczny: Podanie prawidłowego adresu URL chronionego protokołem SSL (https) w polu $this->sSSLShopURL w pliku config.inc.php Twojego sklepu jest obowiązkowe, jeśli chcesz aktywować funkcję „%s”!',
    'TCKLARNA_ERROR_WRONG_CREDS'                        => '<strong>Nieprawidłowe dane logowania!</strong>',
    'TCKLARNA_ERROR_KCO_INACTIVE'                       => 'Błąd konfiguracji: usługa Klarna Checkout nie jest aktywna w sklepie',

    'KLARNA_CAPTURE_SUCCESSFULL'                        => 'Kwota została pomyślnie pobrana.',
    'TCKLARNA_CAPUTRE_FAIL_ORDER_CANCELLED'             => ' Nie udało się pobrać opłaty za zamówienie, ponieważ zostało ono już anulowane.',
    'TCKLARNA_ANONYMIZED_PRODUCT_TOOLTIP'               => 'W tym miejscu należy wpisać ciąg znaków, który ma zostać przesłany do Klarna zamiast rzeczywistej nazwy produktu.',
    'TCKLARNA_NO_REQUESTS_WILL_BE_SENT'                 => 'Zmiany wprowadzone przez Państwa w tym zamówieniu nie zostaną przekazane do firmy Klarna.',
    'TCKLARNA_USER_GUIDE'                               => 'Instrukcja obsługi',
    'TCKLARNA_REGISTER_NOW_BUTTON'                      => 'Zarejestruj się',
    'TCKLARNA_LEARN_MORE_BUTTON'                        => 'Dowiedz się więcej',

    'TCKLARNA_CUSTOMER_TYPE'                            => 'Obsługiwane typy klientów',
    'TCKLARNA_CUSTOMER_TYPE_TOOLTIP'                    => 'Tutaj możesz skonfigurować, czy sklep ma akceptować tylko transakcje B2C (ustawienie domyślne), tylko transakcje B2B, czy zarówno transakcje B2C, jak i B2B. <br> Uwaga: Po zmianie typu klienta, pamięć podręczna sesji przeglądarki musi zostać wyczyszczona przed przetestowaniem płatności.',
    'TCKLARNA_B2C'                                      => 'Wyłącznie klienci B2C',
    'TCKLARNA_B2B'                                      => 'Wyłącznie klienci B2B',
    'TCKLARNA_B2B_B2C'                                  => 'Głównie klienci z sektora B2B, ale także klienci z sektora B2C',
    'TCKLARNA_B2C_B2B'                                  => 'Głównie klienci z sektora B2C, ale także klienci z sektora B2B',
    'TCKLARNA_NEED_SUPPORT'                             => 'Potrzebują Państwo pomocy przy integracji?',
    'TCKLARNA_REACH_SUPPORT'                            => 'Skontaktuj się z działem obsługi sprzedawców firmy Klarna',

    'TCKLARNA_EU_WARNING'                               => '<p>Aby zachować zgodność z rozporządzeniem UE w sprawie blokowania geograficznego, zdecydowanie zaleca się aktywowanie wszystkich krajów europejskich i przypisanie im metody płatności Klarna Checkout.</p><p>Brakuje następujących krajów: %s</p>',

    'TCKLARNA_ON_SITE_MESSAGING'                        => 'Wiadomości na stronie',
    'TCKLARNA_ON_SITE_MESSAGING_ADMIN_DESC'             => 'W tym miejscu można skonfigurować komunikację na stronie do wykorzystania z modułem Klarna dla sklepu OXID eShop.',
    'TCKLARNA_ON_SITE_MESSAGING_SCRIPT'                 => 'Skrypt',
    'TCKLARNA_CREDIT_PROMOTION_PRODUCT'                 => 'Strona szczegółów produktu w ramach promocji kredytowej',
    'TCKLARNA_CREDIT_PROMOTION_BASKET'                  => 'Promocja kredytowa Koszyk',
    'TCKLARNA_TOP_STRIP_PROMOTION'                      => 'Promocja „Top-strip”',
    'TCKLARNA_FOOTER_PROMOTION'                         => 'Promocja w stopce strony',
    'TCKLARNA_BANNER_PROMOTION'                         => 'Promocja banerowa',
    'TCKLARNA_ON_SITE_MESSAGING_SCRIPT_TOOLTIP'         => 'Proszę wstawić tutaj fragment kodu biblioteki JavaScript niezbędny do działania funkcji On-Site Messaging, który można uzyskać w portalu Klarna Merchant Portal.',
    'TCKLARNA_CREDIT_PROMOTION_PRODUCT_TOOLTIP'         => 'Proszę wstawić tutaj tag „Placement”, aby promować finansowanie i zakup na raty za pośrednictwem Credit Promotions na stronie szczegółów produktu',
    'TCKLARNA_CREDIT_PROMOTION_BASKET_TOOLTIP'          => 'Proszę wstawić tutaj tag „Placement”, aby promować finansowanie i zakupy na raty za pośrednictwem Credit Promotions na stronie podsumowania koszyka',
    'TCKLARNA_TOP_STRIP_PROMOTION_TOOLTIP'              => 'Proszę wstawić tutaj tag Placement, aby wyeksponować na stronie głównej sklepu informacje ogólne oraz dotyczące poszczególnych metod płatności',
    'TCKLARNA_FOOTER_PROMOTION_TOOLTIP'                 => 'W tym miejscu proszę wstawić tag Placement, aby wyświetlić dostępne metody płatności Klarna w stopce sklepu',
    'TCKLARNA_BANNER_PROMOTION_TOOLTIP'                 => 'W tym miejscu proszę wstawić tag umieszczenia, aby dodać baner na stronie głównej sklepu',
    'TCKLARNA_ON_SITE_MESSAGING_HEADER_TITLE'           => 'Czym jest komunikacja na stronie?',
    'TCKLARNA_ON_SITE_MESSAGING_HEADER_DESC'            => 'Klienci nie zawsze zdają sobie sprawę z różnych możliwości kredytowych i finansowych, jakie mają do dyspozycji, zanim dotrą do kasy. Możliwości finansowania dostępne na wczesnym etapie mają wpływ na decyzję o zakupie.

Funkcja On-Site Messaging jest łatwa i bezproblemowa w integracji oraz zapewnia dostosowane do potrzeb informacje – od ogólnych banerów, przez promocję współpracy z Klarną i dostępność płatności ratalnej, aż po spersonalizowane oferty kredytowe na stronach produktów lub koszyka.',
    'TCKLARNA_ON_SITE_MESSAGING_HEADER_DESC_2'          => 'Więcej informacji na temat pierwszych kroków można znaleźć tutaj: <a class="cl-pink" href="https://docs.klarna.com/conversion-boosters/on-site-messaging/before-you-start/" target="_blank" rel=”noopener”></a><br><br> 
Zaloguj się do <a class="cl-pink" href="https://merchants.klarna.com/" target="_blank">Portalu Sprzedawcy</a>, aby wygenerować swój osobisty kod JavaScript i kod pozycjonowania. Wiadomości na stronie zostaną aktywowane w Twoim sklepie po zapisaniu kodu JavaScript i wprowadzeniu co najmniej jednego kodu pozycjonowania.<br> 
Można to w każdej chwili wyłączyć, usuwając te kody.',
    'TCKLARNA_ON_SITE_MESSAGING_MERCHANT_BUTTON'        => 'Portal dla sprzedawców',

    'TCKLARNA_IS_ENABLED_HEADLINE'                      => 'Włącz usługę Klarna Instant Shopping',
    'TCKLARNA_IS_ENABLED'                               => 'Aktywny',
    'TCKLARNA_IS_BUTTON_REPLACE'                        => 'Wymiana przycisku Key',
    'TCKLARNA_IS_REPLACE'                               => 'Utwórz nowy przycisk „Key”',
    'TCKLARNA_IS_BUTTON_REPLACE_TOOLTIP'                => 'Można zaktualizować klucz przycisku, jeśli dane konfiguracyjne lub identyfikacyjne wymagają zmiany ze strony Klarna. Zazwyczaj raz wygenerowany klucz przycisku można używać tak długo, jak się chce.',
    'TCKLARNA_IS_ENABLED_TOOLTIP'                       => 'Włącz tutaj funkcję Klarna Instant Shopping. Spowoduje to automatyczne wygenerowanie przycisku do wykorzystania w interfejsie sklepu.',
    'TCKLARNA_IS_BUTTON_APEARANCE_HEADLINE'             => 'Ustawienia stylizacji przycisków',
    'TCKLARNA_IS_VARIATION_TOOLTIP'                     => 'Proszę wybrać między przyciskiem w pełni spójnym z wizerunkiem marki Klarna a bardziej neutralną wersją „Light”.',
    'TCKLARNA_IS_TAGLINE_TOOLTIP'                       => 'Proszę wybrać, czy kolor czcionki sloganu pod przyciskiem ma być jasny czy ciemny.',
    'TCKLARNA_IS_TYPE_TOOLTIP'                          => 'Proszę wybrać żądany napis na przycisku.',
    'TCKLARNA_IS_BUTTON_PREVIEW'                        => 'Podgląd przycisku',
    'TCKLARNA_IS_BUTTON_PLACEMENT_DETAILS'              => 'Wyświetl na stronie szczegółów produktu',
    'TCKLARNA_IS_BUTTON_PLACEMENT_DETAILS_TOOLTIP'      => 'Włącz tę funkcję, aby przycisk Klarna Instant Shopping wyświetlał się na wszystkich stronach szczegółów produktów w Twoim sklepie.',
    'TCKLARNA_IS_BUTTON_PLACEMENT_BASKET'               => 'Wyświetl w podsumowaniu koszyka',
    'TCKLARNA_IS_BUTTON_PLACEMENT_BASKET_TOOLTIP'       => 'Włącz tę funkcję, aby przycisk Klarna Instant Shopping wyświetlał się na stronie podsumowania koszyka w Twoim sklepie.',
    'TCKLARNA_IS_BUTTON_SETTINGS_HEADLINE'              => 'Dodatkowe ustawienia funkcji „Instant Shopping”',
    'TCKLARNA_IS_SETTING_ALLOW_SEPARATE_SHIPPING_ADDRESS'                   => 'Adres dostawy może różnić się od adresu rozliczeniowego',
    'TCKLARNA_IS_SETTING_ALLOW_SEPARATE_SHIPPING_ADDRESS_TOOLTIP'           => 'Jeśli chcesz umożliwić dostawę na inny adres, zaznacz to pole wyboru.',
    'TCKLARNA_IS_SETTING_DATE_OF_BIRTH_MANDATORY'                           => 'Data urodzenia jako pole obowiązkowe',
    'TCKLARNA_IS_SETTING_DATE_OF_BIRTH_MANDATORY_TOOLTIP'                   => 'Jeśli chcą Państwo, aby podanie daty urodzenia było obowiązkowe, proszę zaznaczyć to pole. Zazwyczaj w systemie Klarna data urodzenia nie jest polem obowiązkowym. Jest ona jednak niezbędna, aby umożliwić zakup na rachunek lub płatność w ratach.',
    'TCKLARNA_IS_SETTING_NATIONAL_IDENTIFICATION_NUMBER_MANDATORY'          => 'Krajowy numer identyfikacyjny jako pole obowiązkowe',
    'TCKLARNA_IS_SETTING_NATIONAL_IDENTIFICATION_NUMBER_MANDATORY_TOOLTIP'  => 'Proszę wybrać, czy numer identyfikacyjny powinien być polem obowiązkowym.',
    'TCKLARNA_IS_BUTTON_SETTINGS_VARIATION'             => 'Odmiana',
    'TCKLARNA_IS_BUTTON_SETTINGS_TAGLINE'               => 'Slogan',
    'TCKLARNA_IS_BUTTON_SETTINGS_TYPE'                  => 'Typ',
    'TCKLARNA_IS_SETTING_PHONE_MANDATORY'               => 'Numer telefonu jest polem obowiązkowym',
    'TCKLARNA_IS_SETTING_PHONE_MANDATORY_TOOLTIP'       => 'Proszę wybrać, czy numer telefonu ma być polem obowiązkowym.',
    'TCKLARNA_IS_DEFAULT_COUNTRY_TIP'                   => 'Proszę wybrać z listy kraj, który ma być domyślnie ustawiony przy uruchomieniu usługi Klarna Instant Shopping, dopóki klient nie poda jeszcze swojego kraju.',
    'TCKLARNA_IS_TERMS_URI_TIP'                         => 'W tym miejscu należy podać adres URL prowadzący do ogólnych warunków handlowych. Link do nich zostanie umieszczony w okienku pop-up Klarna Instant Shopping. Należy podać prawidłowy adres URL, zaczynający się od https://.',

    'TCKLARNA_SHIPPING_KCO'                             => 'Przypisanie metod wysyłki dla Klarna Checkout i Klarna Express',
    'TCKLARNA_SHIPPING_KCO_DESC'                        => 'Proszę przypisać zdefiniowanym przez Państwa sposobom wysyłki odpowiednie nazwy Klarna. Dzięki temu przyporządkowaniu można między innymi skonfigurować dostawę do punktów odbioru przesyłek.',
    'TCKLARNA_SHIPPING_SETTINGS'                        => 'Sposoby wysyłki',
    'TCKLARNA_COMPLETE_REFUND'                          => 'Zaksięgować całe zamówienie jako kredyt',
    'TCKLARNA_PACKSTATION_NO_SHIPPING_SET'              => 'Nie znaleziono żadnych aktywnych metod wysyłki',

    'TCKLARNA_AUTHPAYMENTMETHOD'                        => 'Wybierana metoda płatności: ',
    'TCKLARNA_AUTHPAYMENTMETHOD_unknown'                => 'Klarna',
    'TCKLARNA_AUTHPAYMENTMETHOD_direct_debit'           => 'Pobranie',
    'TCKLARNA_AUTHPAYMENTMETHOD_direct_bank_transfer'   => 'Przelew natychmiastowy',
    'TCKLARNA_AUTHPAYMENTMETHOD_slice_it_by_card'       => '3 nieoprocentowane raty',
    'TCKLARNA_AUTHPAYMENTMETHOD_fixed_sum_credit'       => 'Finansowanie',
    'TCKLARNA_AUTHPAYMENTMETHOD_b2b_invoice'            => 'Faktura B2B (Billie)',
    'TCKLARNA_AUTHPAYMENTMETHOD_pay_later_by_card'      => 'Płatność kartą w terminie 30 dni',
    'TCKLARNA_AUTHPAYMENTMETHOD_invoice'                => 'Faktura',
    'TCKLARNA_AUTHPAYMENTMETHOD_pay_by_card'            => 'Karta kredytowa',
    'TCKLARNA_AUTHPAYMENTMETHOD_bank_transfer'          => 'Przelew',
    'TCKLARNA_AUTHPAYMENTMETHOD_card'                   => 'Karta kredytowa',
    'TCKLARNA_AUTHPAYMENTMETHOD_fixed_amount'           => 'Finansowanie',
    'TCKLARNA_AUTHPAYMENTMETHOD_invoice_business'       => 'Faktura B2B (Billie)',
    'TCKLARNA_AUTHPAYMENTMETHOD_mobilepay'              => 'MobilePay',
    'TCKLARNA_AUTHPAYMENTMETHOD_pay_later_in_parts'     => 'Klarna – Płać później w ratach',
    'TCKLARNA_AUTHPAYMENTMETHOD_swish'                  => 'Swish',
    'TCKLARNA_AUTHPAYMENTMETHOD_apple_pay_card'         => 'Apple Pay',
    'TCKLARNA_AUTHPAYMENTMETHOD_google_pay_card'        => 'Google Pay',
    'TCKLARNA_AUTHPAYMENTMETHOD_cartes_bancaires'       => 'Karty bankowe',
    'TCKLARNA_AUTHPAYMENTMETHOD_blik'                   => 'BLIK',
    'TCKLARNA_AUTHPAYMENTMETHOD_twint'                  => 'TWINT',
    'TCKLARNA_AUTHPAYMENTMETHOD_bancontact'             => 'Bancontact',
    'TCKLARNA_AUTHPAYMENTMETHOD_diners'                 => 'Karta kredytowa',
    'TCKLARNA_AUTHPAYMENTMETHOD_discover'               => 'Karta kredytowa',
    'TCKLARNA_AUTHPAYMENTMETHOD_elo'                    => 'Karta kredytowa',
    'TCKLARNA_AUTHPAYMENTMETHOD_jcb'                    => 'Karta kredytowa',
    'TCKLARNA_AUTHPAYMENTMETHOD_union_pay'              => 'Karta kredytowa',
    'TCKLARNA_AUTHPAYMENTMETHOD_pay_by_bank'            => 'Płatność przelewem bankowym',
    'TCKLARNA_AUTHPAYMENTMETHOD_other'                  => 'Niestandardowy proces realizacji zamówienia',
);
